ICED_Physics: IonMigration Class Reference
IonMigration Class Reference
Physics module for ion migration.
Detailed Description
Physics module for ion migration.
Definition at line 1203 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
IonMigration ()
Default constructor.
IonMigration (SolutionData *solutionData, GlobalType &globin)
~IonMigration ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
The IonMigration SolvePhysics function.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
IonMigration () inline
Default constructor.
Definition at line 1210 of file PhysicsModule.hpp.
References OhmsLawElectrolyte::Initialize().
 {Initialize();};
IonMigration (SolutionData * solutionData, GlobalType & globin) inline
Definition at line 1215 of file PhysicsModule.hpp.
References IonMigration::Initialize().
                                                                  : PhysicsModule(solutionData, globin) {
       IonMigration::Initialize();
     };
~IonMigration () inline
Default destructor.
Definition at line 1222 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 1231 of file PhysicsModule.hpp.
References ICED::HalfCell::conc_e, PhysicsModule::idealParameters, PhysicsModule::moduleName, and PhysicsModule::variableIndex.
Referenced by IonMigration::IonMigration().
                       {
       moduleName="IonMigration";
       SetName(moduleName);
       variableIndex=conc_e;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("chargeNumber","1"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numberOfIons","2"));
      idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("faradayConstant","3"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("gasConstant","4"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","5"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("electrolyteConductivity","6"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("electrolyteVolumeFraction","7"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("stoichParameter","9"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numberOfElectrons","10"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("bruggemanCoefficient","11"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","11"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("TransferenceNumber","1"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ActivityCoefficient","1"));
     };
void SolvePhysics () virtual
The IonMigration SolvePhysics function.
The Ion Migration module (represent in-function as ionMigFunc(numNodes)) is defined as a subsection of the time-dependent diffusion of lithium ions in the electrolyte equation below
where the right hand side of the equation is solved (in order) between the Diffusion, IonMigration and WallFlux modules. The part we're interested in, is the middle part of the equation
where can be represented as (see OhmsLawElectrolyte).
For the module, the ion migration equation is rewritten as
where . The charge number, , the number of ions into which one mole of electrolye dissociates, , and Faraday's constant, are represented by the variables chargeNumber, numberOfIons, faradayConstant, respectively.
Before the discretized ion migration and it's non-zero jacobians are calculated, the function proceeds to go ahead and defined a multitude of additional variables.
The function defines a relationship between the effectiveElectrolyteConductivity, , and the electrolyteConductivity, , via the equation below, where is the electrolyteVolumeFraction.
It also defines the TransferenceNumber and it's first two derivatives as transferenceNumber, transferenceNumberP, and transferenceNumberPP. The relationship between the transference number and its first derivative is
with (defined as the vector deltaConce(numNodes)) defined below with regular spacing)
.
The ion migration module utilizes the ActivityCoefficient as well as its first two derivatives (represented by activity Coefficient, activityCoefficientP and activityCoefficientDP) in order to calculate the diffusion electrolyte conductivity (used by the vector diffusionElectrolyteConductivity(numNodes)) as well as its derivative or (diffusionElectrolyteConductivityP(numNodes)).
when implemented gives the equation
where activitycoefficientP is represented as . The function also goes on ahead to define as
where the stoichParameter (stoichiometric coefficient of species i in an electrode reaction) and numberOfElectrons are used throughout.
Now that all the pieces are defined, in order to compute ionMigFunc using the central difference scheme (discretizing the module), the function defines as
represented by deltaElectricPotential. Which allows the use of the discrete ion migration equation for a non - uniform mesh.
The non-zero Jacobian contribution (for non-uniform meshes) are calculated (in the presented order) at the end of the function.
Also note that even though this isn't present within the module below.
Implements PhysicsModule.
Definition at line 19 of file IonMigration.cpp.
References SolutionData::activityCoefficient, SolutionData::activityCoefficientDer, SolutionData::activityCoefficientDerDer, SolutionData::bruggemanCoefficient, SolutionData::chargeNumber, ICED::HalfCell::conc_e, SolutionData::dx, SolutionData::electrolyteConductivity, SolutionData::electrolyteVolumeFraction, SolutionData::faradayConstant, SolutionData::function, SolutionData::gasConstant, SolutionData::iStartInternal, SolutionData::jacobian, SolutionData::numberOfElectrons, SolutionData::numberOfIons, SolutionData::numNodes, ICED::HalfCell::phi_e, PhysicsModule::pSolutionData, SolutionData::solutionData, SolutionData::stoichParameter, SolutionData::temperature, SolutionData::transferenceNumber, SolutionData::transferenceNumberDer, SolutionData::transferenceNumberDerDer, and SolutionData::xCoords.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     Ostr << "Hello from SolvePhysics" << std::endl;
     double chargeNumber = pSolutionData->chargeNumber; // z_i
     double numberOfIons = pSolutionData->numberOfIons; // nu_i
     const double faradayConstant = pSolutionData->faradayConstant; // Faraday's constant
     const double gasConstant = pSolutionData->gasConstant;
     double temperature = pSolutionData->temperature;
     double electrolyteConductivity = pSolutionData->electrolyteConductivity; // \kappa_0
     double electrolyteVolumeFraction = pSolutionData->electrolyteVolumeFraction; // \epsilon
     //double effectiveElectrolyteConductivity = pSolutionData->effectiveElectrolyteConductivity; // \kappa
     double stoichParameter = pSolutionData->stoichParameter; // s_i
     double numberOfElectrons = pSolutionData->numberOfElectrons; // n
     int numNodes = pSolutionData->numNodes;
     int iStartIn = pSolutionData->iStartInternal-1;
     int iEndIn = pSolutionData-> iEndInternal+1;
     // Definie \kappa = \kappa_0 * \epsilon^{3/2}
     double effectiveElectrolyteConductivity = electrolyteConductivity *
          pow(electrolyteVolumeFraction, pSolutionData->bruggemanCoefficient);
     //Print out variables to check
     Ostr << "chargeNumber = " << chargeNumber << std::endl
          << "numberOfIons = " << numberOfIons << std::endl
          << "faradayConstant = " << faradayConstant << std::endl
          << "gasConstant = " << gasConstant << std::endl
          << "temperature = " << temperature << std::endl
          << "electrolyteConductivity = "
          << electrolyteConductivity << std::endl
          << "electrolyteVolumeFraction = "
          << electrolyteVolumeFraction << std::endl
          << "effectiveElectrolyteConductivity = "
          << effectiveElectrolyteConductivity << std::endl
          << "stoichParameter = " << stoichParameter << std::endl
          << "numberOfElectrons = " << numberOfElectrons << std::endl;
     std::vector<double> *transferenceNumber; // t^{0}_{i}
     std::vector<double> *transferenceNumberP; // t'^{0}_{i}
     std::vector<double> *transferenceNumberPP; // t''^{0}_{i}
     transferenceNumber = &pSolutionData->transferenceNumber;
     transferenceNumberP = &pSolutionData->transferenceNumberDer;
     transferenceNumberPP = &pSolutionData->transferenceNumberDerDer;
     std::vector<double> *activityCoefficient; // f_{+/-}
     std::vector<double> *activityCoefficientP; // f'^{+/-}
     std::vector<double> *activityCoefficientDP; // f''^{+/-}
     activityCoefficient = &pSolutionData->activityCoefficient;
     activityCoefficientP = &pSolutionData->activityCoefficientDer;
     activityCoefficientDP = &pSolutionData->activityCoefficientDerDer;
     std::vector<double> ionMigFunc(numNodes); // \phi_m
     std::vector<double> deltaConce(numNodes); // \Delta c_i
     std::vector<double> deltaElectricPotential(numNodes); // \Delta \Phi
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     std::vector<double> diffusionElectrolyteConductivity(numNodes); // \kappa_D
     std::vector<double> diffusionElectrolyteConductivityP(numNodes);// \kappa_D'
     // Define \kappa_D
     // \kappa_D = (\kappa*R*T/F)*(1 + c_i/f_{+/-} + (\partial f_{+/-})/
     //      (\partial c_i))(s_i/(n\nu_i) + t^{0}_{i}/(z_i\nu_i))
     for(int i = iStartIn; i<= iEndIn; ++i){
       diffusionElectrolyteConductivity[i] =
         (effectiveElectrolyteConductivity*gasConstant*temperature/faradayConstant) *
         (stoichParameter/(numberOfElectrons*numberOfIons) +
         ((*transferenceNumber)[i]/(chargeNumber*numberOfIons)));
       if ((*activityCoefficient)[i] != 0) {
         diffusionElectrolyteConductivity[i]*=(1 + ((*pSolution)[i][conc_e]*
           (*activityCoefficientP)[i]/(*activityCoefficient)[i]));
       }
       Ostr << "(*activityCoefficient)[i] = " << (*activityCoefficient)[i] << std::endl;
       Ostr << "diffusionElectrolyteConductivity[" << i << "] = "
            << diffusionElectrolyteConductivity[i] << std::endl;
     }
     // Define \kappa_D'
     for(int i = iStartIn; i<= iEndIn; ++i){
       diffusionElectrolyteConductivityP[i] = (effectiveElectrolyteConductivity *
            gasConstant * temperature / (faradayConstant*numberOfIons)) *
            ((((*activityCoefficientP)[i] / (*activityCoefficient)[i])*(
            1-((*pSolution)[i][conc_e]*(*activityCoefficientP)[i]) / (*activityCoefficient)[i]) +
            (*pSolution)[i][conc_e]*(*activityCoefficientDP)[i]/(*activityCoefficient)[i]) *
            (stoichParameter/numberOfElectrons + (*transferenceNumber)[i]/chargeNumber) +
            ((*transferenceNumberP)[i]/chargeNumber)*(1+(*pSolution)[i][conc_e] *
            (*activityCoefficientP)[i]/ (*activityCoefficient)[i]));
       Ostr << "diffusionElectrolyteConductivity[" << i << "] = "
            << diffusionElectrolyteConductivity[i] << std::endl;
     }
     // define \Delta c_i and \Delta \Phi using the central difference scheme
     //double h = 1.0;
     for(int i = iStartIn; i <= iEndIn; ++i){
       deltaConce[i]=((*pSolution)[i+1][conc_e]-(*pSolution)[i-1][conc_e]);
       deltaElectricPotential[i]=((*pSolution)[i+1][phi_e]-(*pSolution)[i-1][phi_e]);
       Ostr << "deltaConce[" << i << "] = " << deltaConce[i] << std::endl;
       Ostr << "deltaElectricPotential[" << i << "] = "
            << deltaElectricPotential[i] << std::endl;
     }
     double h = 2*pSolutionData->dx;
     // \phi_m = t'^{0}_{i}/(z_i*v_i*F) * (\kappa (\Delta c_i * \Delta \Phi) + \kappa_D/c_i *(\Delta c_i)^2)
     for(int i = iStartIn; i<= iEndIn; ++i){
       if (i == iStartIn)
         h = pSolutionData->xCoords[iStartIn+1]-pSolutionData->xCoords[iStartIn-1];
       else if (i == iEndIn)
         h = pSolutionData->xCoords[iEndIn+1]-pSolutionData->xCoords[iEndIn-1];
       Ostr << "(*pSolution)[i][conc_e] = " << (*pSolution)[i][conc_e] << std::endl;
       ionMigFunc[i] = ((*transferenceNumberP)[i] / (chargeNumber*numberOfIons*faradayConstant*h*h)) *
            (effectiveElectrolyteConductivity * (deltaConce[i] * deltaElectricPotential[i]) +
            ((diffusionElectrolyteConductivity[i] / (*pSolution)[i][conc_e]) *
            ((deltaConce[i]*deltaConce[i]))));
       (*pSolutionData->function)[i][conc_e] += ionMigFunc[i]/
         pSolutionData->electrolyteVolumeFraction;
       //Print out function value for debugging
       Ostr << "computed Ion Migration Function " << ionMigFunc[i] << std::endl;
       if (i == iStartIn)
         h = 2*pSolutionData->dx;
     }
     // Jacobian values
     h = 2*pSolutionData->dx;
     for(int i = iStartIn; i<=iEndIn; ++i){
       if (i == iStartIn)
         h = pSolutionData->xCoords[iStartIn+1]-pSolutionData->xCoords[iStartIn-1];
       else if (i == iEndIn)
         h = pSolutionData->xCoords[iEndIn+1]-pSolutionData->xCoords[iEndIn-1];
       // (\partial \phi_m) / (\partial c_{kn})
       (*pSolutionData->jacobian)[i][i][0][conc_e] =
            (1/(chargeNumber*numberOfIons*faradayConstant*h*h)) *
            ((*transferenceNumberPP)[i]*((effectiveElectrolyteConductivity *
            (deltaConce[i] * deltaElectricPotential[i]) +
            ((diffusionElectrolyteConductivity[i] / (*pSolution)[i][conc_e]) *
            ((deltaConce[i]*deltaConce[i])))))+
            (*transferenceNumberP)[i]*(diffusionElectrolyteConductivityP[i]/(*pSolution)[i][conc_e] -
            diffusionElectrolyteConductivity[i]/((*pSolution)[i][conc_e]*(*pSolution)[i][conc_e])) *
            ((deltaConce[i])*(deltaConce[i])));
       // (\partial \phi_m) / (\partial c_{k(n+1)})
       (*pSolutionData->jacobian)[i][i+1][0][conc_e] =
            ((*transferenceNumberP)[i]/(chargeNumber*numberOfIons*faradayConstant*h*h)) *
            (effectiveElectrolyteConductivity*(deltaElectricPotential[i]) +
            (2*diffusionElectrolyteConductivity[i]/(*pSolution)[i][conc_e])*(deltaConce[i]));
       // (\partial \phi_m) / (\partial c_{k(n-1)})
       (*pSolutionData->jacobian)[i][i-1][0][conc_e] = -(*pSolutionData->jacobian)[i][i+1][0][conc_e];
       // (\partial \phi_m) / (\partial \Phi_{k(n+1)})
       (*pSolutionData->jacobian)[i][i+1][0][phi_e] =
            ((*transferenceNumberP)[i]*effectiveElectrolyteConductivity /
            (chargeNumber*numberOfIons*faradayConstant*h*h))*(deltaConce[i]);
       // (\partial \phi_m) / (\partial \Phi_{k(n-1)})
       (*pSolutionData->jacobian)[i][i-1][0][phi_e] = - (*pSolutionData->jacobian)[i][i+1][0][phi_e];
       if (i == iStartIn)
         h = 2*pSolutionData->dx;
     }
     Ostr << std::endl;
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
The documentation for this class was generated from the following files:
PhysicsModule.hpp
IonMigration.cpp