ICED_Physics: DeviceComponent Class Reference
DeviceComponent Class Reference
Class to hold the solution data for the electro-chemical device solver.
Detailed Description
Class to hold the solution data for the electro-chemical device solver.
This class contains all the global solution data used to produce a solution for an electrochemical device. It specifies the modules needed to model a specific components or piece of the device, i.e. a current collector, electrode, separator, etc. The actual make-up of the components is defined by the physics modules enabled for each component.
Definition at line 41 of file DeviceComponent.hpp.
#include <Physics/include/DeviceComponent.hpp>
Public Member Functions
DeviceComponent ()
Simulation input data structure.
DeviceComponent (const std::vector< std::string > &inputNames, const SolutionData &solnData, GlobalType &globin)
Simulation input data structure.
~DeviceComponent ()
Default destructor.
void Initialize ()
Initialization of the input data from input file.
int LoadModules (IRAD::Util::Parameters params)
Load the desired modules based on the input file.
int InitializeBoundary (IRAD::Util::Parameters params)
Read the boundary types from the input parameter and initialize.
int SetupComponentMesh (const int &firstNode)
Setup the component to global mapping for this component.
int InitializeComponentSolution ()
Set initial values for component solution data.
int InitializeComponent ()
Performs initialization required to calculate component level solutions.
int InitializeComponentPhysics ()
Performs initialization of physics module data outside of timestepping.
int SolveComponent ()
Populate the component solution matricies.
int ApplyComponentBC ()
Apply the appropriate component boundary conditions.
int ApplyInternalBC ()
Apply internal boundary conditions.
int FinalizeComponent ()
Performs finalization required after calculating component level solutions.
Static Public Member Functions
static bool ModulePriorityCompare (PhysicsModule *first, PhysicsModule *second)
Compare the priority of two modules.
Public Attributes
std::vector< std::string > inputDataIntString
storage for input values and input value descriptors
std::vector< int * > inputDataInt
std::vector< std::string > inputDataDoubleString
std::vector< double * > inputDataDouble
std::vector< std::string > inputDataModuleString
std::vector< int > inputDataModulePriority
std::vector< std::string > inputDataBoundaryString
std::vector< PhysicsModule * > componentPhysicsModules
SolutionData * pSolutionData
std::string componentName
std::string componentInputFile
std::vector< int > leftBCType
boundary condition data.
std::vector< int > rightBCType
std::vector< double > leftBCValue
std::vector< double > rightBCValue
global_ordinal_type * myDeviceNodes
mapping to device vector space
Constructor & Destructor Documentation
DeviceComponent () inline
Simulation input data structure.
To add a new input parameter, add it to the list below and add the associated variable in the class.
Definition at line 51 of file DeviceComponent.hpp.
References DeviceComponent::Initialize(), and DeviceComponent::pSolutionData.
                       : GlobalType() {
       Initialize();
       pSolutionData = new ICED::HalfCell::SolutionData();
     };
DeviceComponent (const std::vector< std::string > & inputNames, const SolutionData & solnData, GlobalType & globin) inline
Simulation input data structure.
Parameters
inputNames - A vector with two strings. The first names the object and the second provides an input file to be read.
solnData - A SolutionData object
globin - A GlobalType object
Returns
Pointer to a DeviceComponent.
Todo:
Does SolutionData need a Copy constructor, or is a shallow copy ok here?
Evaluate this whole thing for a refactor. Surely I can make this better...
Definition at line 69 of file DeviceComponent.hpp.
References SolutionData::activityCoefficients, SolutionData::anodicRateConstant, SolutionData::bruggemanCoefficient, SolutionData::cathodicRateConstant, SolutionData::chargeNumber, DeviceComponent::componentInputFile, DeviceComponent::componentName, SolutionData::concentrationDiffusionCoefficients, SolutionData::coulombicCapacity, SolutionData::electrolyteActivityCoefficient, SolutionData::electrolyteConductivity, SolutionData::electrolyteDensity, SolutionData::electrolyteVolumeFraction, SolutionData::faradayConstant, SolutionData::gasConstant, SolutionData::initialElectrolyteLiConcentration, SolutionData::initialElectrolytePotential, SolutionData::initialElectronProductionRate, DeviceComponent::Initialize(), SolutionData::initialSaltConcentration, SolutionData::initialSolidLiConcentration, SolutionData::initialSolidPotential, SolutionData::numberOfElectrons, SolutionData::numberOfIons, SolutionData::openCircuitPotential, SolutionData::polymerMaxConcentration, SolutionData::poreRadius, DeviceComponent::pSolutionData, SolutionData::rateConstant, SolutionData::solidConductivity, SolutionData::solidDensity, SolutionData::solidDiffusionCoefficient, SolutionData::solidTransferenceNumber, SolutionData::stoichParameter, SolutionData::symmetryParameter, SolutionData::temperature, SolutionData::transferenceCoefficients, and SolutionData::velocityOfSpeciesI.
                                                                                                               : GlobalType(globin) {
       Initialize();
       componentName = inputNames[0];
       componentInputFile = inputNames[1];
       SetName(componentName);
       // make a new SolutionData object. We will copy the old data into this one.
       pSolutionData = new ICED::HalfCell::SolutionData(*this);
       // copy the solutionData object member data to our solution data object
       // this is annoying, because if I add a variable in solutionData I have
       // to add it here to ensure that everything works right.
       // This is a testing nightmare.
       pSolutionData->initialSaltConcentration=solnData.initialSaltConcentration;
       pSolutionData->stoichParameter = solnData.stoichParameter;
       pSolutionData->temperature = solnData.temperature;
       pSolutionData->solidDiffusionCoefficient = solnData.solidDiffusionCoefficient;
       pSolutionData->electrolyteVolumeFraction = solnData.electrolyteVolumeFraction;
       pSolutionData->solidConductivity = solnData.solidConductivity;
       pSolutionData->electrolyteConductivity = solnData.electrolyteConductivity;
       pSolutionData->rateConstant = solnData.rateConstant;
       pSolutionData->coulombicCapacity = solnData.coulombicCapacity;
       pSolutionData->electrolyteDensity = solnData.electrolyteDensity;
       pSolutionData->solidDensity = solnData.solidDensity;
       pSolutionData->electrolyteActivityCoefficient = solnData.electrolyteActivityCoefficient;
       pSolutionData->solidTransferenceNumber = solnData.solidTransferenceNumber;
       pSolutionData->initialElectrolytePotential =
       solnData.initialElectrolytePotential;
       pSolutionData->initialSolidPotential =
       solnData.initialSolidPotential;
       pSolutionData->initialElectrolyteLiConcentration =
       solnData.initialElectrolyteLiConcentration;
       pSolutionData->initialSolidLiConcentration =
       solnData.initialSolidLiConcentration;
       pSolutionData->initialElectronProductionRate =
       solnData.initialElectronProductionRate;
       pSolutionData->symmetryParameter =
       solnData.symmetryParameter;
       pSolutionData->polymerMaxConcentration =
       solnData.polymerMaxConcentration;
       pSolutionData->cathodicRateConstant =
       solnData.cathodicRateConstant;
       pSolutionData->anodicRateConstant =
       solnData.anodicRateConstant;
       pSolutionData->bruggemanCoefficient =
       solnData.bruggemanCoefficient;
       pSolutionData->openCircuitPotential =
       solnData.openCircuitPotential;
       pSolutionData->faradayConstant =
       solnData.faradayConstant;
       pSolutionData->gasConstant =
       solnData.gasConstant;
       pSolutionData->poreRadius =
       solnData.poreRadius;
       pSolutionData->velocityOfSpeciesI =
       solnData.velocityOfSpeciesI;
       pSolutionData->chargeNumber =
       solnData.chargeNumber;
       pSolutionData->numberOfIons =
       solnData.numberOfIons;
       //pSolutionData->effectiveElectrolyteConductivity =
       //solnData.effectiveElectrolyteConductivity;
       pSolutionData->numberOfElectrons =
       solnData.numberOfElectrons;
       pSolutionData->transferenceCoefficients =
       solnData.transferenceCoefficients;
       pSolutionData->concentrationDiffusionCoefficients =
       solnData.concentrationDiffusionCoefficients;
       pSolutionData->activityCoefficients =
       solnData.activityCoefficients;
       // now read the input file
     };
~DeviceComponent () inline
Default destructor.
Definition at line 151 of file DeviceComponent.hpp.
 {};
Member Function Documentation
int ApplyComponentBC ()
Apply the appropriate component boundary conditions.
Use the boundary conditions implemented by each physics module to set the component boundary conditions for the component level solution matricies.
Only call boundary condition routines for physics modules that have a valid variableIndex. This indicates that the equations solved by the physics module are included in the global solution matrix and excludes modules that calculate spatially varying material properties
Returns
int an error code
Test:
None
Definition at line 307 of file DeviceComponent.cpp.
References DeviceComponent::componentPhysicsModules, ICED::HalfCell::dirichlet, ICED::HalfCell::left, DeviceComponent::leftBCType, DeviceComponent::leftBCValue, ICED::HalfCell::neumann, ICED::HalfCell::right, DeviceComponent::rightBCType, DeviceComponent::rightBCValue, and ICED::HalfCell::solutionVariable_t_MAX.
Referenced by DeviceComponent::InitializeComponentPhysics(), and DeviceComponent::SolveComponent().
{
       std::ostringstream Ostr;
       Ostr << std::endl;
       StdOut(Ostr.str(),3);
       // loop over all modules and call the appropriate boundary routines
       // note that we only apply boundary conditions from modules that have a
       // valid variableIndex (equal to one of the solution variables).
       //
       // This gets done at every solution step, probably not a major
       // drag on the simulation efficiency. This could be improved by calculating
       // only the boundary conditions routines that are be called a priori during
       // problem generation
       //
       for (size_t i=0; i<componentPhysicsModules.size(); ++i) {
         int position = left;
         for (int j=0; j<solutionVariable_t_MAX; ++j) {
           if (componentPhysicsModules[i]->variableIndex == j) {
             int bcType = leftBCType[j];
             double bcVal = leftBCValue[j];
             switch ( bcType ) {
             case dirichlet:
               componentPhysicsModules[i]->ApplyDirichletBC(position, bcVal);
               break;
             case neumann:
               componentPhysicsModules[i]->ApplyNeumannBC(position, bcVal);
               break;
             }
           }
         }
         position = right;
         for (int j=0; j<solutionVariable_t_MAX; ++j) {
           if (componentPhysicsModules[i]->variableIndex == j) {
             int bcType = rightBCType[j];
             double bcVal = rightBCValue[j];
             switch ( bcType ) {
             case dirichlet:
               componentPhysicsModules[i]->ApplyDirichletBC(position, bcVal);
               break;
             case neumann:
               componentPhysicsModules[i]->ApplyNeumannBC(position, bcVal);
               break;
             }
           }
         }
       }
       return(0);
     } // Function ApplyComponentBC
int ApplyInternalBC ()
Apply internal boundary conditions.
Loop over all the solution variables and apply the internal boundary condition. This averages the solution and function evaluation by the number of overlapping grid points (in this case 2 for 1-D). This is applied to every solution variable that has an internal boundary set. This should be applied only once during a call to the component solve.
Returns
int an error code
Test:
None
Definition at line 357 of file DeviceComponent.cpp.
References SolutionData::function, SolutionData::iEndInternal, SolutionData::iStartInternal, DeviceComponent::leftBCType, DeviceComponent::pSolutionData, DeviceComponent::rightBCType, SolutionData::solutionData, and ICED::HalfCell::solutionVariable_t_MAX.
Referenced by DeviceComponent::InitializeComponentPhysics(), and DeviceComponent::SolveComponent().
{
       std::ostringstream Ostr;
       Ostr << std::endl;
       StdOut(Ostr.str(),3);
       //
       // loop over all solution variables and apply internal
       // boundary conditions where prescribed
       //
       int leftIndex = pSolutionData->iStartInternal-1;
       int rightIndex = pSolutionData->iEndInternal+1;
       for (int i=0; i<solutionVariable_t_MAX; ++i) {
         if (leftBCType[i] == internal) {
           (*pSolutionData->solutionData)[leftIndex][i]/=2.;
           (*pSolutionData->function)[leftIndex][i]/=2.;
         }
         if (rightBCType[i] == internal) {
           (*pSolutionData->solutionData)[rightIndex][i]/=2.;
           (*pSolutionData->function)[rightIndex][i]/=2.;
         }
       }
       return(0);
     } // Function ApplyInternalBC
int FinalizeComponent ()
Performs finalization required after calculating component level solutions.
This function does the following:
Transfers the component solution data from vector storage to Epetra storage This task will be refactored in future code versions
function
jacobian (not yet implemented)
Returns
int an error code
Test:
None
Definition at line 510 of file DeviceComponent.cpp.
References SolutionData::function, SolutionData::functionEpetra, SolutionData::myGlobalElements, SolutionData::numMyElements, DeviceComponent::pSolutionData, SolutionData::solutionData, SolutionData::solutionEpetra, and ICED::HalfCell::solutionVariable_t_MAX.
Referenced by DeviceComponent::InitializeComponentPhysics(), and DeviceComponent::SolveComponent().
{
       std::ostringstream Ostr;
       // transfer function data and solution data from vector storage
       // to Epetra storage. We only do the solution data to catch any
       // changes to the solution data at the boundary nodes
       for (int i=0; i<solutionVariable_t_MAX; ++i) {
         for (int j=0; j<pSolutionData->numMyElements; ++j) {
           global_ordinal_type rowIndex = pSolutionData->myGlobalElements[j];
           double data = (*pSolutionData->function)[rowIndex][i];
           int lclerr = pSolutionData->functionEpetra->
                        ReplaceGlobalValue(rowIndex, i, data);
           if (lclerr != 0) {
             Ostr << "Error copying function data to the components" << std::endl;
             StdOut(Ostr.str());
             return(lclerr);
           }
           data = (*pSolutionData->solutionData)[rowIndex][i];
           lclerr = pSolutionData->solutionEpetra->
                        ReplaceGlobalValue(rowIndex, i, data);
           if (lclerr != 0) {
             Ostr << "Error copying solution data to the components" << std::endl;
             StdOut(Ostr.str());
             return(lclerr);
           }
         }
       }
       StdOut(Ostr.str(),3);
       return 0;
     } // Function FinalizeComponent
void Initialize () inline
Initialization of the input data from input file.
Utilizes inputData<type>String and inputData<type> to set our input data. Where <type> is int or double. Adding values to these arrays to read in additional input data.
Each DeviceComponent has it's own SolutionData object. We copy the data from the device level and then read the input file to overwrite the data.
Returns
void
Test:
None
Todo:
This is a candiate for refactor. I think this is more than a little confusing and there is a bit of code duplication between SolutionData and DeviceComponent
Add a new string to this list to add a physics module
Definition at line 171 of file DeviceComponent.hpp.
References SolutionData::coulombicCapacity, SolutionData::electrolyteActivityCoefficient, SolutionData::electrolyteConductivity, SolutionData::electrolyteDensity, SolutionData::electrolyteVolumeFraction, SolutionData::initialSaltConcentration, DeviceComponent::inputDataBoundaryString, DeviceComponent::inputDataDouble, DeviceComponent::inputDataDoubleString, DeviceComponent::inputDataInt, DeviceComponent::inputDataIntString, DeviceComponent::inputDataModuleString, DeviceComponent::leftBCType, DeviceComponent::leftBCValue, ICED::HalfCell::none, SolutionData::numNodes, DeviceComponent::pSolutionData, SolutionData::rateConstant, DeviceComponent::rightBCType, DeviceComponent::rightBCValue, SolutionData::solidConductivity, SolutionData::solidDensity, SolutionData::solidDiffusionCoefficient, SolutionData::solidTransferenceNumber, ICED::HalfCell::solutionVariable_t_MAX, SolutionData::stoichParameter, SolutionData::temperature, SolutionData::xMax, and SolutionData::xMin.
Referenced by DeviceComponent::DeviceComponent().
                       {
       SetName("DeviceComponent");
       // initialize ints
       inputDataIntString.push_back("numNodes");
       inputDataInt.push_back(&(pSolutionData->numNodes));
       // initialize doubles
       inputDataDoubleString.push_back("xMin");
       inputDataDouble.push_back(&(pSolutionData->xMin));
       inputDataDoubleString.push_back("xMax");
       inputDataDouble.push_back(&(pSolutionData->xMax));
       inputDataDoubleString.push_back("initialSaltConcentration");
       inputDataDouble.push_back(&(pSolutionData->initialSaltConcentration));
       inputDataDoubleString.push_back("stoichParameter");
       inputDataDouble.push_back(&(pSolutionData->stoichParameter));
       inputDataDoubleString.push_back("temperature");
       inputDataDouble.push_back(&(pSolutionData->temperature));
       inputDataDoubleString.push_back("solidDiffusionCoefficient");
       inputDataDouble.push_back(&(pSolutionData->solidDiffusionCoefficient));
       inputDataDoubleString.push_back("electrolyteVolumeFraction");
       inputDataDouble.push_back(&(pSolutionData->electrolyteVolumeFraction));
       inputDataDoubleString.push_back("solidConductivity");
       inputDataDouble.push_back(&(pSolutionData->solidConductivity));
       inputDataDoubleString.push_back("electrolyteConductivity");
       inputDataDouble.push_back(&(pSolutionData->electrolyteConductivity));
       inputDataDoubleString.push_back("rateConstant");
       inputDataDouble.push_back(&(pSolutionData->rateConstant));
       inputDataDoubleString.push_back("coulombicCapacity");
       inputDataDouble.push_back(&(pSolutionData->coulombicCapacity));
       inputDataDoubleString.push_back("electrolyteDensity");
       inputDataDouble.push_back(&(pSolutionData->electrolyteDensity));
       inputDataDoubleString.push_back("solidDensity");
       inputDataDouble.push_back(&(pSolutionData->solidDensity));
       inputDataDoubleString.push_back("electrolyteActivityCoefficient");
       inputDataDouble.push_back(&(pSolutionData->electrolyteActivityCoefficient));
       inputDataDoubleString.push_back("solidTransferenceNumber");
       inputDataDouble.push_back(&(pSolutionData->solidTransferenceNumber));
       inputDataModuleString.push_back("TransferenceNumber");
       inputDataModuleString.push_back("ConcentrationDiffusion");
       inputDataModuleString.push_back("ActivityCoefficient");
       inputDataModuleString.push_back("ionMigration");
       inputDataModuleString.push_back("IonMigration");
       inputDataModuleString.push_back("electronMigration");
       inputDataModuleString.push_back("ButlerVolmer");
       inputDataModuleString.push_back("WallFlux");
       inputDataModuleString.push_back("Diffusion");
       inputDataModuleString.push_back("OhmsLawElectrolyte");
       inputDataModuleString.push_back("OhmsLawSolid");
       inputDataModuleString.push_back("IonMigration");
       inputDataModuleString.push_back("Intercalation");
       inputDataModuleString.push_back("testModule");
       // initialize boundary data
       inputDataBoundaryString.push_back("leftBC");
       inputDataBoundaryString.push_back("rightBC");
       // solutionVariable_t_MAX is the last item of the solutionVariable_t enumeration
       // and thus the number of equations/variables
       leftBCType.resize(solutionVariable_t_MAX,none);
       rightBCType.resize(solutionVariable_t_MAX,none);
       leftBCValue.resize(solutionVariable_t_MAX,0.);
       rightBCValue.resize(solutionVariable_t_MAX,0.);
     };
int InitializeBoundary (IRAD::Util::Parameters params)
Read the boundary types from the input parameter and initialize.
Parameters
params Contains input parameters to be used
Returns
int an error code
Test:
None
Todo:
Add test
Definition at line 18 of file DeviceComponent.cpp.
References DeviceComponent::componentName, ICED::HalfCell::conc_e, ICED::HalfCell::dirichlet, DeviceComponent::inputDataBoundaryString, DeviceComponent::leftBCType, DeviceComponent::leftBCValue, ICED::HalfCell::neumann, ICED::HalfCell::phi_e, ICED::HalfCell::phi_s, DeviceComponent::rightBCType, and DeviceComponent::rightBCValue.
{
     FunctionEntry("InitializeBoundary");
     std::ostringstream Ostr, Cstr;
     std::string inputVal;
     std::vector<std::string> temp;
     for(size_t i=0; i<inputDataBoundaryString.size(); ++i) {
       inputVal = inputDataBoundaryString[i];
       if(params.IsSet(inputVal)) {
         // this can be refactored to avoid duplicate code
         // write a function that takes the boundary position
         // and the input string as input.
         if (inputVal == "leftBC") {
           Cstr << "Setting left boundary values in component "
                << componentName << std::endl;
           temp = params.GetValueVector(inputVal);
           if( temp[0] == "currentCollector") {
             leftBCType[phi_e]=neumann;
             leftBCValue[phi_e]=0.;
             leftBCType[conc_e]=neumann;
             leftBCValue[conc_e]=0.;
             if (temp[1] == "current") {
               leftBCType[phi_s] = neumann;
               leftBCValue[phi_s] = std::strtod(temp[2].c_str(),NULL);
             } else if (temp[1] == "voltage") {
               leftBCType[phi_s]=dirichlet;
               leftBCValue[phi_s] = std::strtod(temp[2].c_str(),NULL);
             } else {
               Cstr << "Invalid current collector mode. Expected either "
                    << "\"Current\" or \"voltage\". Exiting..." << std::endl;
               StdOut(Cstr.str(),3);
               FunctionExit("InitializeBoundary");
               return(1);
             }
           } else if ( temp[0] == "separator" ) {
             //InitializeSeparator(BCpos);
             leftBCType[phi_s] = neumann;
             leftBCValue[phi_s] = 0.;
             leftBCType[phi_e] = internal;
             leftBCValue[phi_e] = 0.;
             leftBCType[conc_e] = internal;
             leftBCValue[conc_e] = 0;
           } else {
             Cstr << "Invalid boundary type. Expected either "
                  << "\"currentCollector\" or \"separator\". Exiting..." << std::endl;
             StdOut(Cstr.str(),3);
             FunctionExit("InitializeBoundary");
             return(1);
           }
         } else if (inputVal == "rightBC") {
           Cstr << "Setting right boundary values in component "
                << componentName << std::endl;
           temp = params.GetValueVector(inputVal);
           if( temp[0] == "currentCollector") {
             rightBCType[phi_e]=neumann;
             rightBCValue[phi_e]=0.;
             rightBCType[conc_e]=neumann;
             rightBCValue[conc_e]=0.;
             if (temp[1] == "current") {
               rightBCType[phi_s] = neumann;
               rightBCValue[phi_s] = std::strtod(temp[2].c_str(),NULL);
             } else if (temp[1] == "voltage") {
               rightBCType[phi_s]=dirichlet;
               rightBCValue[phi_s] = std::strtod(temp[2].c_str(),NULL);
             } else {
               Cstr << "Invalid current collector mode. Expected either "
                    << "\"Current\" or \"voltage\". Exiting..." << std::endl;
               StdOut(Cstr.str(),3);
               FunctionExit("InitializeBoundary");
               return(1);
             }
           } else if ( temp[0] == "separator" ) {
             //InitializeSeparator(BCpos);
             rightBCType[phi_s] = neumann;
             rightBCValue[phi_s] = 0.;
             rightBCType[phi_e] = internal;
             rightBCValue[phi_e] = 0.;
             rightBCType[conc_e] = internal;
             rightBCValue[conc_e] = 0;
           } else {
             Cstr << "Invalid boundary type. Expected either "
                  << "\"currentCollector\" or \"separator\". Exiting..." << std::endl;
             StdOut(Cstr.str(),3);
             FunctionExit("InitializeBoundary");
             return(1);
           }
         }
       }
     }
     StdOut(Cstr.str(),3);
     FunctionExit("InitializeBoundary");
     return(0);
   } // Function InitializeBoundary
int InitializeComponent ()
Performs initialization required to calculate component level solutions.
This function does the following:
Transfers the global solution data from Epetra matricies to vector storage this task will be refactored in future code versions
Zero out component solution data structures
Returns
int an error code
Test:
None
Definition at line 275 of file DeviceComponent.cpp.
References SolutionData::function, SolutionData::iEndInternal, SolutionData::iStartInternal, SolutionData::jacobian, SolutionData::numMyElements, DeviceComponent::pSolutionData, SolutionData::solutionData, SolutionData::solutionEpetra, and ICED::HalfCell::solutionVariable_t_MAX.
Referenced by DeviceComponent::InitializeComponentPhysics(), and DeviceComponent::SolveComponent().
{
       std::ostringstream Ostr;
       // transfer solution data from Epetra storage to vector storage
       for (int i=0; i<solutionVariable_t_MAX; ++i) {
         double* vector = (*pSolutionData->solutionEpetra)[i];
         for (int j=0; j<pSolutionData->numMyElements; ++j) {
           //int rowIndex = pSolutionData->myGlobalElements[j];
           (*pSolutionData->solutionData)[j][i] = vector[j];
         }
       }
       // clear vector function and jacobian data structure
       int iStart = pSolutionData->iStartInternal-1;
       int iEnd = pSolutionData->iEndInternal+1;
       for (int i=iStart; i<=iEnd; ++i) {
         for (int j=0; j<solutionVariable_t_MAX; ++j) {
           (*pSolutionData->function)[i][j] = 0;
           for (int ii=iStart; ii<=iEnd; ++ii) {
             for (int jj=0; jj<solutionVariable_t_MAX; ++jj) {
               (*pSolutionData->jacobian)[i][ii][j][jj] = 0;
             }
           }
         }
       }
       StdOut(Ostr.str(),3);
       return(0);
     } // Function InitializeComponent
int InitializeComponentPhysics ()
Performs initialization of physics module data outside of timestepping.
This function intializes physics module that that does not need to be recalculated during the non-linear solver iteration
Returns
int an error code
Test:
None
Definition at line 382 of file DeviceComponent.cpp.
References DeviceComponent::ApplyComponentBC(), DeviceComponent::ApplyInternalBC(), DeviceComponent::componentPhysicsModules, DeviceComponent::FinalizeComponent(), and DeviceComponent::InitializeComponent().
{
       std::ostringstream Ostr;
       InitializeComponent();
       ApplyComponentBC();
 /*
       std::cout << "In device component, before solve, printing Epetra x" << std::endl;
       pSolutionData->solutionEpetra->Print(std::cout);
       std::cout << "In device component, before solve, printing  Epetra f" << std::endl;
       pSolutionData->functionEpetra->Print(std::cout);
       std::cout << "In device component, before solve, printing Vector x" << std::endl;
       std::cout << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->solutionData)[i][2] << " ";
       std::cout << "]" << std::endl;
       std::cout << "In device component, before solve, printing  Vector f" << std::endl;
       std::cout << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->function)[i][2] << " ";
       std::cout << "]" << std::endl;
 */
       // loop over all modules and compute solutions
       for (size_t i=0; i<componentPhysicsModules.size(); ++i) {
         Ostr << "Initializing Physics for module " <<
           componentPhysicsModules[i]->moduleName << std::endl;
         componentPhysicsModules[i]->InitializePhysics();
       }
       ApplyInternalBC();
       FinalizeComponent();
 /*
       std::cout << "In device component, after solve, printing x" << std::endl;
       pSolutionData->solutionEpetra->Print(std::cout);
       std::cout << "In device component, after solve, printing f" << std::endl;
       pSolutionData->functionEpetra->Print(std::cout);
       std::cout << "In device component, after solve, printing Vector x" << std::endl;
       std::cout << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->solutionData)[i][2] << " ";
       std::cout << "]" << std::endl;
       std::cout << "In device component, after solve, printing  Vector f" << std::endl;
       std::cout << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->function)[i][2] << " ";
       std::cout << "]" << std::endl;
 */
       StdOut(Ostr.str(),3);
       return 0;
     } // Function InitializeComponentPhysics
int InitializeComponentSolution ()
Set initial values for component solution data.
Initialize the component solution data based on values read from the input file. This function is only used to initialize the solution at the component level during simulation startup.
Returns
int an error code
Test:
None
Definition at line 251 of file DeviceComponent.cpp.
References ICED::HalfCell::conc_e, ICED::HalfCell::conc_s, SolutionData::iEndInternal, SolutionData::initialElectrolyteLiConcentration, SolutionData::initialElectrolytePotential, SolutionData::initialElectronProductionRate, SolutionData::initialSolidLiConcentration, SolutionData::initialSolidPotential, SolutionData::iStartInternal, ICED::HalfCell::phi_e, ICED::HalfCell::phi_s, DeviceComponent::pSolutionData, SolutionData::solutionData, and ICED::HalfCell::wallFlux.
{
       std::ostringstream Ostr;
       int iStart = pSolutionData->iStartInternal-1;
       int iEnd = pSolutionData->iEndInternal+1;
       for (int i=iStart; i<=iEnd; ++i) {
         (*pSolutionData->solutionData)[i][phi_e] =
           pSolutionData->initialElectrolytePotential;
         (*pSolutionData->solutionData)[i][phi_s] =
           pSolutionData->initialSolidPotential;
         (*pSolutionData->solutionData)[i][conc_e] =
           pSolutionData->initialElectrolyteLiConcentration;
         (*pSolutionData->solutionData)[i][conc_s] =
           pSolutionData->initialSolidLiConcentration;
         (*pSolutionData->solutionData)[i][wallFlux] =
           pSolutionData->initialElectronProductionRate;
       }
       Ostr << std::endl;
       StdOut(Ostr.str(),3);
       return 0;
     } // Function InitializeComponentSolution
int LoadModules (IRAD::Util::Parameters params)
Load the desired modules based on the input file.
Parameters
params Contains input parameters to be used
Returns
void
Test:
Test__DeviceData
Todo:
Add test
Definition at line 121 of file DeviceComponent.cpp.
References DeviceComponent::componentPhysicsModules, DeviceComponent::inputDataModuleString, DeviceComponent::ModulePriorityCompare(), and DeviceComponent::pSolutionData.
{
     FunctionEntry("LoadModule");
     std::ostringstream Ostr, Cstr;
     std::string inputVal;
     std::vector<std::string> temp;
     for(size_t i=0; i<inputDataModuleString.size(); ++i) {
       inputVal = inputDataModuleString[i];
       if(params.IsSet(inputVal)) {
         if (inputVal == "ionMigration") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::ionMigration(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "electronMigration") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::electronMigration(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "ButlerVolmer") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::ButlerVolmer(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "WallFlux") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::WallFlux(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "Diffusion") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::Diffusion(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "OhmsLawElectrolyte") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::OhmsLawElectrolyte(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "OhmsLawSolid") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::OhmsLawSolid(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "Intercalation") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::Intercalation(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "TransferenceNumber") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::TransferenceNumber(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "ConcentrationDiffusion") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::ConcentrationDiffusion(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "ActivityCoefficient") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::ActivityCoefficient(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "IonMigration") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::IonMigration(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else if (inputVal == "testModule") {
           Cstr << "Loading Module " << inputVal << std::endl;
           componentPhysicsModules.push_back(new
             ICED::HalfCell::testModule(pSolutionData, *this));
           componentPhysicsModules.back()->SetPriority(params.GetValue<int>(inputVal));
         } else {
           Cstr << "Invalid physics module, exiting..." << std::endl;
           StdOut(Cstr.str());
           FunctionExit("LoadModule");
           return(1);
         }
       }
     }
     // sort the physics modules by priority
     // moduleSort is a function that takes two modules and compares the priority
     std::sort(componentPhysicsModules.begin(),
               componentPhysicsModules.end(), ModulePriorityCompare);
     StdOut(Cstr.str(),1);
     FunctionExit("LoadModule");
     return(0);
   } // Function LoadModule
bool ModulePriorityCompare (PhysicsModule * first, PhysicsModule * second) static
Compare the priority of two modules.
Parameters
first first module
second second module
Returns
bool true if first module priority is lower than the second module priority, false otherwise
Test:
Test__ModulePriority
Definition at line 217 of file DeviceComponent.cpp.
References PhysicsModule::modulePriority.
Referenced by DeviceComponent::LoadModules().
{
     return(first->modulePriority < second->modulePriority);
   }
int SetupComponentMesh (const int & firstNode)
Setup the component to global mapping for this component.
Parameters
firstNode the first global element in my mapping
Returns
int an error code
Test:
None
Definition at line 222 of file DeviceComponent.cpp.
References SolutionData::BuildSolutionData(), DeviceComponent::componentName, SolutionData::iEndInternal, SolutionData::iStartInternal, DeviceComponent::myDeviceNodes, SolutionData::numGhostNodes, SolutionData::numNodes, and DeviceComponent::pSolutionData.
{
       std::ostringstream Ostr;
       // the user sets the number of nodes for components
       // add on the ghost zones and set the convienience indicies
       pSolutionData->numNodes+=2*pSolutionData->numGhostNodes;
       pSolutionData->iStartInternal = pSolutionData->numGhostNodes+1;
       pSolutionData->iEndInternal = pSolutionData->numNodes-
         pSolutionData->numGhostNodes-2;
       // initialize the data for the components
       pSolutionData->BuildSolutionData();
       // set the first global index for this component
       myDeviceNodes = new global_ordinal_type[pSolutionData->numNodes];
       myDeviceNodes[0]=firstNode;
       // set the remaining global indicies for the component
       Ostr << " In component " << componentName <<  " myDeviceNodes are:" << std::endl;
       Ostr << myDeviceNodes[0] << " ";
       for (int i=1; i<pSolutionData->numNodes; ++i) {
         myDeviceNodes[i]=myDeviceNodes[i-1]+1;
         Ostr << myDeviceNodes[i] << " ";
       }
       Ostr << std::endl;
       StdOut(Ostr.str(),3);
       return(0);
     } // Function SetupComponentMesh
int SolveComponent ()
Populate the component solution matricies.
Use the physics implemented by each module to fill the component level solution matricies. These are combined at the device level to compute a global solution.
Returns
int an error code
Test:
None
Todo:
Break this into ComputeF and ComputeJ to speed up non-linear solutions
Definition at line 439 of file DeviceComponent.cpp.
References DeviceComponent::ApplyComponentBC(), DeviceComponent::ApplyInternalBC(), DeviceComponent::componentPhysicsModules, DeviceComponent::FinalizeComponent(), and DeviceComponent::InitializeComponent().
{
       std::ostringstream Ostr;
       InitializeComponent();
       ApplyComponentBC();
 /*
       Ostr << "In device component " << componentName <<
                    ", before solve, printing Epetra x" << std::endl;
       pSolutionData->solutionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", before solve, printing  Epetra f" << std::endl;
       pSolutionData->functionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", before solve, printing Vector x" << std::endl;
       Ostr << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i) {
         Ostr << "\t \t";
         for (int j=0; j<solutionVariable_t_MAX; ++j) {
           Ostr << (*pSolutionData->solutionData)[i][j] << "\t \t";
         }
         Ostr << std::endl;
       }
       Ostr << "]" << std::endl;
       Ostr << "In device component " << componentName <<
                    ", before solve, printing  Vector f" << std::endl;
       Ostr << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         Ostr << (*pSolutionData->function)[i][2] << " ";
       Ostr << "]" << std::endl;
 */
       // loop over all modules and compute solutions
       for (size_t i=0; i<componentPhysicsModules.size(); ++i) {
         Ostr << "Solving Physics for module " <<
           componentPhysicsModules[i]->moduleName << std::endl;
         componentPhysicsModules[i]->SolvePhysics();
       }
       ApplyInternalBC();
       FinalizeComponent();
 /*
       Ostr << "In device component " << componentName <<
                    ", after solve, printing x" << std::endl;
       pSolutionData->solutionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", after solve, printing f" << std::endl;
       pSolutionData->functionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", after solve, printing Vector x" << std::endl;
       Ostr << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         Ostr << (*pSolutionData->solutionData)[i][2] << " ";
       Ostr << "]" << std::endl;
       Ostr << "In device component " << componentName <<
                    ", after solve, printing  Vector f" << std::endl;
       Ostr << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         Ostr << (*pSolutionData->function)[i][2] << " ";
       Ostr << "]" << std::endl;
 */
       StdOut(Ostr.str(),3);
       return 0;
     } // Function SolveComponent
Member Data Documentation
std::string componentInputFile
Definition at line 416 of file DeviceComponent.hpp.
Referenced by DeviceComponent::DeviceComponent().
std::string componentName
Definition at line 415 of file DeviceComponent.hpp.
Referenced by DeviceComponent::DeviceComponent(), DeviceComponent::InitializeBoundary(), and DeviceComponent::SetupComponentMesh().
std::vector<PhysicsModule*> componentPhysicsModules
Definition at line 413 of file DeviceComponent.hpp.
Referenced by DeviceComponent::ApplyComponentBC(), DeviceComponent::InitializeComponentPhysics(), DeviceComponent::LoadModules(), and DeviceComponent::SolveComponent().
std::vector<std::string> inputDataBoundaryString
Definition at line 411 of file DeviceComponent.hpp.
Referenced by DeviceComponent::Initialize(), and DeviceComponent::InitializeBoundary().
std::vector<double*> inputDataDouble
Definition at line 408 of file DeviceComponent.hpp.
Referenced by DeviceComponent::Initialize().
std::vector<std::string> inputDataDoubleString
Definition at line 407 of file DeviceComponent.hpp.
Referenced by DeviceComponent::Initialize().
std::vector<int*> inputDataInt
Definition at line 406 of file DeviceComponent.hpp.
Referenced by DeviceComponent::Initialize().
std::vector<std::string> inputDataIntString
storage for input values and input value descriptors
These vectors hold descriptors to be read out of an input file and pointers to their associated variables. Both are initialized by the default constructor.
Definition at line 405 of file DeviceComponent.hpp.
Referenced by DeviceComponent::Initialize().
std::vector<int> inputDataModulePriority
Definition at line 410 of file DeviceComponent.hpp.
std::vector<std::string> inputDataModuleString
Definition at line 409 of file DeviceComponent.hpp.
Referenced by DeviceComponent::Initialize(), and DeviceComponent::LoadModules().
std::vector<int> leftBCType
boundary condition data.
We have a BC type and value for each solution variable we use the solVar enumeration to access them
Definition at line 426 of file DeviceComponent.hpp.
Referenced by DeviceComponent::ApplyComponentBC(), DeviceComponent::ApplyInternalBC(), DeviceComponent::Initialize(), and DeviceComponent::InitializeBoundary().
std::vector<double> leftBCValue
Definition at line 428 of file DeviceComponent.hpp.
Referenced by DeviceComponent::ApplyComponentBC(), DeviceComponent::Initialize(), and DeviceComponent::InitializeBoundary().
global_ordinal_type* myDeviceNodes
mapping to device vector space
Definition at line 432 of file DeviceComponent.hpp.
Referenced by DeviceComponent::SetupComponentMesh().
SolutionData* pSolutionData
Definition at line 414 of file DeviceComponent.hpp.
Referenced by DeviceComponent::ApplyInternalBC(), DeviceComponent::DeviceComponent(), DeviceComponent::FinalizeComponent(), DeviceComponent::Initialize(), DeviceComponent::InitializeComponent(), DeviceComponent::InitializeComponentSolution(), DeviceComponent::LoadModules(), and DeviceComponent::SetupComponentMesh().
std::vector<int> rightBCType
Definition at line 427 of file DeviceComponent.hpp.
Referenced by DeviceComponent::ApplyComponentBC(), DeviceComponent::ApplyInternalBC(), DeviceComponent::Initialize(), and DeviceComponent::InitializeBoundary().
std::vector<double> rightBCValue
Definition at line 429 of file DeviceComponent.hpp.
Referenced by DeviceComponent::ApplyComponentBC(), DeviceComponent::Initialize(), and DeviceComponent::InitializeBoundary().
The documentation for this class was generated from the following files:
DeviceComponent.hpp
DeviceComponent.cpp