ICED_Physics: ICED::TestingObject::Test__IonMigration
void Test__IonMigration (ResultsType & result) inline
Test for ICED::IonMigration module.
This function implements a test of the IonMigration module.
This fucntion initializes the input data values for the simulation, and then calls another function that initializes the test fixtrue solution data object. It then calls the Ion Migration class: SolvePhysics. Jacobian vector with the correct values
Definition at line 5378 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, TestingObject< ResultsType >::pDeviceData, and ICED::HalfCell::phi_e.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__IonMigration" << std::endl;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int error;
       int numNodes=6;
       std::vector<double> transCoeff(3);
       std::vector<double> activityCoeff(5);
       std::vector<double> cSoln(numNodes+2); //c_e
       std::vector<double> phiSoln(numNodes+2); //phi_e
       std::vector<double> phimExact(numNodes+2); // exact solution of IonMigration (phim)
       std::vector<double> x(numNodes+2);
       std::vector<double> cCoeffs(3); //c_e coeffs
       std::vector<double> phiCoeffs(3); //phi_e coeffs
       std::vector<double> *trans;
       std::vector<double> *transDer;
       //std::vector<double> *transDerDer;
       std::vector<double> *ac; //activity coefficient
       std::vector<double> *acDer; //derivative
       std::vector<double> *acDerDer;
       std::vector<double> kappaD(numNodes+2);
       std::vector<double> kappaDDer(numNodes+2);
       double kappa;
       //double h = 1.0;
       double electrolyteConductivity = 5, chargeNumber = -1, electrolyteVolumeFraction = .4;
       double gasConstant = 8.3145, temperature = 300;
       double faradayConstant = 9.64854, stoichParameter = 2.5;
       double numberOfElectrons = 2, numberOfIons = 6.0221413;
       std::stringstream ss;
       transCoeff[0] = 1.0;
       transCoeff[1] = 2.3;
       transCoeff[2] = 3.4;
       activityCoeff[0] = 1.2;
       activityCoeff[1] = 2.3;
       activityCoeff[2] = 3.4;
       activityCoeff[3] = 4.5;
       activityCoeff[4] = 5.6;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1",
              "firstComponent component1.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("numNodes", "6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("chargeNumber","-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("numberOfIons","6.0221413"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("faradayConstant","9.64854"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("gasConstant","8.3145"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("temperature","300"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("numberOfElectrons","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("stoichParameter","2.5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("electrolyteConductivity","5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("electrolyteVolumeFraction",".4"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("xMin","-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("xMax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("bruggemanCoefficient","1.5"));
       ss.clear();
       ss.str("");
       ss << transCoeff[0] << " " << transCoeff[1] << " " << transCoeff[2];
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("transferenceCoefficients", ss.str()));
       ss.clear();
       ss.str("");
       ss << activityCoeff[0] << " " << activityCoeff[1] << " " << activityCoeff[2]
               << " " << activityCoeff[3]<< " " << activityCoeff[4];
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("activityCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("TransferenceNumber","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("ActivityCoefficient","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("IonMigration","2"));
       // build the device
       //error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       //if (error != 0)
       //  works=false;
       bool builds = false;
       // build the device
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("IonMigration:Builds",builds);
       int iStartIn = pDeviceData->deviceComponents[0]->
            pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->
            pSolutionData->iEndInternal;
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->xCoords;
       // set conc_e values to 4x^2 + 4x +1
       cCoeffs[0] = 4;
       cCoeffs[1] = 4;
       cCoeffs[2] = 1;
       GenerateParabolicFunction(cSoln, x, cCoeffs, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output (c_e) "
                   << cSoln[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->
             pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]=cSoln[i];
       }
       // set phi_e values to x^2 + 2x +3
       phiCoeffs[0] = 1;
       phiCoeffs[1] = 2;
       phiCoeffs[2] = 3;
       GenerateParabolicFunction(phiSoln, x, phiCoeffs, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << "Parabolic Function Output (phi_e) " << phiSoln[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::phi_e]=phiSoln[i];
       }
       //Call TransferenceNumber module SolvePhysics function
       //(IonMigration depends on it)
      pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       //Call ActivityCoefficient module SolvePhysics function
       //(kD depends on it)
      pDeviceData->deviceComponents[0]->componentPhysicsModules[1]->
          SolvePhysics();
       //Call IonMigration SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[2]->
          SolvePhysics();
       //Check IonMigration discretized function
       trans = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumber;
       transDer = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDer;
       //transDerDer = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              //->pSolutionData->transferenceNumberDerDer;
       ac = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficient;
       acDer = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDer;
       acDerDer = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDer;
       kappa = electrolyteConductivity *
               pow(electrolyteVolumeFraction,
               pDeviceData->deviceComponents[0]->pSolutionData->bruggemanCoefficient);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         kappaD[i] = (kappa*gasConstant*temperature/faradayConstant)
                   * (1+(cSoln[i]*(*acDer)[i]/(*ac)[i]))
                   * ( (stoichParameter/(numberOfElectrons*numberOfIons))
                   + ((*trans)[i]/(chargeNumber*numberOfIons)) );
         kappaDDer[i] = (kappa*gasConstant*temperature/(numberOfIons*faradayConstant))
                      * ( (((*acDer)[i]/(*ac)[i])*(1-cSoln[i]*(*acDer)[i]/(*ac)[i])
                      + (cSoln[i]*(*acDerDer)[i]/(*ac)[i]))
                      * (stoichParameter/numberOfElectrons+ (*trans)[i]/chargeNumber)
                      + (*transDer)[i]/chargeNumber * (1+cSoln[i]*(*acDer)[i]/(*ac)[i]) );
       }
       //Check error of Ion Migration function
       double testError = 0;
       double h = 2./(numNodes-1);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         phimExact[i] = ((*transDer)[i]/(4*chargeNumber*numberOfIons*faradayConstant*h*h))
                      / electrolyteVolumeFraction
                      * ( kappa*(phiSoln[i+1]-phiSoln[i-1])*(cSoln[i+1]-cSoln[i-1])
                      + (kappaD[i]/cSoln[i])*(cSoln[i+1]-cSoln[i-1])*(cSoln[i+1]-cSoln[i-1]) );
         std::cout << "Test solution: " << phimExact[i] << std::endl;
         std::cout << "Node solution: " << std::setprecision(15) <<
              (*pDeviceData->deviceComponents[0]->
              pSolutionData->function)[i][ICED::HalfCell::conc_e] << std::endl;
         testError += (fabs(phimExact[i] - (*pDeviceData->deviceComponents[0]->
                       componentPhysicsModules[0]->pSolutionData->function)[i][ICED::HalfCell::conc_e]))
                     * (fabs(phimExact[i] - (*pDeviceData->deviceComponents[0]->
                       componentPhysicsModules[0]->pSolutionData->function)[i][ICED::HalfCell::conc_e]));
       }
       testError = sqrt(testError);
       if(testError > 1.0e-8){
         works = false;
         std::cout << "FAILS in Ion Migration Function" << std::endl;
       }
 /*
       //Check the Jacobians
       double valueDown, value, valueUp;
       //Print out the Jacobian for conc_e
       std::cout << std::endl << "Jacobian conc_e (tridiagonal):" << std::endl;
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i-1][0]
            [ICED::HalfCell::conc_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][0]
            [ICED::HalfCell::conc_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i+1][0]
            [ICED::HalfCell::conc_e] << std::endl;
       }
       //Check values of the jacobian for conc_e
       //check n-1
       valueDown = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn][iStartIn-1][0][ICED::HalfCell::conc_e];
       //check n
       value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][0][ICED::HalfCell::conc_e];
       //check n+1
       valueUp = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+2][iStartIn+3][0][ICED::HalfCell::conc_e];
       //if(fabs(valueDown - 299.549730255735) > 1.0e-8){
       if(fabs(valueDown - 1872.18581409834) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 1" << std::endl;
       }
       //if(fabs(value + 47.5399248675) > 1.0e-8){
       if(fabs(value + 297.124530421875) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 2" << std::endl;
       }
       //if(fabs(valueUp - 1784.18899414192) > 1.0e-8){
       if(fabs(valueUp - 11151.181213387) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 3" << std::endl;
       }
       //Print out the Jacobian for phi_e
       std::cout << std::endl << "Jacobian phi_e (tridiagonal):" << std::endl;
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i-1][0]
            [ICED::HalfCell::phi_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][0]
            [ICED::HalfCell::phi_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i+1][0]
            [ICED::HalfCell::phi_e] << std::endl;
       }
       //Check values of the jacobian for phi_e
       //check n-1
       valueDown = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn][iStartIn-1][0][ICED::HalfCell::phi_e];
       //check n
       value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][0][ICED::HalfCell::phi_e];
       //check n+1
       valueUp = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+2][iStartIn+3][0][ICED::HalfCell::phi_e];
       //if(fabs(valueDown + 0.0601992789817686) > 1.0e-8){
       if(fabs(valueDown + 0.376245493636054) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_e Jacobian 1" << std::endl;
       }
       if(fabs(value - 0) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_e Jacobian 2" << std::endl;
       }
       //if(fabs(valueUp + 1.10129269196059) > 1.0e-8){
       if(fabs(valueUp + 6.88307932475369) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_e Jacobian 3" << std::endl;
       }
       //Print out the Jacobian for phi_e
       std::cout << std::endl << "Jacobian phi_e (tridiagonal):" << std::endl;
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i-1][0]
            [ICED::HalfCell::phi_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModNules[0]
            ->pSolutionData->jacobian)[i][i][0]
            [ICED::HalfCell::phi_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i+1][0]
            [ICED::HalfCell::phi_e] << std::endl;
       }
 */
       result.UpdateResult("IonMigration:Works",works);
       delete pDeviceData;
     }