ICED_Physics: Intercalation Class Reference
Intercalation Class Reference
The Intercalation function is a module that solves the time-dependent, second-order diffusion equation for ion migration in the solid.
Detailed Description
The Intercalation function is a module that solves the time-dependent, second-order diffusion equation for ion migration in the solid.
The Intercalation function is a module that solves the time-dependent, second-order diffusion equation for ion migration in the solid.
The active material is assumed to be made up of spherical particles of radius with (solid state) diffusion being the mechanism for transport. We take the direction normal to the surface of the particles to be the direction. Here represents the concentration of the ions in the solid particle phase. If , the solid diffusion coefficient, is (approximately) constant, then the concentration in the particle resulting from a time-varying rate of reaction at the surface can be obtained by superposing the concentration changes resulting from simple step changes in concentration at the surface.
The Intercalation module couples with the governing equations through the WallFlux . The function evaluation then becomes
where is the concentration of lithium ions in the solid and is the series expansion constant, both at spatial point and temporal time Note that has been dropped from the WallFlux term to avoid confusion.
comes from the input file, and is related to through the below equation.
We use a Laplace transform to obtain series expansions for . A substitution occurs to change from dimensioned time to dimensionless time . is obtained from CalcATK .
Definition at line 985 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
Intercalation ()
Default constructor.
Intercalation (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~Intercalation ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Physics solution.
void InitializePhysics ()
Physics solution initialization.
double CalcATK (const double &tau)
A Laplace transform is used to obtain series expansions for .
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Public Attributes
std::list< std::vector< double > > prevConcS
conc_s at previous time steps.
std::list< double > prevTime
the list of times
std::list< double > aTK
a list of a (surface area of the pore walls per unit volume) at every time step.
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
Intercalation () inline
Default constructor.
Definition at line 992 of file PhysicsModule.hpp.
References OhmsLawElectrolyte::Initialize().
 {Initialize();};
Intercalation (SolutionData * solutionData, GlobalType & globin) inline
Constructor for solution data and global object.
Definition at line 997 of file PhysicsModule.hpp.
References Intercalation::Initialize().
                                                                   :
          PhysicsModule(solutionData, globin) {
       Intercalation::Initialize();
     };
~Intercalation () inline
Default destructor.
Definition at line 1005 of file PhysicsModule.hpp.
 {};
Member Function Documentation
double CalcATK (const double & tau)
A Laplace transform is used to obtain series expansions for .
The CalcATK function obtains an expression for for the Intercalation module. is rewritten in a form that depends on . We use a Laplace transform to obtain series expansions for . A substitution occurs to change from dimensioned time to dimensionless time . There are two limits for , one valid for short times and one for long times.
At short times:
At long times:
Here is the dimensionless time defined as:
states that evaluating the first three terms of the short-time solution or the first five terms in the long-time solution provides sufficient accuracy.
Todo:
We should test this assumption (should be easy with a unit test). The long-time solution is used when > 0.06. This solution assumes spherical particles.
Definition at line 21 of file Intercalation.cpp.
References PI.
Referenced by Intercalation::InitializePhysics(), and Intercalation::SolvePhysics().
{
     double value1=0.;
     double atk=0;
     // different formulas for aTK depending on the value
     // of time (see notes document)
     //
     // only the first 5 terms of the series expansion are computed
     // increased accurary could be obtained by calculating more...
     //
     if(tau > 0 && tau <= 0.06) {
         atk = exp(-1.0/tau) - sqrt(PI/tau)*erfc(1.0/sqrt(tau));
         atk += exp(-4.0/tau) - 2.0*sqrt(PI/tau)*erfc(2.0/sqrt(tau));
         atk += exp(-9.0/tau) - 3.0*sqrt(PI/tau)*erfc(3.0/sqrt(tau));
         atk = -tau + 2.0*sqrt(tau/PI)*(1.0 + 2.0*value1);
     } else if (tau > 0.06) {
       //Ostr << "long tau" << std::endl;
       atk = 1.0 - exp(-PI*PI*tau);
       atk += 1.0/4.0*(1.0 - exp(-4.0*PI*PI*tau));
       atk += 1.0/9.0*(1.0 - exp(-9.0*PI*PI*tau));
       atk += 1.0/16.0*(1.0 - exp(-16.0*PI*PI*tau));
       atk += 1.0/25.0*(1.0 - exp(-25.0*PI*PI*tau));
       atk *= 2.0/(PI*PI);
     }
     return atk;
   }
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 1014 of file PhysicsModule.hpp.
References ICED::HalfCell::conc_s, PhysicsModule::idealParameters, PhysicsModule::moduleName, and PhysicsModule::variableIndex.
Referenced by Intercalation::Intercalation().
                       {
       moduleName="Intercalation";
       SetName(moduleName);
       variableIndex=conc_s;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","0"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("poreRadius","4"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("solidDiffusionCoefficient","1"));
     };
void InitializePhysics () virtual
Physics solution initialization.
Sets things that do not change during the timestep. For intercalation, this involves putting the initial concentration and functions onto the end of the list data structures.
Reimplemented from PhysicsModule.
Definition at line 48 of file Intercalation.cpp.
References Intercalation::aTK, Intercalation::CalcATK(), ICED::HalfCell::conc_s, SolutionData::iStartInternal, SolutionData::numNodes, SolutionData::poreRadius, Intercalation::prevConcS, Intercalation::prevTime, PhysicsModule::pSolutionData, SolutionData::solidDiffusionCoefficient, SolutionData::solutionData, and SolutionData::time.
{
     const int numNodes = pSolutionData->numNodes;
     const int iStartIn = pSolutionData->iStartInternal-1;
     const int iEndIn = pSolutionData-> iEndInternal+1;
     const double solidDiff = pSolutionData->solidDiffusionCoefficient;
     const double poreRadius = pSolutionData->poreRadius;
     const double time = pSolutionData->time;
     std::vector<double> conc(numNodes);
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     //set local conc vector to conc_s from solution data
     //Ostr << "conc: " << std::endl;
     for(int i= iStartIn; i <= iEndIn; ++i){
       conc[i] = (*pSolution)[i][conc_s];
       //Ostr << conc[i] << std::endl;
     }
     prevConcS.push_back(conc);
     prevTime.push_back(time);
     // calculate current tau, current aTK;
     double tau = time*solidDiff/(poreRadius*poreRadius);
     aTK.push_back(CalcATK(tau));
   }
void SolvePhysics () virtual
Physics solution.
Fills in the Function values for intercalation at every node in the mesh. It also populates the Jacobian matrices with the calculated values.
Todo:
This is in need of a refactor. Once we are able to do problems of any size, we need to check the performance of of our list data structures. Surely there is a better way to implement this function.
Implements PhysicsModule.
Definition at line 76 of file Intercalation.cpp.
References Intercalation::aTK, Intercalation::CalcATK(), ICED::HalfCell::conc_s, SolutionData::function, SolutionData::iStartInternal, SolutionData::numNodes, SolutionData::poreRadius, Intercalation::prevConcS, Intercalation::prevTime, PhysicsModule::pSolutionData, SolutionData::solidDiffusionCoefficient, SolutionData::solutionData, SolutionData::time, and ICED::HalfCell::wallFlux.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     Ostr << "**************************************" << std::endl;
     Ostr << "**************************************" << std::endl;
     Ostr << "**************************************" << std::endl;
     Ostr << "Hello from SolvePhysics" << std::endl;
     //get all the component wide variables needed
     const int iStartIn = pSolutionData->iStartInternal-1;
     const int iEndIn = pSolutionData-> iEndInternal+1;
     const int numNodes = pSolutionData->numNodes;
     //const int timeStep = pSolutionData->timeStep;
     const double time = pSolutionData->time;
     //const double deltaTime = pSolutionData->deltaTime;
     const double solidDiff = pSolutionData->solidDiffusionCoefficient;
     const double poreRadius = pSolutionData->poreRadius;
     double value1, value2, value3, tau;
     double A1;
     std::vector<double> fkn(numNodes); // f_{kn}
     Ostr << "numNodes = " << numNodes << std::endl;
     Ostr << "iStartIn = " << iStartIn << std::endl;
     Ostr << "iEndIn = " << iEndIn << std::endl;
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     // declare some iterators
     std::list<double>::iterator aTKIt;
     std::list<double>::iterator aTKItP1;
     std::list< std::vector<double> >::iterator prevConcSIt;
     std::list< std::vector<double> >::iterator prevConcSItP1;
     std::list< std::vector<double> >::iterator prevConcSItEnd;
     std::list<double>::iterator prevTimeIt;
     std::list<double>::iterator prevTimeItP1;
     std::vector<double> conc(numNodes);
     //set local conc vector to conc_s from solution data at the current time
     for(int i= iStartIn; i <= iEndIn; ++i){
       conc[i] = (*pSolution)[i][conc_s];
     }
     //Loop over all the nodes and initialize f_kn to wallFlux
     for(int i=iStartIn; i <= iEndIn; ++i){
       fkn[i] = (*pSolution)[i][wallFlux];
     }
     // contribution for current time step
     // requires current value of concentration
     // last known concentration
     prevConcSIt = prevConcS.end();
     --prevConcSIt;
     // last known time
     prevTimeIt = prevTime.end();
     --prevTimeIt;
     // first and second values of a(tau)
     aTKIt = aTK.begin();
     aTKItP1 = aTKIt;
     ++aTKItP1;
     double dt;
     // check for first time
     // if this is the first time only the initial conditions exist
     // in the prevConcS and aTK arrays, which means that we have to
     // do something special
     if (prevConcSIt == prevConcS.begin()) {
       dt = time - *prevTimeIt;
       tau = pSolutionData->time*solidDiff/(poreRadius*poreRadius);
       double atk = CalcATK(tau);
       //Loop over all the nodes
       for(int i=iStartIn; i <= iEndIn; ++i){
         fkn[i] += (conc[i] - (*prevConcSIt)[i])
                   //*(atk - *aTKIt)*poreRadius/(solidDiff*dt);
                   *(atk - *aTKIt)*poreRadius/(dt);
       }
     } else {
       double dt = time - *prevTimeIt;
       //Loop over all the nodes
       for(int i=iStartIn; i <= iEndIn; ++i){
         fkn[i] += (conc[i] - (*prevConcSIt)[i])
                //*(*aTKItP1 - *aTKIt)*poreRadius/(solidDiff*dt);
                *(*aTKItP1 - *aTKIt)*poreRadius/(dt);
       }
       // contribution for current time step
       // requires current value of a(tau)
       // first two known concentrations
       prevConcSIt = prevConcS.begin();
       prevConcSItP1 = prevConcSIt;
       ++prevConcSItP1;
       // first two times
       prevTimeIt = prevTime.begin();
       prevTimeItP1 = prevTimeIt;
       ++prevTimeItP1;
       // last know value for a(tau)
       aTKIt = aTK.end();
       --aTKIt;
       tau = pSolutionData->time*solidDiff/(poreRadius*poreRadius);
       double atk = CalcATK(tau);
       dt = *prevTimeItP1 - *prevTimeIt;
       //Loop over all the nodes
       for(int i=iStartIn; i <= iEndIn; ++i){
         fkn[i] += ((*prevConcSItP1)[i] - (*prevConcSIt)[i])
                //*(atk - *aTKIt)*poreRadius/(solidDiff*dt);
                *(atk - *aTKIt)*poreRadius/(dt);
       }
       // Loop over all the previous time steps
       // this does not include the very first and most recent timesteps
       // as those calculations require access to values of concentration
       // and a(tau) that are not in our list
       // start on the second item and save an iterator to the next component
       //
       // due to our use of multiple lists, I think this would be more clear
       // if we used a random-access data structure. I don't think we are
       // gaining any performance benefits (Mike Anderson)
       //
       aTKIt = aTK.end();
       --aTKIt;
       aTKItP1 = aTKIt;
       --aTKIt;
       prevTimeIt = prevTime.begin();
       ++prevTimeIt;
       prevTimeItP1 = prevTimeIt;
       ++prevTimeItP1;
       prevConcSIt = prevConcS.begin();
       ++prevConcSIt;
       prevConcSItEnd = prevConcS.end();
       --prevConcSItEnd;
       for(prevConcSIt; prevConcSIt != prevConcSItEnd; prevConcSIt++){
         prevConcSItP1 = prevConcSIt;
         ++prevConcSItP1;
         //Ostr << "time = " << time << std::endl;
         //Ostr << "aTK = " << (*aTKIt) << std::endl;
         //Ostr << "aTK+1 = " << (*aTKItP1) << std::endl;
         //Loop over all the nodes
         dt = *prevTimeItP1 - *prevTimeIt;
         double An = *aTKItP1 - *aTKIt;
         for(int i=iStartIn; i <= iEndIn; ++i) {
   /*
             Ostr << "******************" << std::endl;
             Ostr << "f_kn = " << (*pSolutionData->function)[i][4] << std::endl;
             Ostr << "node = " << i << std::endl;
             Ostr << "conc_k = " << (*prevConcSItP1)[i] << std::endl;
             Ostr << "conc_k-1 = " << (*prevConcSIt)[i] << std::endl;
             Ostr << "j = " << (*pSolution)[i][wallFlux] << std::endl;
             Ostr << "poreRadius = " << poreRadius << std::endl;
             Ostr << "solidDiff = " << solidDiff << std::endl;
             Ostr << "delta_c = " << ((*prevConcSItP1)[i]
                   - (*prevConcSIt)[i]) << std::endl;
             Ostr << "A = " << (*aTKItP1 - *aTKIt)*poreRadius/solidDiff << std::endl;
   */
           fkn[i] += ((*prevConcSItP1)[i]
                 //- (*prevConcSIt)[i])*An*poreRadius/(solidDiff*dt);
                 - (*prevConcSIt)[i])*An*poreRadius/(dt);
         }
         //first = false;
         ++prevTimeIt;
         ++prevTimeItP1;
         --aTKIt;
         --aTKItP1;
       }
     }
 /*
     //Print out f_kn to check
     Ostr << "f_kn:" << std::endl;
     for(int i=iStartIn; i <= iEndIn; ++i){
       Ostr << (*pSolutionData->function)[i][4] << std::endl;
     }
 */
     for(int i=iStartIn; i <= iEndIn; ++i){
       (*pSolutionData->function)[i][conc_s] = fkn[i];
       Ostr << "computed Intercalation Function = " <<
         fkn[i] << std::endl;
     }
 /*
   commented out Jacobian stuff for now
   fix this later
     //calculate A1 to use in the Jacobian
     aTKIt = aTK.begin();
     value1 = *aTKIt;
     //Ostr << "aTK0 = " << value1 << std::endl;
     aTKIt++;
     value2 = *aTKIt;
     //Ostr << "aTK1 = " << value2 << std::endl;
     A1 = poreRadius/solidDiff*(value2 - value1);
     //Ostr << "A1 = " << A1 << std::endl;
     //Fill in the Jacobian values
     for(int i=iStartIn; i <= iEndIn; ++i){
       (*pSolutionData->jacobian)[i][i][4][conc_s] = A1*solidDiff/deltaTime;
       (*pSolutionData->jacobian)[i][i][4][wallFlux] = 1.0;
     }
 */
     Ostr << std::endl;
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
Member Data Documentation
std::list<double> aTK
a list of a (surface area of the pore walls per unit volume) at every time step.
Equation for aTK:
Definition at line 1083 of file PhysicsModule.hpp.
Referenced by Intercalation::InitializePhysics(), and Intercalation::SolvePhysics().
std::list< std::vector<double> > prevConcS
conc_s at previous time steps.
Definition at line 1073 of file PhysicsModule.hpp.
Referenced by Intercalation::InitializePhysics(), and Intercalation::SolvePhysics().
std::list<double> prevTime
the list of times
Definition at line 1077 of file PhysicsModule.hpp.
Referenced by Intercalation::InitializePhysics(), and Intercalation::SolvePhysics().
The documentation for this class was generated from the following files:
PhysicsModule.hpp
Intercalation.cpp