ICED_Physics: ICED::TestingObject::Test__ButlerVolmer
void Test__ButlerVolmer (ResultsType & result) inline
Test for ICED::ButlerVolmer.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of a Butler-volmer module.
This function calls another function that loads test data into the solution data object. It then creates an object of the Butler volmer class, and calls SolvePhysics. Finally it verifies that SolvePhysics populates the function and Jacobian vector with the correct values
Definition at line 3198 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_s, DeviceData::deviceComponents, TestingObject< ResultsType >::global, TestingObject< ResultsType >::pDeviceData, ICED::HalfCell::phi_e, ICED::HalfCell::phi_s, and ICED::HalfCell::wallFlux.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__ButlerVolmer" << std::endl;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int error;
       int numNodes=6, numVars=5;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1",
              "firstComponent component1.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","300"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("symmetryParameter","0.75"));
       // polymerMaxConcentration is irrelevant now that "maxConc" is calculated in BV module using
       // coulombicCapacity and solidDensity parameters
       // componentParameters[0].push_back(
       //  IRAD::Primitive::KeyValuePairObj<std::string,std::string>("polymerMaxConcentration","1000.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("cathodicRateConstant","1.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("anodicRateConstant","1.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("openCircuitPotential","10.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("faradayConstant","10.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("gasConstant","5.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("coulombicCapacity","5.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("solidDensity","5.0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("openCircuitPotentialType","100"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ButlerVolmer","1"));
       //error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       //if (error != 0)
       //  works=false;
       bool builds = false;
       // Build the device
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("ButlerVolmer:Builds",builds);
       // Set up nodes
       int iStartIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       // Set up the values to be passed to the BV module. For every i...
       // y(x) = x^2 - 2x + 3
       // Phi_e  is the value of y(x) at j = 0
       // Phi_s  is the value of y(x) at j = 1
       // Conc_s is the value at y(x) at j = 3
       // j_n    is the value at y(x) at j = 4
       //
       //        j =   0   1   2   3   4
       //        { {   3   2   3   6  11 } i = 1
       // y(x) =   {  18  27  38  51  66 }     2 (iStartIn)
       //          {  83 102 123 146 171 }     3
       //          { 198 227 258 291 326 }     4
       //          { 363 402 443 486 531 }     5 (iEndIn)
       //          { 578 627 678 731 786 } }   6
       //
       for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=0; j < numVars; j++){
           double x = double((i-1)*5 + j);
           (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData
                ->solutionData)[i][j] = x*x - 2.0*x + 3.0;
           std::cout << x*x - 2.0*x + 3.0 << " ";
         }
         std::cout << std::endl;
       }
       for(int i=0; i < numNodes+2; i++){
         for(int j=0; j < numVars; j++){
            //double x = double(i*5 + j);
             std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                  ->pSolutionData->solutionData)[i][j] << " ";
         }
         std::cout << std::endl;
       }
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->SolvePhysics();
       //Create "exact" solution with which to compare the module-calculated value
       //Right now the test assumes a constant open circuit potential as set above
       //It does NOT allow for variable material type (i.e., openCircuitPotentialVector[i])
       double R = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->gasConstant;
       double T = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->temperature;
       double alc = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->symmetryParameter; //beta
       double ala = 1.0 - alc;
       double ka = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->anodicRateConstant;
       double kc = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->cathodicRateConstant;
       double f = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->faradayConstant;
       double cCap = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->coulombicCapacity;
       double solden = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->solidDensity;
       double OPC = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->openCircuitPotential;
       double cmax = 3600.0*cCap*solden/f;
       for(int i=iStartIn-1; i <= iEndIn+1; i++){
         double exactBVsol = 0;
         double phi_e  = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->solutionData)[i][0];
         double phi_s  = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->solutionData)[i][1];
         double conc_s = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->solutionData)[i][3];
         double j_n    = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->solutionData)[i][4];
         double eta  = phi_s - phi_e - OPC;
         double expA =  (ala*f*eta)/(R*T);
         double expC = -(alc*f*eta)/(R*T);
         double i0 = pow(ka,alc)*pow(kc,ala)*pow((cmax-conc_s),alc)*pow(conc_s,ala);
         double in = i0*(exp(expA)-exp(expC));
         std::cout << "i0  = " << i0 << std::endl;
         std::cout << "in  = " << in << std::endl;
         std::cout << "j_n = " << j_n << std::endl;
         exactBVsol += (in - j_n);
         //Value calculated by the Bulter-Volmer physics module
         //Double check module for missing factors of Faraday and/or area.
         //If so, modify test.
         double moduleBVsol;
         moduleBVsol = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                  ->pSolutionData->function)[i][ICED::HalfCell::wallFlux];
         std::cout << "Test solution = " << exactBVsol << std::endl;
         std::cout << "Comp solution = " << moduleBVsol << std::endl;
         if(fabs(exactBVsol - moduleBVsol) > 1.0e-8){
          works = false;
          std::cout << "FAILS in Bulter-Volmer function" << std::endl;
         }
       }
 /*
       //Check that the off-diagonal values of the jacobians are zero
       //and check one of the values of the diagonal
       //phi_e
       for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=iStartIn-1; j <= iEndIn+1; j++){
           value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                ->pSolutionData->jacobian)[i][j][1][0];
           std::cout << "value = " << value << std::endl;
           if(i != j){
             if(fabs(value) > 1.0e-15){
               works = false;
               std::cout << "Failing in phi_e jacobian check" << std::endl;
             }
           }
           else if(i == 0){
             if(fabs(value + 16.156631646 > 1.0e-9)){
               works = false;
               std::cout << "Failing in phi_e jacobian check" << std::endl;
             }
           }
         }
       }
       //skipping phi_s since it is simply the negative of phi_e
       //c_e
       for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=iStartIn-1; j <= iEndIn+1; j++){
           value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                ->pSolutionData->jacobian)[i][j][1][2];
           std::cout << "value = " << value << std::endl;
           if(i != j){
             if(fabs(value) > 1.0e-15){
               works = false;
               std::cout << "Failing in c_e jacobian check" << std::endl;
             }
           }
           else if(i == 0){
             if(fabs(value + 14.405987182 > 1.0e-9)){
               works = false;
               std::cout << "Failing in c_e jacobian check" << std::endl;
             }
           }
         }
       }
       //c_s should all be zero
       for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=iStartIn-1; j <= iEndIn+1; j++){
           value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                ->pSolutionData->jacobian)[i][j][1][3];
           std::cout << "value = " << value << std::endl;
           if(fabs(value) > 1.0e-15){
             works = false;
             std::cout << "Failing in c_s jacobian check" << std::endl;
           }
         }
       }
       //s_dot
       for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=iStartIn-1; j <= iEndIn+1; j++){
           value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                ->pSolutionData->jacobian)[i][j][1][4];
           std::cout << "value = " << value << std::endl;
           if(i != j){
             if(fabs(value) > 1.0e-15){
               works = false;
               std::cout << "Failing in s_dot jacobian check" << std::endl;
             }
           }
           else if(i == 0){
             if(fabs(value + 1 > 1.0e-4)){
               works = false;
               std::cout << "Failing in s_dot jacobian check" << std::endl;
             }
           }
         }
       }
 */
       result.UpdateResult("ButlerVolmer:Works",works);
       delete pDeviceData;
     }