ICED_Physics: SerialProgram Class Reference
SerialProgram Class Reference
Implementation of the batterySim program.
Detailed Description
Implementation of the batterySim program.
This object encapsulates the serial program. It inherits from the IRAD::Global::Program type.
The program simulates a half-cell battery. The command line usage goes:
       batterySim Usage:
       batterySim [-h] [-v [arg] -o <filename> ] <input>
       -h,--help
          Prints this long version of help.
              -v,--verbosity [arg]
       -o,--output <filename>
          Specifies the name of the output file.
              <input>
          Specifies the input <filename> (required)
Definition at line 138 of file HalfCell.hpp.
#include <Physics/include/HalfCell.hpp>
Public Member Functions
SerialProgram ()
Default constructor.
SerialProgram (int nargs, char **args)
Constructor designed to take the commandline args.
virtual int Initialize ()
Initializes native data structures from commandline args.
int VerbLevel () const
Returns verbosity level.
virtual ~SerialProgram ()
Destructor.
virtual int Run ()
This function implements the main function executed by the program.
Protected Attributes
std::string output_name
Name of file for output.
std::string input_name
Name of input file.
int verblevel
Verbosity level.
std::ofstream Ouf
Outfile stream for output.
std::ifstream Inf
Infile stream for input.
Constructor & Destructor Documentation
SerialProgram () inline
Default constructor.
Definition at line 155 of file HalfCell.hpp.
                       :
         SerialProgramType()
       {};
SerialProgram (int nargs, char ** args) inline
Constructor designed to take the commandline args.
Definition at line 161 of file HalfCell.hpp.
                                            :
         SerialProgramType(nargs,args)
       {};
virtual ~SerialProgram () inline virtual
Destructor.
Definition at line 225 of file HalfCell.hpp.
References SerialProgram::Ouf.
{
         if(Ouf){
           Ouf.close();
           SetOutStream(std::cout);
         }
       };
Member Function Documentation
virtual int Initialize () inline virtual
Initializes native data structures from commandline args.
Definition at line 167 of file HalfCell.hpp.
References SerialProgram::input_name, SerialProgram::output_name, and SerialProgram::verblevel.
Referenced by ICED::HalfCell::Driver(), and ICED::ExampleProgram::Driver().
       {
         int retval = SerialProgramType::Initialize();
         if(!_command_line.GetOption("help").empty()){
           std::ostringstream Ostr;
           Ostr << _command_line.LongUsage() << std::endl;
           StdOut(Ostr.str());
           return(-1);
         }
         if(retval){
           std::ostringstream Ostr;
           Ostr << _command_line.ErrorReport() << std::endl
                << std::endl << _command_line.ShortUsage() << std::endl;
           ErrOut(Ostr.str());
           return(retval);
         }
         // Check if output file is specified
         output_name = _command_line.GetOption("output");
         // Set input file to first argument
         std::vector<std::string> args(_command_line.GetArgs());
         input_name = args[0];
         // Check the verbosity level
         std::string sverb(_command_line.GetOption("verbosity"));
         if(sverb.empty() || sverb == ".true.")
           verblevel = 1;
         else {
           std::istringstream Vin(sverb);
           Vin >> verblevel;
           if(verblevel < 0)
             verblevel = 1;
         }
         SetVerbLevel(verblevel);
         // If high verbosity, stick a configuration blurb to stdout.
         if(verblevel > 1){
           std::ostringstream Ostr;
           Ostr << "Configuration:" << std::endl
                << "verbosity           = " << verblevel << std::endl
                << "input_name          = " << input_name << std::endl;
           if(!output_name.empty())
             Ostr << "output file         = " << output_name << std::endl;
           Ostr << std::endl;
           StdOut(Ostr.str());
         }
         return(0);
       };
int Run () virtual
This function implements the main function executed by the program.
Definition at line 17 of file HalfCell.cpp.
References SerialProgram::Inf, SerialProgram::input_name, SerialProgram::Ouf, ICED::HalfCell::phi_e, ICED::HalfCell::phi_s, and ICED::HalfCell::wallFlux.
Referenced by ICED::HalfCell::Driver(), and ICED::ExampleProgram::Driver().
   {
     // FunctionEntry("NAME"): Updates the user-defined stack and
     // the program profiles with timing information. The placement
     // of FunctionEntry and FunctionExit calls is at the developer's
     // discretion.
     FunctionEntry("Run");
     std::ostringstream Ostr;
     // Open the specified input file for reading
     Inf.open(input_name.c_str());
     if(!Inf){
       // If the input file failed to open, notify to
       // the error stream and return non-zero
       std::ostringstream Ostr;
       Ostr << "Error: Could not open input file, "
            << input_name << ".";
       ErrOut(Ostr.str());
       FunctionExit("Run");
       return(1);
     }
     // Create output directory if it does not exist
     std::string outputDir = "Output";
     if(!IRAD::Sys::FILEEXISTS(outputDir))
       IRAD::Sys::CreateDirectory(outputDir);
 /*
     // Open the specified output file for writing
     bool use_outfile = false;
     if(!output_name.empty()){
       use_outfile = true;
       Ouf.open(output_name.c_str());
       if(!Ouf){
         // If the output file failed to open, notify
         // to error stream and return non-zero
         std::ostringstream Ostr;
         Ostr << "Error: Unable to open output file, " << output_name << ".";
         ErrOut(Ostr.str());
         // don't forget to tell the profiler/stacker the
         // function is exiting.
         FunctionExit("Run");
         return(1);
       }
     }
 */
     // read parameters from file and set solver input data
     IRAD::Util::Parameters deviceParams;
     deviceParams.ReadFromStream(Inf);
     // Create an object to hold the Device data
     // pass in the global object to get access to member functions
     Teuchos::RCP<ICED::HalfCell::DeviceData> pDeviceData =
       Teuchos::rcp(new ICED::HalfCell::DeviceData(*this));
     std::vector<IRAD::Util::Parameters> componentParams;
     // get the parameters for the components
     int error = pDeviceData->GetDeviceComponentParameters(deviceParams, componentParams);
     if(error > 0){
       Ostr << "Error reading component Parameters from file" << std::endl;
       ErrOut(Ostr.str());
       FunctionExit("Run");
       return(1);
     }
     // build the device
     error = pDeviceData->BuildDevice(deviceParams, componentParams);
     if(error > 0){
       Ostr << "Error building device" << std::endl;
       ErrOut(Ostr.str());
       FunctionExit("Run");
       return(1);
     }
     // Initialize device solution data
     Teuchos::RCP<TransientSolverInterface> pTransientSolverInterface =
       Teuchos::rcp(new TransientSolverInterface(pDeviceData));
     if (pDeviceData->initializationType == 2) {
       //
       // set initial potential in the electrolyte
       // this is a big kludge that needs to be fixed
       // this only works if the dimensions match what was read in from input
       //
       // assumes 3 components and that they are ordered from left to right
       // also assumes that the current is applied on the right current collector
       //
       // there must be a way to do this automatically and generally
       int nx = pDeviceData->pSolutionData->numNodes;
       double kappa = pDeviceData->deviceComponents[2]->pSolutionData->electrolyteConductivity
                      *pow(pDeviceData->deviceComponents[2]->pSolutionData->electrolyteVolumeFraction,
                      pDeviceData->deviceComponents[2]->pSolutionData->bruggemanCoefficient);
       double sigma = pDeviceData->deviceComponents[2]->pSolutionData->solidConductivity*
                      (1.0-pDeviceData->deviceComponents[2]->pSolutionData->electrolyteVolumeFraction);
       double interfaceLocation1 = pDeviceData->deviceComponents[0]->pSolutionData->xMax;
       double interfaceLocation2 = pDeviceData->deviceComponents[1]->pSolutionData->xMax;
       double potentialOld = 0;
       double potentialNew = 0;
       double electrolyteCurrent = 0;
       int componentIndex=2;
       double x;
       double volumeFraction = pDeviceData->deviceComponents[2]->
                               pSolutionData->electrolyteVolumeFraction;
       double xR = pDeviceData->deviceComponents[2]->pSolutionData->xMax;
       double xL = pDeviceData->deviceComponents[2]->pSolutionData->xMin;
       double h = xR-xL;
       double dx = h/(nx-3);
       //double iZero = pDeviceData->deviceComponents[2]->rightBCValue[phi_s];
       double iZero = -pDeviceData->deviceComponents[2]->rightBCValue[phi_s]*sigma;
       double iR = 0;
       double iL = iZero;
       double phiR = 0;
       double phiL = iZero*h/kappa+phiR;
       double radius = pDeviceData->deviceComponents[2]->pSolutionData->poreRadius;
       //double area = 3*h*(1-volumeFraction)/radius/(nx-2);
       double area = 3*(1-volumeFraction)/radius;
       int nxComp = pDeviceData->deviceComponents[2]->pSolutionData->numNodes-2;
       double wf = -iZero/h/area/nxComp/
                   (pDeviceData->pSolutionData->faradayConstant);
       // calculate open circuit potential
       // stolen dirctly from Butler-Volmer
       int index = 0;
       double maxConc = 3600.0*pDeviceData->deviceComponents[index]->pSolutionData->coulombicCapacity*
                               pDeviceData->deviceComponents[index]->pSolutionData->solidDensity/
                               pDeviceData->pSolutionData->faradayConstant;
       double percentCharged=pDeviceData->deviceComponents[index]->pSolutionData->
                             initialSolidLiConcentration/maxConc;
       // MCMB 2528 graphite measured by Chris Bogatu 2000,
       // Telcordia and PolyStor materials
       double pc = percentCharged;
       double openCircuitAnode =
         0.194+1.5*exp(-120.0*pc)
         + 0.0351*tanh((pc-0.286)/0.083)
         - 0.0045*tanh((pc-0.849)/0.119)
         - 0.035*tanh((pc-0.9233)/0.05)
         - 0.0147*tanh((pc-0.5)/0.034)
         - 0.102*tanh((pc-0.194)/0.142)
         - 0.022*tanh((pc-0.9)/0.0164)
         - 0.011*tanh((pc-0.124)/0.0226)
         + 0.0155*tanh((pc-0.105)/0.029);
       std::cout << "openCircuitAnode " << openCircuitAnode << std::endl;
           // Cobalt dioxide (CoO2)
       index = 2;
       maxConc = 3600.0*pDeviceData->deviceComponents[index]->pSolutionData->coulombicCapacity*
                               pDeviceData->deviceComponents[index]->pSolutionData->solidDensity/
                               pDeviceData->pSolutionData->faradayConstant;
       percentCharged=pDeviceData->deviceComponents[index]->pSolutionData->
                               initialSolidLiConcentration/maxConc;
           double stretch = 1.062;
           pc = stretch*percentCharged;
           double openCircuitCathode =
             2.16216+0.07645*tanh(30.834-54.4806*pc)
             + 2.1581*tanh(52.294-50.294*pc)
             - 0.14169*tanh(11.0923-19.8543*pc)
             + 0.2051*tanh(1.4684-5.4888*pc)
             + 0.2531*tanh((-pc+0.56478)/0.1316)
             - 0.02167*tanh((pc-0.525)/0.006);
           std::cout << "openCircuitCathode " << openCircuitCathode << std::endl;
       // hard wired to start from right, assumes that is where the current is
       double openCirc=openCircuitCathode;
       for (int j=nx-2; j>0 ; j--) {
         x = pDeviceData->pSolutionData->xCoords[j];
         // set electrolyte conductivity
         if (x > interfaceLocation2) {
           componentIndex = 2;
         } else if (x > interfaceLocation1) {
           componentIndex = 1;
         } else {
           componentIndex = 0;
         }
         // calculate potential at the edges
         // moving across interface 2 puts us into the separator
         if (x == interfaceLocation2) {
           volumeFraction = pDeviceData->deviceComponents[componentIndex]->
                            pSolutionData->electrolyteVolumeFraction;
           kappa = pDeviceData->deviceComponents[componentIndex]->pSolutionData->electrolyteConductivity
                   *pow(volumeFraction,1.5);
           xR = pDeviceData->deviceComponents[componentIndex]->pSolutionData->xMax;
           xL = pDeviceData->deviceComponents[componentIndex]->pSolutionData->xMin;
           h = xR-xL;
           iR = iL;
           phiR = phiL;
           phiL = iZero*h/kappa+phiR;
           //radius = 0;
           //wf = 0;
           //openCirc = 0;
         // moving across interface 1 puts us into the anode
         } else if (x == interfaceLocation1) {
           volumeFraction = pDeviceData->deviceComponents[componentIndex]->
                            pSolutionData->electrolyteVolumeFraction;
           kappa = pDeviceData->deviceComponents[componentIndex]->pSolutionData->electrolyteConductivity
                   *pow(volumeFraction,1.5);
           xR = pDeviceData->deviceComponents[componentIndex]->pSolutionData->xMax;
           xL = pDeviceData->deviceComponents[componentIndex]->pSolutionData->xMin;
           h = xR-xL;
           iL = 0;
           phiR = phiL;
           phiL = iZero*h/kappa+phiR;
           radius = pDeviceData->deviceComponents[componentIndex]->pSolutionData->poreRadius;
           nxComp = pDeviceData->deviceComponents[componentIndex]->pSolutionData->numNodes-2;
           //area = 3*h*(1-volumeFraction)/radius/(nx-2);
           area = 3*(1-volumeFraction)/radius;
           openCirc=openCircuitAnode;
           openCirc=-1.;
           wf = (iR-iL)/h/area/nxComp/
                (pDeviceData->pSolutionData->faradayConstant);
         }
         global_ordinal_type rowIndex = j;
         // set electrolyte current
         electrolyteCurrent = iL + (iR - iL)*(x-xL)/h;
         // set potential in electrolyte using forward euler
         potentialOld = potentialNew;
         dx = pDeviceData->pSolutionData->xCoords[j] -
              pDeviceData->pSolutionData->xCoords[j-1];
         potentialNew = potentialOld+dx*electrolyteCurrent/kappa;
         pDeviceData->pSolutionData->solutionEpetra->
           ReplaceGlobalValue(rowIndex, phi_e, potentialNew);
         // set wallFlux
   /*
         if (radius == 0) {
           wf = 0;
         } else {
           wf = (iR-iL)/h/area/
                (pDeviceData->pSolutionData->faradayConstant);
         }
   */
         pDeviceData->pSolutionData->solutionEpetra->
           ReplaceGlobalValue(rowIndex, wallFlux, wf);
         // set potential in solid
         double solidPotential = openCirc + potentialNew;
         if (openCirc == 0 )
           solidPotential = 0;
         else if (openCirc < 0)
           solidPotential = potentialNew;
         pDeviceData->pSolutionData->solutionEpetra->
           ReplaceGlobalValue(rowIndex, phi_s, solidPotential);
         // moving across interface 2 puts us into the cathode
         // doing this last gets the voltage and wallFlux correct
         // on the boundary
         if (x == interfaceLocation2) {
           radius = 0;
           wf = 0;
           openCirc = 0;
         }
         // this neglects kd, but should be close
         std::cout << "x[" << j << "]=" << pDeviceData->pSolutionData->xCoords[j] <<
           " i_e = " << (potentialNew - potentialOld)/5.e-6*kappa <<
           " electrolyteCurrent = " << electrolyteCurrent << std::endl;
       }
       // give solution data to components
       pDeviceData->CopyDataToComponents();
       // give solution data to global storage
       pDeviceData->CopyDeviceToGlobalStorage();
       std::cout << "Initial Conditions\n";
       pDeviceData->pSolutionData->solutionEpetra->Print(std::cout);
       //FunctionExit("Run");
       //return(0);
     }
     // Write the initial conditions to the output file
     pDeviceData->DumpSolution(pDeviceData->currentTime);
     // Solve!
     pTransientSolverInterface->TransientSolver();
     // Write the results to the output file
     // don't write if we aling with a dump interval, that has already been done
     if (pDeviceData->currentIteration % pDeviceData->dumpInterval != 0)
       pDeviceData->DumpSolution(pDeviceData->currentTime);
     StdOut(Ostr.str(),1);
     // ---------- Program End -----------------
     // Close both files
     Ouf.close();
     Inf.close();
     // Update the stacker/profiler that we are exiting
     // this function.
     FunctionExit("Run");
     // return 0 for success
     return(0);
   }
int VerbLevel () const inline
Returns verbosity level.
Definition at line 221 of file HalfCell.hpp.
References SerialProgram::verblevel.
Referenced by ICED::HalfCell::Driver(), and ICED::ExampleProgram::Driver().
 { return verblevel;};
Member Data Documentation
std::ifstream Inf protected
Infile stream for input.
Definition at line 150 of file HalfCell.hpp.
Referenced by SerialProgram::Run().
std::string input_name protected
Name of input file.
Definition at line 144 of file HalfCell.hpp.
Referenced by SerialProgram::Initialize(), and SerialProgram::Run().
std::ofstream Ouf protected
Outfile stream for output.
Definition at line 148 of file HalfCell.hpp.
Referenced by SerialProgram::Run(), and SerialProgram::~SerialProgram().
std::string output_name protected
Name of file for output.
Definition at line 142 of file HalfCell.hpp.
Referenced by SerialProgram::Initialize().
int verblevel protected
Verbosity level.
Definition at line 146 of file HalfCell.hpp.
Referenced by SerialProgram::Initialize(), and SerialProgram::VerbLevel().
The documentation for this class was generated from the following files:
HalfCell.hpp
HalfCell.cpp
TrilinosExample.cpp