ICED_Physics: ICED::TestingObject::Test__ModulePriority
void Test__ModulePriority (ResultsType & result) inline
Test for ICED::DeviceComponent.
Parameters
result ICED::TestResults object to store test results.
This function builds a DeviceData object and tests the module priority. It loads several modules with varying priority and checks that the modules get called in the correct order.
Definition at line 332 of file ICEDTest.H.
References DeviceData::BuildDevice(), DeviceData::deviceComponents, TestingObject< ResultsType >::global, and TestingObject< ResultsType >::pDeviceData.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       Ostr.str("");
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       // device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1","firstComponent component1.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("TransferenceNumber","5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("WallFlux","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("OhmsLawSolid","4"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("Diffusion","3"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ConcentrationDiffusion","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ActivityCoefficient","7"));
       // initial data required for the physics modules to build
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numberOfIons","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("concentrationDiffusionCoefficients","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("transferenceCoefficients","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("poreRadius","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("electrolyteVolumeFraction","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("faradayConstant","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("solidConductivity","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("bruggemanCoefficient","6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("activityCoefficients","6"));
       // build the device
       bool builds=false;
       int error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       else
         std::cout << "Error building device for ModulePriority" << std::endl;
       int numModules = pDeviceData->deviceComponents[0]->componentPhysicsModules.size();
       int previousPriority=0;
       for (int i=0; i<numModules; ++i) {
         int nextPriority = pDeviceData->deviceComponents[0]->
           componentPhysicsModules[i]->modulePriority;
         if (nextPriority < previousPriority) {
           builds = false;
           std::cout << "Incorrect ModulePriority" << std::endl;
           std::cout << "For module " <<
             pDeviceData->deviceComponents[0]->componentPhysicsModules[i]->moduleName <<
             " previous module was priority " << previousPriority << " current priority is " <<
             nextPriority << std::endl;
         }
         previousPriority = nextPriority;
       }
       result.UpdateResult("ModulePriority:Works",builds);
       delete pDeviceData;
     }