ICED_Physics: ICED::TestingObject::Test__ConcentrationDiffusion
void Test__ConcentrationDiffusion (ResultsType & result) inline
Test for ICED::ConcentrationDiffusion.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of ConcentrationDiffusion module.
This function initializes the input data values for the simulation. It then calls the ConcentrationDiffusion class SolvePhysics function, passing in test values for calculation. Finally it verifies that SolvePhysics populates its function and derivative with the correct values.
Definition at line 3968 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, and TestingObject< ResultsType >::pDeviceData.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__ConcentrationDiffusion" << std::endl;
       bool builds=false;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int error;
       int numNodes=8;
       std::vector<double> diffCoeff(3);
       std::vector<double> solution(numNodes+2);
       std::vector<double> diff(numNodes+2);
       std::vector<double> diffDer(numNodes+2);
       std::vector<double> diffDerDer(numNodes+2);
       std::vector<double> coefficient(3);
       std::vector<double> x(numNodes+2);
       std::stringstream ss;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       diffCoeff[0] = -4.1;
       diffCoeff[1] = 6.3;
       diffCoeff[2] = 9.4;
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ecdc1","firstComponent component1.inp"));
       // component1 parameters
       ss.clear();
       ss.str("");
       ss << numNodes;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numNodes", ss.str()));
       ss.clear();
       ss.str("");
       ss << diffCoeff[0] << " " << diffCoeff[1] << " " << diffCoeff[2];
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("concentrationDiffusionCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMin", "-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMax", "1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ConcentrationDiffusion","1"));
       // build the device
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("ConcentrationDiffusion:Builds",builds);
       int iStartIn = pDeviceData->deviceComponents[0]
           ->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       //Get x values for the nodes
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
           ->pSolutionData->xCoords;
       // set conc_e values to 2.5x^2 + 7.2x - 0.1
       coefficient[0] = 2.5;
       coefficient[1] = 7.2;
       coefficient[2] = -0.1;
       // Generate parabola
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  "
              << solution[i] << std::endl;
       }
       //Initialize values for conc_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]
             =solution[i];
       }
       //Call ConcentrationDiffusion SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       double value;
       //Check concentrationDiffusion
       std::cout << "concentrationDiffusion:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              concentrationDiffusion[i] << " ";
         value = diffCoeff[0]*solution[i]*solution[i] + diffCoeff[1]*solution[i]
               + diffCoeff[2];
         std::cout << "value = " << value << std::endl;
         if(fabs(value - pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              concentrationDiffusion[i]) > 1.0e-10){
           works = false;
           std::cout << "Fails in concentrationDiffusion check" << std::endl;
         }
       }
       std::cout << std::endl;
       //Check concentrationDiffusionDer
       std::cout << "concentrationDiffusionDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->concentrationDiffusionDer[i] << " ";
         value = diffCoeff[0]*2.0*solution[i] + diffCoeff[1];
         std::cout << "value = " << value << std::endl;
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->concentrationDiffusionDer[i]) > 1.0e-10){
           works = false;
           std::cout << "Fails in concentrationDiffusionDer check" << std::endl;
         }
       }
       std::cout << std::endl;
       //Check concentrationDiffusionDerDer
       std::cout << "concentrationDiffusionDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->concentrationDiffusionDerDer[i] << " ";
         value = 2.0*diffCoeff[0];
         std::cout << "value = " << value << std::endl;
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->concentrationDiffusionDerDer[i]) > 1.0e-10){
           works = false;
           std::cout << "Fails in concentrationDiffusionDerDer check" << std::endl;
         }
       }
       std::cout << std::endl;
       result.UpdateResult("ConcentrationDiffusion:Works",works);
       delete pDeviceData;
     }