ICED_Physics: ICED::HalfCell::DeviceData::BuildDevice
int BuildDevice (IRAD::Util::Parameters & deviceParameters, std::vector< IRAD::Util::Parameters > & componentParameters)
Initialization of the entire device data structure.
This function builds the device including:
reading input files
initializing components
loading physics modules
setting appropriate input data
We note that most of these things could be done in a constructor, but with the file reads, it is easier to do them outside the constructor to make error tracking easier.
We will name the components in the order that they are read (erdc[1-9]) correlating to their position in the componentParameter vector.
Parameters
deviceParameters Parameter object defining the device parameters
componentParameters Vector of Parameter objects defining the component parameters
Returns
int An error code
Test:
None
Todo:
This need consistency checks so that we ensure that data needed to initialize the mesh is read in appropriately.
Definition at line 607 of file DeviceData.cpp.
References DeviceData::CopyDataFromComponents(), DeviceData::CopyDeviceToGlobalStorage(), DeviceData::deviceComponents, DeviceData::LoadComponents(), DeviceData::pSolutionData, DeviceData::SetData(), SolutionData::SetData(), and DeviceData::SetupGlobalData().
Referenced by TestingObject< ResultsType >::RunIntercalationModule(), TestingObject< ResultsType >::Test__ActivityCoefficient(), TestingObject< ResultsType >::Test__ButlerVolmer(), TestingObject< ResultsType >::Test__CheckParamsBad(), TestingObject< ResultsType >::Test__CheckParamsGood(), TestingObject< ResultsType >::Test__ComponentBoundaryConditions(), TestingObject< ResultsType >::Test__ConcentrationDiffusion(), TestingObject< ResultsType >::Test__DeviceData(), TestingObject< ResultsType >::Test__DeviceDataMapping(), TestingObject< ResultsType >::Test__Diffusion(), TestingObject< ResultsType >::Test__IonMigration(), TestingObject< ResultsType >::Test__ModulePriority(), TestingObject< ResultsType >::Test__OhmsLawElectrolyte(), TestingObject< ResultsType >::Test__OhmsLawSolid(), TestingObject< ResultsType >::Test__TransferenceNumber(), and TestingObject< ResultsType >::Test__WallFlux().
{
     FunctionEntry("BuildDevice");
     std::ostringstream Ostr;
     pSolutionData = new ICED::HalfCell::SolutionData(*this);
     int error = pSolutionData->SetData(deviceParameters);
     if(error > 0){
       Ostr << "Error intializing input data" << std::endl;
       ErrOut(Ostr.str());
       FunctionExit("BuildDevice");
       return(1);
     }
     // now read Device specific input data
     error = SetData(deviceParameters);
     if(error > 0){
       Ostr << "Error setting device specific input data" << std::endl;
       ErrOut(Ostr.str());
       FunctionExit("BuildDevice");
       return(1);
     }
     // now read and load Device specific modules
     error = LoadComponents(deviceParameters);
     if(error > 0){
       Ostr << "Error building componets" << std::endl;
       ErrOut(Ostr.str());
       FunctionExit("BuildDevice");
       return(1);
     }
     // have the parameters for each component, proceed to load them
     for (size_t i=0; i < deviceComponents.size(); ++i) {
       error = deviceComponents[i]->pSolutionData->SetData(componentParameters[i]);
       if(error > 0){
         Ostr << "Error setting component parameters" << std::endl;
         ErrOut(Ostr.str());
         FunctionExit("BuildDevice");
         return(1);
       }
       error = deviceComponents[i]->InitializeBoundary(componentParameters[i]);
       if(error > 0){
         Ostr << "Error setting component boundary conditions" << std::endl;
         ErrOut(Ostr.str());
         FunctionExit("BuildDevice");
         return(1);
       }
       // now load the necessary modules for this component
       error = deviceComponents[i]->LoadModules(componentParameters[i]);
       if(error > 0){
         Ostr << "Error loading Physics Modules for " << i
              << deviceComponents[i]->componentName << std::endl;
         ErrOut(Ostr.str());
         FunctionExit("BuildDevice");
         return(1);
       }
         //calls my new error checking for parameters function
         //we need to find a way to get the ideal parameters.
         //call one for every physics module: Intercalation::CheckParams, Diffusion::CheckParams, etc. Add an idealParameters variable in each of those classes and populate.
         std::vector<PhysicsModule*>::iterator It;
         for (It = deviceComponents[i]->componentPhysicsModules.begin(); It != deviceComponents[i]->componentPhysicsModules.end(); ++It) {
         error = (*It)->CheckParams((componentParameters[i]), (deviceParameters));
         if (error>0) {
         FunctionExit("BuildDevice");
         return(1);
         }
         }
     }
     // now setup the mapping between the device and components
     // and initialize the global data structures
     SetupGlobalData();
     // now we initialize the solution
     std::cout << "Initializing solution" << std::endl;
     for (size_t i=0; i<deviceComponents.size(); ++i) {
       // set solution in vector storage
       deviceComponents[i]->InitializeComponentSolution();
       // apply boundary conditions
       deviceComponents[i]->ApplyComponentBC();
       deviceComponents[i]->ApplyInternalBC();
       // transfer to Epetra_MultiVector
       deviceComponents[i]->FinalizeComponent();
     }
     CopyDataFromComponents();
     CopyDeviceToGlobalStorage();
     FunctionExit("BuildDevice");
     return(0);
   } // Function BuildDevice