ICED_Physics: ICED::TestingObject::Process
virtual void Process (ResultsType & result) inline virtual
Runs all tests implemented by the ICED::TestingObject.
Parameters
result ICED::TestResults object to store test results.
Definition at line 6010 of file ICEDTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ActivityCoefficient(), TestingObject< ResultsType >::Test__ButlerVolmer(), TestingObject< ResultsType >::Test__CheckParamsBad(), TestingObject< ResultsType >::Test__CheckParamsGood(), TestingObject< ResultsType >::Test__ComponentBoundaryConditions(), TestingObject< ResultsType >::Test__ConcentrationDiffusion(), TestingObject< ResultsType >::Test__DeviceData(), TestingObject< ResultsType >::Test__DeviceDataMapping(), TestingObject< ResultsType >::Test__Diffusion(), TestingObject< ResultsType >::Test__Intercalation(), TestingObject< ResultsType >::Test__IonMigration(), TestingObject< ResultsType >::Test__ModulePriority(), TestingObject< ResultsType >::Test__OhmsLawElectrolyte(), TestingObject< ResultsType >::Test__OhmsLawSolid(), TestingObject< ResultsType >::Test__TransferenceNumber(), and TestingObject< ResultsType >::Test__WallFlux().
Referenced by ICED::Test().
{
       Prologue();
       Test__DeviceData(result);
       Test__DeviceDataMapping(result);
       Test__ModulePriority(result);
       Test__ComponentBoundaryConditions(result);
       Test__CheckParamsGood(result);
       Test__CheckParamsBad(result);
       //Test__ExampleFunction(result);
       //Test__TrapezoidQuadrature(result);
       //Test__MidPointQuadrature(result);
       Test__ButlerVolmer(result);
       Test__WallFlux(result);
       Test__Diffusion(result);
       Test__TransferenceNumber(result);
       Test__ConcentrationDiffusion(result);
       Test__OhmsLawElectrolyte(result);
       Test__OhmsLawSolid(result);
       Test__Intercalation(result);
       Test__ActivityCoefficient(result);
       Test__IonMigration(result);
       //Test__SteadySolver(result);
       //Test__SteadySolverNL(result);
       //Test__SolverFE(result);
       //Test__SolverBE(result);
       //Test__SolverBENL(result);
       //Test__SolverOhmsLawSolid(result);
       //Test__SolverOhmsLawElectrolyte(result);
       //Test__SolverButlerVolmer(result);
       //Test__SolverIntercalation(result);
       Epilogue();
     }