ICED_Physics: ICED::TestingObject::Test__OhmsLawElectrolyte
void Test__OhmsLawElectrolyte (ResultsType & result) inline
Test for ICED::OhmsLawElectrolyte.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of the OhmsLawElecrolyte module.
This function initializes the input data values for the simulation.It then calls the OhmsLawElectrolyte class SolvePhysics. Finally it verifies that SolvePhysics populates the function and Jacobian vector with the correct values
Definition at line 4801 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, TestingObject< ResultsType >::pDeviceData, ICED::HalfCell::phi_e, and ICED::HalfCell::wallFlux.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__OhmsLawElectrolyte" << std::endl;
       // variables required by the module
       bool works=true;
       int build_error;
       int numNodes=5;
       std::vector<double> c(numNodes+2);
       std::vector<double> phi(numNodes+2);
       std::vector<double> jn(numNodes+2);
       std::vector<double> cCoeff(3);
       std::vector<double> phiCoeff(3);
       std::vector<double> jnCoeff(3);
       std::vector<double> transCoeff(3);
       std::vector<double> actCoeff(5);
       std::vector<double> x(numNodes+2);
       std::vector<double>* f;
       std::vector<double>* fp;
       std::vector<double>* fpp;
       std::vector<double>* t;
       std::vector<double>* tp;
       double k0=2.3, E=0.25, F=3.0, R=2.3, T=21.1, si=-1.5, n=-6.7, z=1.3;
       double v=5.3;
       double As=0.675; // has to be consistent with poreRadius
       std::stringstream ss;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       //device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ecdc1","firstComponent component1.inp"));
       transCoeff[0] = 2.5;
       transCoeff[1] = 3.1;
       transCoeff[2] = 4.0;
       actCoeff[0] = 1.5;
       actCoeff[1] = 5.7;
       actCoeff[2] = -0.5;
       actCoeff[3] = 2.5;
       actCoeff[4] = -1.8;
       // component1 parameters
       ss.clear();
       ss.str("");
       ss << numNodes;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numNodes", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMin", "-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMax", "2"));
       ss.clear();
       ss.str("");
       ss << k0;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("electrolyteConductivity", ss.str()));
       ss.clear();
       ss.str("");
       ss << E;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("electrolyteVolumeFraction", ss.str()));
       ss.clear();
       ss.str("");
       ss << F;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("faradayConstant", ss.str()));
       ss.clear();
       ss.str("");
       ss << R;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("gasConstant", ss.str()));
       ss.clear();
       ss.str("");
       ss << T;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("temperature", ss.str()));
       ss.clear();
       ss.str("");
       ss << si;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("stoichParameter", ss.str()));
       ss.clear();
       ss.str("");
       ss << n;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numberOfElectrons", ss.str()));
       ss.clear();
       ss.str("");
       ss << z;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("chargeNumber", ss.str()));
       ss.clear();
       ss.str("");
       ss << v;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numberOfIons", ss.str()));
       ss.clear();
       ss.str("");
       ss << As;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("surfaceAreaA", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("TransferenceNumber","1"));
       ss.clear();
       ss.str("");
       ss << transCoeff[0] << " " << transCoeff[1] << " " << transCoeff[2];
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("transferenceCoefficients", ss.str()));
       ss.clear();
       ss.str("");
       ss << actCoeff[0] << " " << actCoeff[1] << " " << actCoeff[2]
          << " " << actCoeff[3] << " " << actCoeff[4];
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("activityCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ActivityCoefficient","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("OhmsLawElectrolyte","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("poreRadius","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("bruggemanCoefficient","1.5"));
       // build the device
       build_error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (build_error != 0)
         works=false;
       int iStartIn = pDeviceData->deviceComponents[0]
           ->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       //Get x values for the nodes
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
           ->pSolutionData->xCoords;
       //Iniitalize the solution variables using parabolas
       // set conc_e values to 2.5x^2 + 3.7x - 5.1
       cCoeff[0] = 2.5;
       cCoeff[1] = 3.7;
       cCoeff[2] = -5.1;
       // Generate parabola
       GenerateParabolicFunction(c, x, cCoeff, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  "
              << c[i] << std::endl;
       }
       //Initialize values for conc_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]
             =c[i];
       }
       // set phi_e values to 5.1x^2 - 4.2x + 3.7
       phiCoeff[0] = 5.1;
       phiCoeff[1] = -4.2;
       phiCoeff[2] = 3.7;
       // Generate parabola
       GenerateParabolicFunction(phi, x, phiCoeff, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  "
              << phi[i] << std::endl;
       }
       //Initialize values for phi_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::phi_e]
             =phi[i];
       }
       // set wallFlux values to 8.7x^2 + 3.1x - 5.4
       jnCoeff[0] = 8.7;
       jnCoeff[1] = 3.1;
       jnCoeff[2] = -5.4;
       // Generate parabola
       GenerateParabolicFunction(jn, x, jnCoeff, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  "
              << jn[i] << std::endl;
       }
       //Initialize values for wallFlux as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::wallFlux]
             =jn[i];
       }
       //Call TransferenceNumber SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       //Call ActivityCoefficient SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[1]->
          SolvePhysics();
       //Call OhmsLawElectrolyte SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[2]->
          SolvePhysics();
       f = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficient;
       //Check activityCoefficient
       std::cout << "activityCoefficient:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficient[i] << " ";
       }
       std::cout << std::endl;
       fp = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDer;
       //Check activityCoefficientDer
       std::cout << "activityCoefficientDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDer[i] << " ";
       }
       std::cout << std::endl;
       fpp = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDer;
       //Check activityCoefficientDerDer
       std::cout << "activityCoefficientDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDer[i] << " ";
       }
       std::cout << std::endl;
       //Check activityCoefficientDerDerDer
       std::cout << "activityCoefficientDerDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDerDer[i] << " ";
       }
       std::cout << std::endl;
       t = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumber;
       //Check transferenceNumber
       std::cout << "transferenceNumber:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumber[i] << " ";
       }
       std::cout << std::endl;
       tp = &pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDer;
       //Check transferenceNumberDer
       std::cout << "transferenceNumberDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDer[i] << " ";
       }
       std::cout << std::endl;
       //Check transferenceNumberDerDer
       std::cout << "transferenceNumberDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDerDer[i] << " ";
       }
       std::cout << std::endl;
       std::vector<double> exact(numNodes+2);
       double kd, k, dkdc;
       //Calculate exact function answer
       //(based on using parabolic functions for the
       //solution vectors and
       //check OhmsLawElectrolyte computation
       k = k0*pow(E,pDeviceData->deviceComponents[0]->pSolutionData->bruggemanCoefficient);
       for(int i=iStartIn; i<=iEndIn; i++){
         std::cout << "******************************" << std::endl;
         std::cout << "k = " << k << std::endl;
         std::cout << "R = " << R << std::endl;
         std::cout << "T = " << T << std::endl;
         std::cout << "F = " << F << std::endl;
         std::cout << "c[i] = " << c[i] << std::endl;
         std::cout << "f[i] = " << (*f)[i] << std::endl;
         std::cout << "t[i] = " << (*t)[i] << std::endl;
         std::cout << "si = " << si << std::endl;
         std::cout << "n = " << n << std::endl;
         std::cout << "v = " << v << std::endl;
         std::cout << "z = " << z << std::endl;
         std::cout << "dc/dx = " << 5.0*x[i]+3.7 << std::endl;
         std::cout << "d2c/dx2 = " << 5.0 << std::endl;
         std::cout << "d2phidx2 = " << 10.2 << std::endl;
         std::cout << "x = " << x[i] << std::endl;
         kd = k*R*T/F*(1.0 + c[i]/(*f)[i]*(*fp)[i])*(si/(n*v) + (*t)[i]/(z*v));
         std::cout << "kd = " << kd << std::endl;
         dkdc = k*R*T/(F*v)*(((*fp)[i]/(*f)[i]*(1.0 - c[i]*(*fp)[i]/(*f)[i])
              + c[i]*(*fpp)[i]/(*f)[i])*(si/n + (*t)[i]/z) + (*tp)[i]/z*
              (1.0 + c[i]/(*f)[i]*(*fp)[i]));
         std::cout << "dkdc = " << dkdc << std::endl;
         exact[i] = 2.0*k*phiCoeff[0];
         exact[i] += kd*(1.0/c[i]*2.0*cCoeff[0] - 1.0/(c[i]*c[i])*
             (2.0*cCoeff[0]*x[i] + cCoeff[1])*(2.0*cCoeff[0]*x[i] + cCoeff[1]));
         exact[i] += dkdc*(1.0/c[i])*(2.0*cCoeff[0]*x[i] + cCoeff[1])*
             (2.0*cCoeff[0]*x[i] + cCoeff[1]);
         exact[i] += As*F*jn[i];
         std::cout << "exact = " << exact[i] << std::endl;
         std::cout << "computed = " << (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              function)[i][ICED::HalfCell::phi_e] << std::endl;
         //Check that the exact answer and the computed answer are
         //within 1.0e-8 tolerance.
         if(fabs(exact[i] - (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              function)[i][ICED::HalfCell::phi_e]) > 1.0e-8 ){
             works = false;
             std::cout << "FAILS in Ohms Electrolyte function" << std::endl;
         }
       }
 /*
       //Check the Jacobian values against precomputed values
       double value1, value2, value3;
       //Print out the Jacobian for conc_e
       std::cout << std::endl << "Jacobian conc_e (tridiagonal):" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i-1][ICED::HalfCell::phi_e]
            [ICED::HalfCell::conc_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][ICED::HalfCell::phi_e]
            [ICED::HalfCell::conc_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i+1][ICED::HalfCell::phi_e]
            [ICED::HalfCell::conc_e] << std::endl;
       }
       //Check the values for the Jacobian for conc_e
       //check diagonal-1 for first node
       value1 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn][iStartIn-1][ICED::HalfCell::phi_e]
         [ICED::HalfCell::conc_e];
       //check diagonal for second node
       value2 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][ICED::HalfCell::phi_e]
         [ICED::HalfCell::conc_e];
       //check diagonal+1 for third node
       value3 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+2][iStartIn+3][ICED::HalfCell::phi_e]
         [ICED::HalfCell::conc_e];
       if(fabs(value1 + 110.854571700969) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 1" << std::endl;
       }
       if(fabs(value2 - 2887.7939042072) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 2" << std::endl;
       }
       if(fabs(value3 - 164.266018487032) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 3" << std::endl;
       }
       //Print out the Jacobian for phi_e
       std::cout << std::endl << "Jacobian phi_e (tridiagonal):" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i-1][ICED::HalfCell::phi_e]
            [ICED::HalfCell::phi_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][ICED::HalfCell::phi_e]
            [ICED::HalfCell::phi_e] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i+1][ICED::HalfCell::phi_e]
            [ICED::HalfCell::phi_e] << std::endl;
       }
       //Check the values for the Jacobian for phi_e
       //check diagonal-1 for first node
       value1 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn][iStartIn-1][ICED::HalfCell::phi_e]
         [ICED::HalfCell::phi_e];
       //check diagonal for second node
       value2 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][ICED::HalfCell::phi_e]
         [ICED::HalfCell::phi_e];
       //check diagonal+1 for third node
       value3 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+2][iStartIn+3][ICED::HalfCell::phi_e]
         [ICED::HalfCell::phi_e];
       if(fabs(value1 - 0.511111111111111) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_e Jacobian 1" << std::endl;
       }
       if(fabs(value2 + 1.02222222222222) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_e Jacobian 2" << std::endl;
       }
       if(fabs(value3 - 0.511111111111111) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_e Jacobian 3" << std::endl;
       }
       //Check & print out the Jacobian for wallFlux
       std::cout << std::endl << "Jacobian wallFlux (diagonal):" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][ICED::HalfCell::phi_e]
            [ICED::HalfCell::wallFlux] << std::endl;
       }
       //Check the values for the Jacobian for wallFlux
       //check diagonal for second node
       value2 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][ICED::HalfCell::phi_e]
         [ICED::HalfCell::wallFlux];
       if(fabs(value2 - 9.3) > 1.0e-8){
         works = false;
         std::cout << "Fails in conc_e Jacobian 2" << std::endl;
       }
 */
       result.UpdateResult("OhmsLawElectrolyte:Works",works);
       delete pDeviceData;
     }