ICED_Physics: ICED::TestingObject::Test__ActivityCoefficient
void Test__ActivityCoefficient (ResultsType & result) inline
Test for ICED::ActivitCoefficient module.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of TransferenceNumber module.
This fucntion initializes the input data values for the simulation. It then calls the ActivitCoefficient class SolvePhysics function, passing in test values for calculation. Finally it verifies that SolvePhysics populates its function and derivative with the correct values.
Definition at line 4377 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, and TestingObject< ResultsType >::pDeviceData.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__ActivityCoefficient" << std::endl;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int error;
       int numNodes=6;
       std::vector<double> activityCoeff(5);
       std::vector<double> solution(numNodes+2);
       std::vector<double> coefficient(3);
       std::vector<double> x(numNodes+2);
       std::stringstream ss;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       activityCoeff[0] = 1.2;
       activityCoeff[1] = 2.3;
       activityCoeff[2] = 3.4;
       activityCoeff[3] = 4.5;
       activityCoeff[4] = 5.6;
       ss << activityCoeff[0] << " " << activityCoeff[1] << " " << activityCoeff[2] << " "
          << activityCoeff[3] << " " << activityCoeff[4];
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ecdc1","firstComponent component1.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numNodes", "6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("activityCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMin", "-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMax", "1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ActivityCoefficient","1"));
       bool builds = false;
       // build the device
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("ActivityCoefficient:Builds",builds);
       int iStartIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       //Get x values for the nodes
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
           ->pSolutionData->xCoords;
       // set conc_e values to 0.5x^2 + 4.2x - 8.1
       coefficient[0] = 0.5;
       coefficient[1] = 4.2;
       coefficient[2] = -8.1;
       // Generate parabola
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  " << solution[i] << std::endl;
       }
       //Initialize values for conc_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]=solution[i];
       }
       //Call ActivityCoefficient SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       double value;
       //Check activityCoefficient
       std::cout << "activityCoefficient:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficient[i] << " ";
         value = activityCoeff[0]*solution[i]*solution[i]*solution[i]*solution[i] +
                 activityCoeff[1]*solution[i]*solution[i]*solution[i]+
                 activityCoeff[2]*solution[i]*solution[i]+
                 activityCoeff[3]*solution[i]+
                 activityCoeff[4];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficient[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       //Check activityCoefficientDer
       std::cout << "activityCoefficientDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDer[i] << " ";
         value = 4*activityCoeff[0]*solution[i]*solution[i]*solution[i] +
                 3*activityCoeff[1]*solution[i]*solution[i]+
                 2*activityCoeff[2]*solution[i]+
                 activityCoeff[3];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDer[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       //Check activityCoefficientDerDer
       std::cout << "activityCoefficientDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDer[i] << " ";
         value = 12*activityCoeff[0]*solution[i]*solution[i] +
                 6*activityCoeff[1]*solution[i]+
                 2*activityCoeff[2];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDer[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       //Check activityCoefficientDerDerDer
       std::cout << "activityCoefficientDerDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDerDer[i] << " ";
         value = 24*activityCoeff[0]*solution[i]+6*activityCoeff[1];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->activityCoefficientDerDerDer[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       result.UpdateResult("ActivityCoefficient:Works",works);
       delete pDeviceData;
     }