ICED_Physics: TransientSolverInterface Class Reference
TransientSolverInterface Class Reference
Class to hold the interface to the Transient Solver.
Detailed Description
Class to hold the interface to the Transient Solver.
This is the interface to the transient solver. It wraps the nonliner NOX interface.
Todo:
Beef up this discussion.
add support for the global type
Definition at line 170 of file Solver.hpp.
#include <Physics/include/Solver.hpp>
Public Member Functions
TransientSolverInterface (Teuchos::RCP< DeviceData > &device)
Transient Solver Interface.
~TransientSolverInterface ()
Transient Solver Interface Destructor.
void TransientSolver ()
Wrapper for our transient solver.
void TransientForwardEuler ()
Forward Euler transient solver.
void TransientBackwardEuler ()
Backward Euler transient solver.
bool evaluate (NOX::Epetra::Interface::Required::FillType flag, const Epetra_Vector *soln, const Epetra_Vector *solnDot)
evaluate the problem at a time
void setdt (double dt)
Accesor function for setting time step.
double getdt ()
Accesor function for time obtaining step.
Public Member Functions inherited from SolverInterface
SolverInterface (Teuchos::RCP< DeviceData > device)
Solver Interface.
~SolverInterface ()
Solver Interface Destructor.
bool computeF (const Epetra_Vector &x, Epetra_Vector &f, NOX::Epetra::Interface::Required::FillType F)
Implementation of computeF.
bool computeJacobian (const Epetra_Vector &x, Epetra_Operator &Jac)
Implementation of computeJacobian.
bool computePrecMatrix (const Epetra_Vector &x, Epetra_RowMatrix &M)
bool computePreconditioner (const Epetra_Vector &x, Epetra_Operator &O)
Additional Inherited Members
Protected Attributes inherited from SolverInterface
Teuchos::RCP< DeviceData > pDevice
Constructor & Destructor Documentation
TransientSolverInterface (Teuchos::RCP< DeviceData > & device) inline
Transient Solver Interface.
The constructor takes a DeviceData pointer.
Parameters
device Pointer to the global solution data (device)
Definition at line 185 of file Solver.hpp.
     : SolverInterface(device) {}
~TransientSolverInterface () inline
Transient Solver Interface Destructor.
The destructor doesn't need to do anything, because RCPs are smart pointers; they handle deallocation automatically.
Definition at line 194 of file Solver.hpp.
 {}
Member Function Documentation
bool evaluate (NOX::Epetra::Interface::Required::FillType flag, const Epetra_Vector * soln, const Epetra_Vector * solnDot) inline
evaluate the problem at a time
Definition at line 236 of file Solver.hpp.
                                                              {return false;}
double getdt () inline
Accesor function for time obtaining step.
Definition at line 243 of file Solver.hpp.
References SolverInterface::pDevice.
 { return pDevice->dt; }
void setdt (double dt) inline
Accesor function for setting time step.
Definition at line 240 of file Solver.hpp.
References SolverInterface::pDevice.
 { pDevice->dt = dt; }
void TransientBackwardEuler ()
Backward Euler transient solver.
Evalute the function at the next time and advance the solution by delta t
Uses the NOX non-linear solver to advance the function F. Implicitly stable for linear problems, stability is unclear for non-linear problems.
Definition at line 83 of file Solver.cpp.
References SolverInterface::pDevice, ICED::HalfCell::SetupSolver(), and ICED::HalfCell::solutionVariable_t_MAX.
Referenced by TransientSolverInterface::TransientSolver().
{
     std::ostringstream Ostr;
     // save solution from the previous timestep
     pDevice->globalDeviceSolutionOld->Update(1.0, *pDevice->globalDeviceSolution, 0.);
     // component initialization
     // current used by Intercalation to save the previous timestep, pushes
     // the solution back onto a list of all the previous solutions for conc_s
     for (size_t i=0; i<pDevice->deviceComponents.size(); ++i) {
       pDevice->deviceComponents[i]->InitializeComponentPhysics();
       // update time after the component physics is initialized
       pDevice->deviceComponents[i]->pSolutionData->time =
         pDevice->currentTime;
     }
     // setup solver
     // I probably don't have to do this every time, but this is convivient for
     // now to get the code working.
     // I would guess this is not the long pole in the tent, probably the jacobian
     // calculation is more expensive
     SetupSolver(pDevice);
     //call non-linear solve
     NOX::StatusTest::StatusType status = pDevice->noxSolver->solve();
     Ostr << "Nonlinear solver returned with status " << status << std::endl;
     StdOut(Ostr.str());
     // Get the Epetra_Vector with the final solution from the solver.
     const NOX::Epetra::Group& finalGroup =
       dynamic_cast<const NOX::Epetra::Group&> (pDevice->noxSolver->getSolutionGroup ());
     const Epetra_Vector& finalSolution =
       dynamic_cast<const NOX::Epetra::Vector&> (finalGroup.getX
       ()).getEpetraVector ();
     // put the final solution back into our solution vector
     //
     int numDeviceNodes = pDevice->pSolutionData->numNodes;
     for (int i=0; i<solutionVariable_t_MAX; ++i) {
       //for (int j=0; j<pSolutionData->numMyElements; ++j) {
       double* mapping = (*pDevice->globalDeviceSolutionMapping)[i];
       for (int j=0; j<numDeviceNodes; ++j) {
         //global_ordinal_type rowIndex = pSolutionData->myGlobalElements[j];
         if (mapping[j] > 0) {
           global_ordinal_type globalRowIndex = mapping[j];
           double data = finalSolution[globalRowIndex];
           global_ordinal_type rowIndex = j;
           int lclerr = pDevice->pSolutionData->solutionEpetra->
                        ReplaceGlobalValue(rowIndex, i, data);
           if (lclerr != 0) {
             Ostr << "Error copying solution from Vector to MultiVector" << std::endl;
             StdOut(Ostr.str());
             return;
           }
         }
       }
     }
     // copy final solution back to global solution vector
     // do I have to do this?
     pDevice->globalDeviceSolution->Update(1., finalSolution, 0.);
   }
void TransientForwardEuler ()
Forward Euler transient solver.
Simply evalute the function at a given time and advance the solution by delta t
No fancy nonlinear solves. This routine is unstable in time. At a minimum for linear heat transfer, the CFL number must be satisfied.
Definition at line 19 of file Solver.cpp.
References ICED::HalfCell::conc_e, and SolverInterface::pDevice.
Referenced by TransientSolverInterface::TransientSolver().
{
     std::ostringstream Ostr;
     pDevice->globalDeviceFunction->PutScalar(0.);
     // DeviceAssembleF gives us the RHS of our non-linear system at the previous timestep
     pDevice->DeviceAssembleF(*pDevice->globalDeviceSolution, *pDevice->globalDeviceFunction);
     // scale function by dt and add to the old solution
     // this is the Forward Euler discretization
     //pDevice->globalDeviceSolution->Update(pDevice->dt, *pDevice->globalDeviceFunction, 1.0);
 /*
    std::cout << "In TransientSolverInterface, before transfer to global storage\n";
    std::cout << "Printing Solution in GlobalDeviceSolution\n";
    pDevice->globalDeviceSolution->Print(std::cout);
    std::cout << "Printing Solution in GlobalDeviceFunction\n";
    pDevice->globalDeviceFunction->Print(std::cout);
 */
     int myNodes = pDevice->pSolutionData->numMyElements-2;
     int iStart = pDevice->pSolutionData->iStartInternal-2;
     int iEnd = pDevice->pSolutionData->iEndInternal+1;
     //std::cout << "mynodes=" << myNodes <<  std::endl;
     //std::cout << "iStart=" << iStart <<  std::endl;
     //std::cout << "iEnd=" << iEnd <<  std::endl;
     for (int j=iStart; j<=iEnd; ++j) {
       global_ordinal_type rowIndex = pDevice->pSolutionData->myGlobalElements[j];
       int index = conc_e*myNodes+rowIndex;
       double data = (*pDevice->globalDeviceSolution)[index] +
                     pDevice->dt*(*pDevice->globalDeviceFunction)[index];
       int lclerr = pDevice->globalDeviceSolution->ReplaceGlobalValues(1, &data, &index);
       if (lclerr != 0) {
         Ostr << "Error setting values in globalDeviceSolution, TransientForwardEuler" << std::endl;
         StdOut(Ostr.str());
         return;
       }
     }
 /*
     double* mapping = (*globalDeviceSolutionMapping)[conc_e];
     double* vector = (*(pSolutionData->functionEpetra))[conc_e];
     for (int j=0; j<numDeviceNodes; ++j) {
       if (mapping[j] > 0) {
         global_ordinal_type rowIndex = j;
         double data = vector[rowIndex];
         global_ordinal_type deviceIndex = mapping[j];
         data = data*dt+(*globalDeviceSolutionOld)[deviceIndex]-x[deviceIndex];
         int lclerr = f.ReplaceGlobalValues(1, &data, &deviceIndex);
         if (lclerr != 0) {
           Ostr << "Error copying solution from Vector to MultiVector" << std::endl;
           StdOut(Ostr.str());
           return(lclerr);
         }
       }
     }
 */
 /*
    std::cout << "In TransientSolverInterface, after  transfer to global storage\n";
    std::cout << "Printing Solution in GlobalDeviceSolution\n";
    pDevice->globalDeviceSolution->Print(std::cout);
 */
   }
void TransientSolver ()
Wrapper for our transient solver.
Definition at line 150 of file Solver.cpp.
References ICED::HalfCell::backwardEuler, ICED::HalfCell::forwardEuler, SolverInterface::pDevice, TransientSolverInterface::TransientBackwardEuler(), and TransientSolverInterface::TransientForwardEuler().
{
     FunctionEntry("TransientSolver");
     //double totalTime = 0.;
     //int iter = 0;
     std::ostringstream Ostr;
     Ostr << "Finding transient solution\n";
     while (pDevice->currentTime + pDevice->dt < pDevice->maxTime) {
       pDevice->currentTime += pDevice->dt;
       pDevice->currentIteration++;
       //Ostr << "Iteration " << pDevice->currentIteration
       std::cout << "Iteration " << pDevice->currentIteration
                 << " Total Simulation Time " << pDevice->currentTime
                 << " seconds" <<  std::endl;
       if (pDevice->transientSolver == forwardEuler)
         TransientForwardEuler();
       else if (pDevice->transientSolver == backwardEuler)
         TransientBackwardEuler();
       else
         Ostr << "FAIL!!!" << std::endl;
 /*
       std::cout << "Printing Solution in EpetraVector\n";
       pDevice->pSolutionData->solutionEpetra->Print(std::cout);
       std::cout << "Printing Solution in GlobalDeviceSolution\n";
       pDevice->globalDeviceSolution->Print(std::cout);
 */
       // write simulation output files
       if (pDevice->currentIteration % pDevice->dumpInterval == 0)
         pDevice->DumpSolution(pDevice->currentTime);
     }
     StdOut(Ostr.str());
     FunctionExit("TransientSolver");
   }
The documentation for this class was generated from the following files:
Solver.hpp
Solver.cpp