ICED_Physics: ActivityCoefficient Class Reference
ActivityCoefficient Class Reference
Physics module for activity coefficient of species i .
Detailed Description
Physics module for activity coefficient of species i .
Definition at line 1144 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
ActivityCoefficient ()
Default constructor.
ActivityCoefficient (SolutionData *solutionData, GlobalType &globin)
~ActivityCoefficient ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Solver for Activity Coefficient.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
ActivityCoefficient () inline
Default constructor.
Definition at line 1151 of file PhysicsModule.hpp.
References OhmsLawElectrolyte::Initialize().
 {Initialize();};
ActivityCoefficient (SolutionData * solutionData, GlobalType & globin) inline
Definition at line 1156 of file PhysicsModule.hpp.
References ActivityCoefficient::Initialize().
                                                                         : PhysicsModule(solutionData, globin) {
       ActivityCoefficient::Initialize();
     };
~ActivityCoefficient () inline
Default destructor.
Definition at line 1163 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 1172 of file PhysicsModule.hpp.
References PhysicsModule::idealParameters, PhysicsModule::moduleName, ICED::HalfCell::solutionVariable_t_MAX, and PhysicsModule::variableIndex.
Referenced by ActivityCoefficient::ActivityCoefficient().
                       {
       moduleName="ActivityCoefficient";
       SetName(moduleName);
       variableIndex=solutionVariable_t_MAX;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("activityCoefficients","2"));
     };
void SolvePhysics () virtual
Solver for Activity Coefficient.
The activity coefficient is a dimensionless quantity, dependent on temperature, pressure, and solution composition, that scales the chemical potential to account for solution non-ideality. The ActivityCoefficient SolvePhysics function is a submodule that solves for the mean molar activity coefficient of a binary electrolyte based on the concentration of the electrolyte . The current implementation assumes a 4th-order polynomial for the activity coefficient, but other functions could be added. The coefficients of the polynomial are read from the input file(s).
where and are constants. The constants are expressed in the function below in the vector pActivityCoeff starting with the 0th index.
The coefficient is used when dealing with the electrolytic current used in modules such as OhmsLawElectrolyte.
Todo:
Consider modifying ActivityCoefficient SolvePhysics function to be P and T dependent. Since it is a dimensionless quantity and in one of the governing equations, we take the natural log (not sure how it could depend on concentration).
Implements PhysicsModule.
Definition at line 20 of file ActivityCoefficient.cpp.
References SolutionData::activityCoefficient, SolutionData::activityCoefficientDer, SolutionData::activityCoefficientDerDer, SolutionData::activityCoefficientDerDerDer, SolutionData::activityCoefficients, ICED::HalfCell::conc_e, SolutionData::iEndInternal, SolutionData::iStartInternal, PhysicsModule::pSolutionData, and SolutionData::solutionData.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     //Ostr << "Hello from SolvePhysics" << std::endl;
     //int numNodes = pSolutionData->numNodes;
     int iStartIn = pSolutionData->iStartInternal-1;
     int iEndIn = pSolutionData->iEndInternal+1;
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     std::vector<double>* pActivityCoeff = &pSolutionData->activityCoefficients;
     Ostr << "coefficients for function to calculate activity coefficient:"
          << std::endl;
     Ostr << "pActivityCoeff->size() = " << pActivityCoeff->size() << std::endl;
     for(int i= 0; i<5; ++i){
         Ostr << (*pActivityCoeff)[i] << std::endl;
     }
     // Quartic function for the activity coefficient as a function of conc_e
     // ax^4 + bx^3 + cx^2 + dx + e
     // a*conc_e^4 + b*conc_e^3 + c*conc_e^2 + d*conc_e + e
     for(int i= iStartIn; i<=iEndIn; ++i){
       pSolutionData->activityCoefficient[i] = (*pActivityCoeff)[0]*(*pSolution)[i][conc_e] *
            (*pSolution)[i][conc_e]*(*pSolution)[i][conc_e]*(*pSolution)[i][conc_e] +
            (*pActivityCoeff)[1]*(*pSolution)[i][conc_e]*(*pSolution)[i][conc_e] *
            (*pSolution)[i][conc_e] + (*pActivityCoeff)[2]*(*pSolution)[i][conc_e] *
            (*pSolution)[i][conc_e] + (*pActivityCoeff)[3]*(*pSolution)[i][conc_e] +
            (*pActivityCoeff)[4];
       Ostr << std::setprecision(15) << "activityCoefficient[" << i << "] = "
            << pSolutionData->activityCoefficient[i] << std::endl;
       pSolutionData->activityCoefficientDer[i] =
            4*(*pActivityCoeff)[0]*(*pSolution)[i][conc_e] *
            (*pSolution)[i][conc_e]*(*pSolution)[i][conc_e] + 3*(*pActivityCoeff)[1] *
            (*pSolution)[i][conc_e]*(*pSolution)[i][conc_e]+2*(*pActivityCoeff)[2] *
            (*pSolution)[i][conc_e]+(*pActivityCoeff)[3];
       Ostr << std::setprecision(15) << "activityCoefficientDer[" << i << "] = "
            << pSolutionData->activityCoefficientDer[i] << std::endl;
       pSolutionData->activityCoefficientDerDer[i] = 12*(*pActivityCoeff)[0] *
            (*pSolution)[i][conc_e]*(*pSolution)[i][conc_e] + 6*(*pActivityCoeff)[1] *
            (*pSolution)[i][conc_e] + 2*(*pActivityCoeff)[2];
       Ostr << std::setprecision(15) << "activityCoefficientDerDer[" << i << "] = "
            << pSolutionData->activityCoefficientDerDer[i] << std::endl;
       pSolutionData->activityCoefficientDerDerDer[i] = 24*(*pActivityCoeff)[0] *
            (*pSolution)[i][conc_e] + 6*(*pActivityCoeff)[1];
       Ostr << std::setprecision(15) << "activityCoefficientDerDerDer[" << i << "] = "
            << pSolutionData->activityCoefficientDerDerDer[i] << std::endl;
     }
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
The documentation for this class was generated from the following files:
PhysicsModule.hpp
ActivityCoefficient.cpp