ICED_Physics: WallFlux Class Reference
WallFlux Class Reference
Physics module for Wall Flux.
Detailed Description
Physics module for Wall Flux.
Definition at line 561 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
WallFlux ()
Default constructor.
WallFlux (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~WallFlux ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Physics solution for Wall Flux.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
WallFlux () inline
Default constructor.
Definition at line 568 of file PhysicsModule.hpp.
References WallFlux::Initialize().
 {Initialize();};
WallFlux (SolutionData * solutionData, GlobalType & globin) inline
Constructor for solution data and global object.
Definition at line 573 of file PhysicsModule.hpp.
References WallFlux::Initialize().
                                                              : PhysicsModule(solutionData, globin) {
       WallFlux::Initialize();
     };
~WallFlux () inline
Default destructor.
Definition at line 580 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 589 of file PhysicsModule.hpp.
References ICED::HalfCell::conc_e, PhysicsModule::idealParameters, PhysicsModule::moduleName, and PhysicsModule::variableIndex.
Referenced by WallFlux::WallFlux().
                       {
       moduleName="WallFlux";
       SetName(moduleName);
       variableIndex=conc_e;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numberOfIons","6"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("TransferenceNumber","1"));
     };
void SolvePhysics () virtual
Physics solution for Wall Flux.
The discrete equation for the diffusion of Li ions in the electrolyte is (summation of Diffusion + IonMigration + WallFlux):
From here, the basic pore wall flux equation is motivated to give: where and are constants represented by the variables surfaceAreaA and numberOfIons respectively.
is the TransferenceNumber (represented by transferenceNumber) and the WallFlux is one of the unknown variables solved in this module (represented by wallFluxJ(numNodes)).
Discretizing the equation above where the values of and are considered gives us the discrete equation:
where the wall flux function values are summed into the function defined by fkn(numNodes).
There exists a function for every node in the discretization space for a temporal discretization point and a spatial discretization point . These functions and their Jacobian matrices must be calculated by the module implementing the wall flux component.
The non-zero entries calculated are:
where is the partial TransferenceNumber (represented by transferenceNumberP) and calculated in IonMigration.
Implements PhysicsModule.
Definition at line 19 of file WallFlux.cpp.
References ICED::HalfCell::conc_e, SolutionData::electrolyteVolumeFraction, SolutionData::function, SolutionData::iStartInternal, SolutionData::jacobian, SolutionData::numberOfIons, SolutionData::numGhostNodes, SolutionData::numNodes, SolutionData::poreRadius, PhysicsModule::pSolutionData, SolutionData::solutionData, SolutionData::transferenceNumber, SolutionData::transferenceNumberDer, ICED::HalfCell::wallFlux, SolutionData::xMax, and SolutionData::xMin.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     Ostr << "Hello from SolvePhysics" << std::endl;
     //const double surfaceAreaA = pSolutionData->surfaceArea; // a
     double surfaceAreaA;
     if (pSolutionData->electrolyteVolumeFraction < 0.99) {
       surfaceAreaA = 3*(pSolutionData->xMax - pSolutionData->xMin)*
       //surfaceAreaA = 3*
                        (1-pSolutionData->electrolyteVolumeFraction)/
                        pSolutionData->poreRadius/
                        (pSolutionData->numNodes-2*pSolutionData->numGhostNodes);
     } else {
       surfaceAreaA = 0;
     }
     const double numberOfIons = pSolutionData->numberOfIons; // nu_i
     int numNodes = pSolutionData->numNodes;
     int iStartIn = pSolutionData->iStartInternal-1;
     int iEndIn = pSolutionData-> iEndInternal+1;
     Ostr << "surfaceAreaA = " << surfaceAreaA << std::endl;
     Ostr << "numberOfIons = " << numberOfIons << std::endl;
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     std::vector<double> *transferenceNumber; // t^{0}_{i}
     std::vector<double> *transferenceNumberP; // t'^{0}_{in}
     std::vector<double> wallFluxJ(numNodes); // j_{in}
     std::vector<double> fkn(numNodes); // f_{kn}
     transferenceNumber = &pSolutionData->transferenceNumber;
     transferenceNumberP = &pSolutionData->transferenceNumberDer;
     // wall flux of species i
     Ostr << "wallFlux = ";
     for(int i = iStartIn; i <= iEndIn; i++){
       wallFluxJ[i] = (*pSolution)[i][wallFlux];
       //Ostr << wallFluxJ[i] << " ";
     }
     Ostr << std::endl;
 /*
     Ostr << "transferenceNumber = ";
     for(int i = iStartIn; i <= iEndIn; i++){
       Ostr << (*transferenceNumber)[i] << " ";
     }
     Ostr << std::endl;
 */
     //Sum the wall flux function values into the function
     //for  Diffusion + ion migration + wallflux
     for(int i = iStartIn; i <= iEndIn; i++){
       // factor for surface area at nodes
       double fac;
       if (i == iStartIn || i == iEndIn)
         fac=0.5;
       else
         fac = 1.0;
       fkn[i] = fac*surfaceAreaA * wallFluxJ[i] * (1-(*transferenceNumber)[i]) / numberOfIons;
       (*pSolutionData->function)[i][conc_e] += fkn[i]/
         pSolutionData->electrolyteVolumeFraction;
       Ostr << "computed Wall Flux Function = " <<
       fkn[i] << std::endl;
     }
     // Jacobian values
     for(int i = iStartIn; i <= iEndIn; i++){
       // (partial f_kn) / (partial jin_kn)
       (*pSolutionData->jacobian)[i][i][conc_e][wallFlux] = surfaceAreaA *
            (1 - (*transferenceNumber)[i]) / numberOfIons;
       // (partial f_kn) / (partial c_kn)
       (*pSolutionData->jacobian)[i][i][conc_e][conc_e] = -surfaceAreaA *
            wallFluxJ[i] * (*transferenceNumberP)[i] / numberOfIons;
     }
     Ostr << std::endl;
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
The documentation for this class was generated from the following files:
PhysicsModule.hpp
WallFlux.cpp