ICED_Physics: ICED::TestingObject::Test__OhmsLawSolid
void Test__OhmsLawSolid (ResultsType & result) inline
Test for ICED::OhmsLawSolid.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of the OhmsLawSolid module.
This function initializes the input data values for the simulation.It then calls the OhmsLawSolid class SolvePhysics. Finally it verifies that SolvePhysics populates the function and Jacobian vector with the correct values
Definition at line 4550 of file ICEDTest.H.
References DeviceData::BuildDevice(), DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, TestingObject< ResultsType >::pDeviceData, ICED::HalfCell::phi_s, and ICED::HalfCell::wallFlux.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__OhmsLawSolid" << std::endl;
       bool works=true;
       int build_error;
       // Set variables usually assigned from pSolutionData
       int numNodes=6; // numNodes
       double faraday=9.64854, solCon=0.001; // faradayConstant and solidConductivity
       double volumeFraction = 0.5; // electrolyteVolumeFraction
       std::vector<double> phisCoeff(3);
       std::vector<double> jnCoeff(3);
       std::vector<double> phis(numNodes+2);
       std::vector<double> jn(numNodes+2);
       std::vector<double> x(numNodes+2);
       double dx;
       std::stringstream ss;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       //device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ecdc1","firstComponent component1.inp"));
       ss.clear();
       ss.str("");
       ss << numNodes;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numNodes", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMin", "-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMax", "2"));
       ss.clear();
       ss.str("");
       ss << faraday;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("faradayConstant", ss.str()));
       ss.clear();
       ss.str("");
       ss << solCon;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("solidConductivity", ss.str()));
 /*
       ss.clear();
       ss.str("");
       ss << As;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("surfaceAreaA", ss.str()));
 */
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("OhmsLawSolid","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("electrolyteVolumeFraction","0.5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("poreRadius","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("bruggemanCoefficient","1"));
       //build_error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       //if (build_error != 0)
       //  works=false;
       // build the device
       bool builds=false;
       build_error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (build_error == 0)
         builds=true;
       result.UpdateResult("OhmsLawSolid:Builds",builds);
       //Get x values for the nodes
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->xCoords;
       dx = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
          ->pSolutionData->dx;
       int iStartIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       // set phi_e values to 5.1x^2 - 4.2x + 3.7
       phisCoeff[0] =  5.1;
       phisCoeff[1] = -4.2;
       phisCoeff[2] =  3.7;
       // Generate parabola
       GenerateParabolicFunction(phis, x, phisCoeff, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output (Phi)  "
              << phis[i] << std::endl;
       }
       //Initialize values for phi_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::phi_s]
             =phis[i];
       }
       // set wallFlux values to 8.7x^2 + 3.1x - 5.4
       jnCoeff[0] =  8.7;
       jnCoeff[1] =  3.1;
       jnCoeff[2] = -5.4;
       // Generate parabola
       GenerateParabolicFunction(jn, x, jnCoeff, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output (WallFlux)  "
              << jn[i] << std::endl;
       }
       //Initialize values for wallFlux as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::wallFlux]
             =jn[i];
       }
       //Call OhmsLawSolid SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
                    SolvePhysics();
       // solve the ohms law function with the values provided above
       std::vector<double> exactOhmsSol(numNodes+2);
       double As = 0.375; // calculated from pore radius above
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         // If the node i exists at a component boundary, then surfaceAreaA (As) is half (to avoid double counting).
         if (i == iStartIn-1 || i == iEndIn+1){
            exactOhmsSol[i] = volumeFraction*solCon*(phis[i+1]-2*phis[i]+phis[i-1])/(dx*dx)
                            - (0.5*As*jn[i]*faraday);
         }
         // Otherwise the node is internal to the component, and the full area should be used.
         else{
            exactOhmsSol[i] = volumeFraction*solCon*(phis[i+1]-2*phis[i]+phis[i-1])/(dx*dx)
                            - (As*jn[i]*faraday);
         }
         std::cout << "Test Solution = " << exactOhmsSol[i] << std::endl;
         std::cout << "Computed Soln = " << (*pDeviceData->deviceComponents[0]->
           componentPhysicsModules[0]->pSolutionData->function)[i][ICED::HalfCell::phi_s] << std::endl;
         //Check that the exact answer and the computed answer are within 1.0e-8 tolerance.
         if(fabs(exactOhmsSol[i] - (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->function)[i][ICED::HalfCell::phi_s]) > 1.0e-8 ){
             works = false;
             std::cout << "FAILS in Ohms Solid function" << std::endl;
         }
       }
 /*
       // Check the jacobians
       double value1, value2, value3;
       //Print out and check the Jacobian for phi_s
       std::cout << std::endl << "Jacobian phi_s (tridiagonal):" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i-1][ICED::HalfCell::phi_s]
            [ICED::HalfCell::phi_s] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][ICED::HalfCell::phi_s]
            [ICED::HalfCell::phi_s] << " ";
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i+1][ICED::HalfCell::phi_s]
            [ICED::HalfCell::phi_s] << std::endl;
       }
       //check diagonal-1 for first node
       value1 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn][iStartIn-1][ICED::HalfCell::phi_s]
         [ICED::HalfCell::phi_s];
       //check diagonal for second node
       value2 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][ICED::HalfCell::phi_s]
         [ICED::HalfCell::phi_s];
       //check diagonal+1 for third node
       value3 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+2][iStartIn+3][ICED::HalfCell::phi_s]
         [ICED::HalfCell::phi_s];
       if(fabs(value1 - 0.00277777777777778) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_s Jacobian 1" << std::endl;
       }
       if(fabs(value2 + 0.00555555555555556) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_s Jacobian 2" << std::endl;
       }
       if(fabs(value3 - 0.00277777777777778) > 1.0e-8){
         works = false;
         std::cout << "Fails in phi_s Jacobian 3" << std::endl;
       }
       //Check & print out the Jacobian for wallFlux
       std::cout << std::endl << "Jacobian wallFlux (diagonal):" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
          std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[i][i][ICED::HalfCell::phi_s]
            [ICED::HalfCell::wallFlux] << std::endl;
       }
       value2 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
         ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][ICED::HalfCell::phi_s]
         [ICED::HalfCell::wallFlux];
       if(fabs(value2 + 154.37664) > 1.0e-8){
         works = false;
         std::cout << "Fails in wallFlux Jacobian 1" << std::endl;
       }
 */
       result.UpdateResult("OhmsLawSolid:Works",works);
       delete pDeviceData;
     }