ICED_Physics: OhmsLawSolid Class Reference
OhmsLawSolid Class Reference
Physics module for Ohms Law in the solid phase.
Detailed Description
Physics module for Ohms Law in the solid phase.
Definition at line 822 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
OhmsLawSolid ()
Default constructor.
OhmsLawSolid (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~OhmsLawSolid ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Physics solution.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
OhmsLawSolid () inline
Default constructor.
Definition at line 829 of file PhysicsModule.hpp.
References OhmsLawElectrolyte::Initialize().
 {Initialize();};
OhmsLawSolid (SolutionData * solutionData, GlobalType & globin) inline
Constructor for solution data and global object.
Definition at line 834 of file PhysicsModule.hpp.
References OhmsLawSolid::Initialize().
                                                                  :
          PhysicsModule(solutionData, globin) {
       OhmsLawSolid::Initialize();
     };
~OhmsLawSolid () inline
Default destructor.
Definition at line 842 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 851 of file PhysicsModule.hpp.
References PhysicsModule::idealParameters, PhysicsModule::moduleName, ICED::HalfCell::phi_s, and PhysicsModule::variableIndex.
Referenced by OhmsLawSolid::OhmsLawSolid().
                       {
       moduleName="OhmsLawSolid";
       SetName(moduleName);
       variableIndex=phi_s;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","0"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("poreRadius","1"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","2"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","3"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("electrolyteVolumeFraction","4"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("faradayConstant","5"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("solidConductivity","6"));
     };
void SolvePhysics () virtual
Physics solution.
When considering electron transfer at the interface between the electrode and the electrolyte, the driving force for the flow of the electrons is the electric field which is the same as the migration term for ionic conduction. Both are governed by Ohm's Law. Ohm's law for the solid phase is given by
where is the electronic conductivity of the solid matrix in and is the electic potential in . The ButlerVolmer module relates the currents for the solid and electrolyte (and). Also note that the IonMigration module relates and ionic conductivity (used in).
For a solid, Ohm's Law is reinterpreted in one-dimension and used at every node in the mesh populating the Jacobian matrices. The function to populate this module is as follows:
The constants, are represented by variables sigma, As, faraday, respectively, in the function below. are the surface area of the pore walls per unit volume of the total electrode (in) and Faraday's constant (in), respectively. The module will solve for the pore wall flux of species averaged over the surface area (see the WallFlux module) as well as .
Using the central difference method (allowing discretization), the function is rewritten as
where is the function for every node in the discretization space. represents the electric potential at the temporal discretization point and spatial discretization point . Also note
where is an N-dimensional argument taken by .
Here and are represented by the vectors ohmsLawSolid(numNodes) and wallFluxVar(numNodes) respectively.
and their Jacobian matrices must be calculated by the function implementing Ohm's Law for the solid phase. The function itself calculated the non-zero entries for non-uniform meshes where:
And the calculated non-zero Jacobian Entries are:
Also note that and are represented by the variables dxr and dxl respectively in the function below as well.
Implements PhysicsModule.
Definition at line 19 of file OhmsLawSolid.cpp.
References SolutionData::dx, SolutionData::electrolyteVolumeFraction, SolutionData::faradayConstant, SolutionData::function, SolutionData::iStartInternal, SolutionData::jacobian, SolutionData::numGhostNodes, SolutionData::numNodes, ICED::HalfCell::phi_s, SolutionData::poreRadius, PhysicsModule::pSolutionData, SolutionData::solidConductivity, SolutionData::solutionData, ICED::HalfCell::wallFlux, SolutionData::xCoords, SolutionData::xMax, and SolutionData::xMin.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     Ostr << "Hello from SolvePhysics" << std::endl;
     double faraday = pSolutionData->faradayConstant;
     double sigma = pSolutionData->solidConductivity;
     // modify sigma, taking into accout the electrolyte volume fraction
     double factor = (1-pSolutionData->electrolyteVolumeFraction);
     sigma *= factor;
     //const double As = pSolutionData->surfaceAreaA;
     //const double As = 4*pSolutionData->PI*pSolutionData->poreRadius*
                         //pSolutionData->poreRadius;
     //const double As = pSolutionData->surfaceArea;
     double As;
     if (pSolutionData->electrolyteVolumeFraction < 0.99) {
       As = 3*(pSolutionData->xMax - pSolutionData->xMin)*
       //As = 3*
              (1-pSolutionData->electrolyteVolumeFraction)/
              pSolutionData->poreRadius/
              (pSolutionData->numNodes-2*pSolutionData->numGhostNodes);
     } else {
       As = 0;
     }
     const int iStartIn = pSolutionData->iStartInternal-1;
     const int iEndIn = pSolutionData-> iEndInternal+1;
     const int numNodes = pSolutionData->numNodes;
     double dx = pSolutionData->dx;
     std::vector<double> ohmsLawSolid(numNodes); // fkn
     std::vector<double> wallFluxVar(numNodes); // jnkn
     std::vector<double> diffElecPotential(numNodes); // Electric potential diff
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     double dxl = dx;
     double dxr = dx;
     for(int i = iStartIn; i<= iEndIn; i++){
       // set dxl,dxr at boundary nodes
       if (i == iStartIn)
         dxl = pSolutionData->xCoords[iStartIn]-pSolutionData->xCoords[iStartIn-1];
       else if (i == iEndIn)
         dxr = pSolutionData->xCoords[iEndIn+1]-pSolutionData->xCoords[iEndIn];
       // Solve the OhmsLawSolid function
       diffElecPotential[i]=((*pSolution)[i+1][phi_s]-(*pSolution)[i][phi_s])*(1+dxl/dxr)+
                            ((*pSolution)[i-1][phi_s]-(*pSolution)[i][phi_s])*(1+dxr/dxl);
       wallFluxVar[i]=(*pSolution)[i][wallFlux];
       // factor for surface area at nodes
       double fac;
       if (i == iStartIn || i == iEndIn)
         fac=0.5;
       else
         fac = 1.0;
       ohmsLawSolid[i]=2*sigma*diffElecPotential[i]/(dxl+dxr)/(dxl+dxr)-
        fac*(As*wallFluxVar[i]*faraday);
       (*pSolutionData->function)[i][phi_s] = ohmsLawSolid[i];
       Ostr << "Computed Ohms Law Solid Function " << ohmsLawSolid[i] << std::endl;
       // Compute the non-zero jacobians
       //
       // j_n^0 = \partial fkn/ partial phikn
       (*pSolutionData->jacobian)[i][i][phi_s][phi_s]=-2*sigma*(2+dxr/dxl+dxl/dxr)/
                                                  (dxl+dxr)/(dxl+dxr);
       // j_n^- = \partial fkn/ partial phik(n-1)
       (*pSolutionData->jacobian)[i][i-1][phi_s][phi_s]=2*sigma*(1+dxr/dxl)/
                                                    (dxl+dxr)/(dxl+dxr);
       // j_n^+ = \partial fkn/ partial phik(n+1)
       (*pSolutionData->jacobian)[i][i+1][phi_s][phi_s]=2*sigma*(1+dxl/dxr)/
                                                    (dxl+dxr)/(dxl+dxr);
       // j_{jn} = \partial fkn/ partial jnkn
       (*pSolutionData->jacobian)[i][i][wallFlux][wallFlux]=-As*faraday;
       // reset dxl for interior nodes
       if (i == iStartIn)
         dxl = pSolutionData->dx;
     }
     Ostr << std::endl;
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
The documentation for this class was generated from the following files:
PhysicsModule.hpp
OhmsLawSolid.cpp