ICED_Physics: ICED::TestingObject::RunTest
virtual void RunTest (const std::string & name, ResultsType & result) inline virtual
Runs a test specified by name.
Parameters
name String name of the test to run.
result ICED::TestResults object to store test results.
Definition at line 6049 of file ICEDTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ActivityCoefficient(), TestingObject< ResultsType >::Test__ButlerVolmer(), TestingObject< ResultsType >::Test__ComponentBoundaryConditions(), TestingObject< ResultsType >::Test__ConcentrationDiffusion(), TestingObject< ResultsType >::Test__DeviceData(), TestingObject< ResultsType >::Test__DeviceDataMapping(), TestingObject< ResultsType >::Test__Diffusion(), TestingObject< ResultsType >::Test__Intercalation(), TestingObject< ResultsType >::Test__IonMigration(), TestingObject< ResultsType >::Test__ModulePriority(), TestingObject< ResultsType >::Test__OhmsLawElectrolyte(), TestingObject< ResultsType >::Test__OhmsLawSolid(), TestingObject< ResultsType >::Test__SolverBE(), TestingObject< ResultsType >::Test__SolverBENL(), TestingObject< ResultsType >::Test__SolverButlerVolmer(), TestingObject< ResultsType >::Test__SolverFE(), TestingObject< ResultsType >::Test__SolverIntercalation(), TestingObject< ResultsType >::Test__SolverOhmsLawElectrolyte(), TestingObject< ResultsType >::Test__SolverOhmsLawSolid(), TestingObject< ResultsType >::Test__SteadySolver(), TestingObject< ResultsType >::Test__SteadySolverNL(), TestingObject< ResultsType >::Test__TransferenceNumber(), TestingObject< ResultsType >::Test__UnsteadySolver(), and TestingObject< ResultsType >::Test__WallFlux().
Referenced by TestingObject< ResultsType >::ProcessTests(), and ICED::Test().
     {
       Prologue();
       if(name == "DeviceData")
         Test__DeviceData(result);
       else if (name == "DeviceDataMapping")
         Test__DeviceDataMapping(result);
       else if (name == "ModulePriority")
         Test__ModulePriority(result);
       else if (name == "ComponentBoundaryConditions")
         Test__ComponentBoundaryConditions(result);
       else if (name == "ButlerVolmer")
         Test__ButlerVolmer(result);
       else if (name == "WallFlux")
         Test__WallFlux(result);
       else if (name == "Diffusion")
         Test__Diffusion(result);
       else if (name == "TransferenceNumber")
         Test__TransferenceNumber(result);
       else if (name == "ConcentrationDiffusion")
         Test__ConcentrationDiffusion(result);
       else if (name == "OhmsLawElectrolyte")
         Test__OhmsLawElectrolyte(result);
       else if (name == "OhmsLawSolid")
         Test__OhmsLawSolid(result);
       else if (name == "Intercalation")
         Test__Intercalation(result);
       else if (name == "ActivityCoefficient")
         Test__ActivityCoefficient(result);
       else if (name == "IonMigration")
         Test__IonMigration(result);
       else if (name == "SteadySolver")
         Test__SteadySolver(result);
       else if (name == "SteadySolverNL")
         Test__SteadySolverNL(result);
       else if (name == "SolverForwardEuler")
         Test__SolverFE(result);
       else if (name == "SolverBackwardEuler")
         Test__SolverBE(result);
       else if (name == "SolverBackwardEulerNL")
         Test__SolverBENL(result);
       else if (name == "SolverOhmsLawSolid")
         Test__SolverOhmsLawSolid(result);
       else if (name == "SolverOhmsLawElectrolyte")
         Test__SolverOhmsLawElectrolyte(result);
       else if (name == "SolverButlerVolmer")
         Test__SolverButlerVolmer(result);
       else if (name == "SolverIntercalation")
         Test__SolverIntercalation(result);
       else if (name == "UnsteadySolver")
         Test__UnsteadySolver(result);
       Epilogue();
     }