ICED_Physics: ICED::TestingObject::Test__Diffusion
void Test__Diffusion (ResultsType & result) inline
Test for ICED::Diffusion module.
Parameters
result ICED::TestResults object to store test results.
This function implements a simple test of the diffusion module.
This function initializes the input data values for the simulation, and then calls another function that initializes the test fixtrue solution data object. It then calls the Diffusion class SolvePhysics. Finally it verifies that SolvePhysics populates the function and Jacobian vector with the correct values
Definition at line 4139 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, and TestingObject< ResultsType >::pDeviceData.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__Diffusion" << std::endl;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int build_error;
       int numNodes=10;
       std::vector<double> diffCoeff(3);
       std::vector<double> solution(numNodes+2);
       std::vector<double> diff(numNodes+2);
       std::vector<double> diffDer(numNodes+2);
       std::vector<double> diffDerDer(numNodes+2);
       std::vector<double> coefficient(3);
       std::vector<double> x(numNodes+2);
       std::stringstream ss;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       diffCoeff[0] = 5.1;
       diffCoeff[1] = 4.0;
       diffCoeff[2] = -2.1;
       //device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ecdc1","firstComponent component1.inp"));
       // component1 parameters
       ss.clear();
       ss.str("");
       ss << numNodes;
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numNodes", ss.str()));
       ss.clear();
       ss.str("");
       ss << diffCoeff[0] << " " << diffCoeff[1] << " " << diffCoeff[2];
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("concentrationDiffusionCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMin", "0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMax", "2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ConcentrationDiffusion","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("Diffusion","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("electrolyteVolumeFraction","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("bruggemanCoefficient","0"));
       //build_error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       //if (build_error != 0)
         //works=false;
       // build the device
       bool builds=false;
       build_error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (build_error == 0)
         builds=true;
       result.UpdateResult("Diffusion:Builds",builds);
       int iStartIn = pDeviceData->deviceComponents[0]
           ->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       //Get x values for the nodes
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
           ->pSolutionData->xCoords;
       // set conc_e values to -0.2x^2 + 0.72x - 3.1
       coefficient[0] = -0.2;
       coefficient[1] = 0.72;
       coefficient[2] = -3.1;
       // Generate parabola
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  "
              << solution[i] << std::endl;
       }
       //Initialize values for conc_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]
             =solution[i];
       }
       //Call ConcentrationDiffusion SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       //Call Diffusion SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[1]->
          SolvePhysics();
       double value1, value2, value3;
       std::vector<double> exact(numNodes+2);
       //Exact diffusion calculation (using derivatives of the
       //parabolas and the exact diffusion function
       std::cout << "Exact Diffusion:" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
         std::cout << "c = " << solution[i] << " ";
         std::cout << "x = " << x[i] << " ";
         std::cout << "diffCoeff[0] = " << diffCoeff[0] << " ";
         std::cout << "diffCoeff[1] = " << diffCoeff[1] << " ";
         std::cout << "diffCoeff[2] = " << diffCoeff[2] << " ";
         value1 = diffCoeff[0]*solution[i]*solution[i]
                + diffCoeff[1]*solution[i] + diffCoeff[2];
         std::cout << "value1 = " << value1 << std::endl;
         value1 *= coefficient[0]*2.0;
         value2 = diffCoeff[0]*2.0*solution[i] + diffCoeff[1];
         value2 *= (2.0*coefficient[0]*x[i] + coefficient[1]);
         value2 *= (2.0*coefficient[0]*x[i] + coefficient[1]);
         value1 += value2;
         std::cout <<  "exact = " << value1 << std::endl;
         exact[i] = value1;
       }
       double error=0;
       //Check Diffusion computation
       std::cout << "Diffusion:" << std::endl;;
       for(int i=iStartIn; i<=iEndIn; i++){
         std::cout << (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              function)[i][HalfCell::conc_e] << std::endl;
         std::cout << "exact = " << exact[i] << std::endl;
         error += (fabs(exact[i] - (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              function)[i][HalfCell::conc_e]))*
              (fabs(exact[i] - (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              function)[i][HalfCell::conc_e]));
         std::cout << "node error = "
              << (fabs(exact[i]- (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->
              function)[i][HalfCell::conc_e])) << std::endl;
       }
       error = sqrt(error);
       if(error > 1.0e-10){
         works = false;
         std::cout << "Fails in Diffusion function check" << std::endl;
       }
       std::cout << "dx = " << pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->dx << std::endl;
       std::cout << "error = " << error << std::endl;
       std::cout << std::endl;
       //Check Jacobian
       std::cout << "Jacobian:" << std::endl;
       for(int i=iStartIn; i<=iEndIn; i++){
         std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->jacobian)[i][i-1][0][ICED::HalfCell::conc_e] << " ";
         std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->jacobian)[i][i][0][ICED::HalfCell::conc_e] << " ";
         std::cout << (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->jacobian)[i][i+1][0][ICED::HalfCell::conc_e]
              << std::endl;
       }
       //Get off diagonal (-1) entry for first node
       value1 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[iStartIn][iStartIn-1][0]
            [ICED::HalfCell::conc_e];
       //Get diagonal entry for second node
       value2 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[iStartIn+1][iStartIn+1][0]
            [ICED::HalfCell::conc_e];
       //Get off diagonal (+1) entry for third node
       value3 = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[iStartIn+2][iStartIn+3][0]
            [ICED::HalfCell::conc_e];
       //Verify those entries of the Jacobian
       if(fabs(value1 - 691.302487777778) > 1.0e-8){
         works = false;
         std::cout << "Fails in Diffusion Jacobian check" << std::endl;
       }
       if(fabs(value2 + 1100.18299037037) > 1.0e-8){
         works = false;
         std::cout << "Fails in Diffusion Jacobian check" << std::endl;
       }
       if(fabs(value3 - 447.68855) > 1.0e-8){
         works = false;
         std::cout << "Fails in Diffusion Jacobian check" << std::endl;
       }
       std::cout << std::endl;
       result.UpdateResult("Diffusion:Works",works);
       delete pDeviceData;
     }