ICED_Physics: electronMigration Class Reference
electronMigration Class Reference
Physics module for electron migration.
Detailed Description
Physics module for electron migration.
Definition at line 294 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
electronMigration ()
Default constructor.
electronMigration (SolutionData *solutionData, GlobalType &globin)
~electronMigration ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Physics solution.
void ApplyDirichletBC (int position)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position)
Application of Neumann boundary conditions.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
electronMigration () inline
Default constructor.
Definition at line 301 of file PhysicsModule.hpp.
References electronMigration::Initialize().
 {Initialize();};
electronMigration (SolutionData * solutionData, GlobalType & globin) inline
Definition at line 306 of file PhysicsModule.hpp.
References electronMigration::Initialize().
                                                                       : PhysicsModule(solutionData, globin) {
       electronMigration::Initialize();
     };
~electronMigration () inline
Default destructor.
Definition at line 313 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void ApplyDirichletBC (int position) inline
Application of Dirichlet boundary conditions.
This provides an implementation of the Dirichlet boundary conditions for the physics module.
A Dirichlet boundary condition sets the value of a boundary node
Definition at line 363 of file PhysicsModule.hpp.
 {};
void ApplyNeumannBC (int position) inline
Application of Neumann boundary conditions.
This provides an implementation of the Neumann boundary conditions for the physics module.
A Neumann boundary condition sets the deriviative at a boundary node to a specified value.
Definition at line 374 of file PhysicsModule.hpp.
 {};
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 322 of file PhysicsModule.hpp.
References PhysicsModule::moduleName.
Referenced by electronMigration::electronMigration().
                       {
       SetName("electronMigration");
       moduleName="electronMigration";
     };
void SolvePhysics () inline virtual
Physics solution.
This provides a shell for the physics module implementation
Implements PhysicsModule.
Definition at line 332 of file PhysicsModule.hpp.
References PhysicsModule::pSolutionData, and SolutionData::temperature.
{
       FunctionEntry("SolvePhysics");
       std::ostringstream Ostr;
       Ostr << "Hello from solvePhysics" << std::endl;
       Ostr << "temperature " << pSolutionData->temperature << std::endl;
       StdOut(Ostr.str());
       FunctionExit("SolvePhysics");
     };
The documentation for this class was generated from the following file:
PhysicsModule.hpp