ICED_Physics: ICED::HalfCell::DeviceComponent::SolveComponent
int SolveComponent ()
Populate the component solution matricies.
Use the physics implemented by each module to fill the component level solution matricies. These are combined at the device level to compute a global solution.
InitializeComponent
ApplyComponentBC
module SolvePhysics
ApplyInternalBC
FinalizeComponent
Returns
int an error code
Test:
None
Todo:
Break this into ComputeF and ComputeJ to speed up non-linear solutions
Definition at line 439 of file DeviceComponent.cpp.
References DeviceComponent::ApplyComponentBC(), DeviceComponent::ApplyInternalBC(), DeviceComponent::componentPhysicsModules, DeviceComponent::FinalizeComponent(), and DeviceComponent::InitializeComponent().
{
       std::ostringstream Ostr;
       InitializeComponent();
       ApplyComponentBC();
 /*
       Ostr << "In device component " << componentName <<
                    ", before solve, printing Epetra x" << std::endl;
       pSolutionData->solutionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", before solve, printing  Epetra f" << std::endl;
       pSolutionData->functionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", before solve, printing Vector x" << std::endl;
       Ostr << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i) {
         Ostr << "\t \t";
         for (int j=0; j<solutionVariable_t_MAX; ++j) {
           Ostr << (*pSolutionData->solutionData)[i][j] << "\t \t";
         }
         Ostr << std::endl;
       }
       Ostr << "]" << std::endl;
       Ostr << "In device component " << componentName <<
                    ", before solve, printing  Vector f" << std::endl;
       Ostr << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         Ostr << (*pSolutionData->function)[i][2] << " ";
       Ostr << "]" << std::endl;
 */
       // loop over all modules and compute solutions
       for (size_t i=0; i<componentPhysicsModules.size(); ++i) {
         Ostr << "Solving Physics for module " <<
           componentPhysicsModules[i]->moduleName << std::endl;
         componentPhysicsModules[i]->SolvePhysics();
       }
       ApplyInternalBC();
       FinalizeComponent();
 /*
       Ostr << "In device component " << componentName <<
                    ", after solve, printing x" << std::endl;
       pSolutionData->solutionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", after solve, printing f" << std::endl;
       pSolutionData->functionEpetra->Print(Ostr);
       Ostr << "In device component " << componentName <<
                    ", after solve, printing Vector x" << std::endl;
       Ostr << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         Ostr << (*pSolutionData->solutionData)[i][2] << " ";
       Ostr << "]" << std::endl;
       Ostr << "In device component " << componentName <<
                    ", after solve, printing  Vector f" << std::endl;
       Ostr << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         Ostr << (*pSolutionData->function)[i][2] << " ";
       Ostr << "]" << std::endl;
 */
       StdOut(Ostr.str(),3);
       return 0;
     } // Function SolveComponent