ICED_Physics: ICED::TestingObject::Test__DeviceDataMapping
void Test__DeviceDataMapping (ResultsType & result) inline
Test for ICED::DeviceDataMapping.
Parameters
result ICED::TestResults object to store test results.
This function builds a DeviceData object and tests the mapping data generated by physics module at the component level to the device level. We scale that data and propagte back to the component level.
Input is specified via Parameter objects. A test module is loaded that sets solution data to be a simple list of numbers based on the temperature parameter. The results are compiled across all components.
Definition at line 428 of file ICEDTest.H.
References DeviceData::BuildDevice(), DeviceData::CopyDataFromComponents(), DeviceData::CopyDataToComponents(), DeviceData::deviceComponents, TestingObject< ResultsType >::global, SolutionData::iEndInternal, SolutionData::iStartInternal, SolutionData::numGhostNodes, SolutionData::numNodes, TestingObject< ResultsType >::pDeviceData, DeviceData::pSolutionData, SolutionData::solutionEpetra, SolutionData::temperature, and SolutionData::xCoords.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       Ostr.str("");
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(3);
       // device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1","firstComponent component1.inp"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc2","secondComponent component2.inp"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc3","thirdComponent component3.inp"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","700"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("testModule","1"));
       // component1 parameters
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","7"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","1"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","2"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("testModule","1"));
       // component2 parameters
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","6"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","2"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","3"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("testModule","1"));
       // build the device and run the same tests
       bool builds=false;
       int error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("DeviceDataMapping:Builds",builds);
       // check that the device has the right number of nodes (5+7+6)
       // internal nodes + boundary nodes + ghost nodes (3+5+4)+4+2 = 18
       int totalNodes = pDeviceData->pSolutionData->numNodes;
       bool nodes = false;
       int expectedNumNodes =
         pDeviceData->deviceComponents[0]->pSolutionData->numNodes - 2 -
         2*pDeviceData->deviceComponents[0]->pSolutionData->numGhostNodes +
         pDeviceData->deviceComponents[1]->pSolutionData->numNodes - 2 -
         2*pDeviceData->deviceComponents[1]->pSolutionData->numGhostNodes +
         pDeviceData->deviceComponents[2]->pSolutionData->numNodes - 2 -
         2*pDeviceData->deviceComponents[2]->pSolutionData->numGhostNodes +
         pDeviceData->deviceComponents.size()+1+
         2*pDeviceData->pSolutionData->numGhostNodes;
       if (totalNodes == expectedNumNodes) {
         nodes = true;
       } else {
         std::cout << "Wrong number of nodes in DeviceDataMapping" << std::endl;
         std::cout << "Got " << totalNodes << " Expected " << expectedNumNodes << std::endl;
         std::cout << pDeviceData->deviceComponents[0]->pSolutionData->numNodes  << " "
                   << pDeviceData->deviceComponents[1]->pSolutionData->numNodes  << " "
                   << pDeviceData->deviceComponents[2]->pSolutionData->numNodes  << " "
                   << pDeviceData->deviceComponents[2]->pSolutionData->numGhostNodes  << " "
                   << pDeviceData->deviceComponents.size()
                   << std::endl;
       }
       result.UpdateResult("DeviceDataMapping:NodeCount",nodes);
       // check that the mapping is correct, use the coordinates as a check
       // ignore ghost nodes
       bool coords=true;
       for (int i=0; i<pDeviceData->deviceComponents.size(); ++i) {
         int nodes  = pDeviceData->deviceComponents[i]->pSolutionData->numNodes;
         //int end = pDeviceData->deviceComponents[i]->pSolutionData->iEndInternal+1;
         for (int j=0; j<nodes; ++j) {
           double componentX = pDeviceData->deviceComponents[i]->pSolutionData->xCoords[j];
           int deviceIndex = pDeviceData->deviceComponents[i]->myDeviceNodes[j];
           double deviceX = pDeviceData->pSolutionData->xCoords[deviceIndex];
           if( componentX != deviceX) {
             std::cout << "Mismatch between component and device x coordinates" << std::endl;
             std::cout << "component x[" << j << "] = " << componentX
                       << " device x[" << deviceIndex << "] = " << deviceX << std::endl;
             coords = false;
           }
         }
       }
       result.UpdateResult("DeviceDataMapping:Mapping",coords);
       // compute solution from the physics module and propagate back to the device
       for (int i=0; i<pDeviceData->deviceComponents.size(); ++i) {
         pDeviceData->deviceComponents[i]->componentPhysicsModules[0]->SolvePhysics();
       }
       pDeviceData->CopyDataFromComponents();
       // check that the solution data is correct
       // we expect that the solution data is temperature*x[i]
       // by one for each index
       bool data = false;
       double expectedValues[totalNodes];
       // set expected values
       //int numNodes1 = pDeviceData->deviceComponents[0]->pSolutionData->numNodes;
       //int numNodes2 = pDeviceData->deviceComponents[1]->pSolutionData->numNodes;
       for (int i=0; i<totalNodes; ++i) {
         expectedValues[i]=pDeviceData->pSolutionData->temperature*
                           pDeviceData->pSolutionData->xCoords[i];
       }
       // set some boundary values for special cases
       expectedValues[0]=0.;
       expectedValues[totalNodes-1]=0.;
       // internal boundarys are summed from both components, double our expected value
       expectedValues[5]*=2;
       expectedValues[11]*=2;
       // we don't copy the component ghost node values back to the device
       // they are only used by the components
       int iStart = pDeviceData->pSolutionData->iStartInternal-1;
       int iEnd = pDeviceData->pSolutionData->iEndInternal+1;
       data = true;
       for (int i=iStart; i<=iEnd; ++i) {
         // solution is a multivector. [i] returns a pointer to a array of doubles at index i.
         double* val = (*(pDeviceData->pSolutionData->solutionEpetra))[0];
         if (expectedValues[i] == val[i]) {
           // this preserves previous settings of data, have to get all data points
           // true to pass the test
           data = data && true;
         } else {
           data = false;
           std::cout << "Incorrect solution data in DeviceDataMapping" << std::endl;
           std::cout << "At device index " << i << " xCoords[" << i
                     << "]=" << pDeviceData->pSolutionData->xCoords[i] << std::endl;
           std::cout << "Got " << val[i] << " Expected " << expectedValues[i] << std::endl;
         }
       }
       result.UpdateResult("DeviceDataMapping:CorrectDataToDevice",data);
       // now scale the result at the device level and propagate the answer back
       // down to the components
       pDeviceData->pSolutionData->solutionEpetra->Scale(5);
       pDeviceData->CopyDataToComponents();
       // set new expected answer
       for (int i=0; i<totalNodes; ++i) {
         expectedValues[i]*=5;
       }
       data = true;
       for (int i=0; i<pDeviceData->deviceComponents.size(); ++i) {
         // solution is a multivector. [i] returns a pointer to a array of doubles at index i.
         double* val = (*(pDeviceData->deviceComponents[i]->pSolutionData->solutionEpetra))[0];
         for (int j=0; j<pDeviceData->deviceComponents[i]->pSolutionData->numNodes; ++j) {
           int index = pDeviceData->deviceComponents[i]->myDeviceNodes[j];
           if (expectedValues[index] == val[j]) {
             // this preserves previous settings of data, have to get all data points
             // true to pass the test
             data = data && true;
           } else {
             data = false;
             std::cout << "In component " << i << std::endl;
             std::cout << "Incorrect solution data in DeviceDataMapping" << std::endl;
             std::cout << "Device index was " << index << std::endl;
             std::cout << "Got " << val[j] << " Expected "
                       << expectedValues[index] << std::endl;
           }
         }
       }
       result.UpdateResult("DeviceDataMapping:CorrectDataFromDevice",data);
       delete pDeviceData;
     }