ICED_Physics: ICED::HalfCell::DeviceData::CopyDataFromComponents
int CopyDataFromComponents ()
Copy device data from the component level.
This function copies the component level Trilinos data structures into the device counterpart. Copies solution data and function evalution.
Returns
int An error code
Test:
Test__DeviceDataMapping
Todo:
Add support for jacobian.
Definition at line 289 of file DeviceData.cpp.
References DeviceData::deviceComponents, SolutionData::functionEpetra, DeviceData::pSolutionData, SolutionData::solutionEpetra, and ICED::HalfCell::solutionVariable_t_MAX.
Referenced by DeviceData::BuildDevice(), DeviceData::DeviceAssembleF(), and TestingObject< ResultsType >::Test__DeviceDataMapping().
{
     std::ostringstream Ostr;
 /*
       for (int i=0; i<deviceComponents.size(); ++i) {
         std::cout << "Printing Component " << i << " Solution in CopyDataFromComponents" << std::endl;
         deviceComponents[i]->pSolutionData->solutionEpetra->Print(std::cout);
       }
 */
     // copy data to the device level, excluding internal ghost points
     pSolutionData->solutionEpetra->PutScalar(0.);
     for (int k=0; k<solutionVariable_t_MAX; ++k) {
       for (size_t i=0; i<deviceComponents.size(); ++i) {
         double* solutionVector = (*(deviceComponents[i]->pSolutionData->
                                  solutionEpetra))[k];
         double* functionVector = (*(deviceComponents[i]->pSolutionData->
                                  functionEpetra))[k];
         int start = deviceComponents[i]->pSolutionData->iStartInternal-1;
         int end = deviceComponents[i]->pSolutionData->iEndInternal+1;
         //
         // put the external ghost nodes into the device solution
         // assumes the first component is on the left and the last
         // component is on the right
         //
         if (i == 0)
           start--;
         if (i == deviceComponents.size())
           end++;
         for (int j=start; j<=end; ++j) {
           global_ordinal_type rowIndex = deviceComponents[i]->myDeviceNodes[j];
           int lclerr = pSolutionData->solutionEpetra->
                        //ReplaceGlobalValue(rowIndex, k, solutionVector[j]);
                        SumIntoGlobalValue(rowIndex, k, solutionVector[j]);
           if (lclerr != 0) {
             Ostr << "Error copying solution data from the components" << std::endl;
             Ostr << "Component " << i << " Row " << j << std::endl;
             StdOut(Ostr.str());
             return(lclerr);
           }
           // Use sum here to average the values at boundary nodes
           // at internal boundaries, the data is divided by 2 to account for the overlap
           lclerr = pSolutionData->functionEpetra->
                    SumIntoGlobalValue(rowIndex, k, functionVector[j]);
           if (lclerr != 0) {
             Ostr << "Error copying solution data from the components" << std::endl;
             Ostr << "Component " << i << " Row " << j << std::endl;
             StdOut(Ostr.str());
             return(lclerr);
           }
         }
       }
     }
 /*
     std::cout << "Printing Device Solution in CopyDataToDevice" << std::endl;
     pSolutionData->solutionEpetra->Print(std::cout);
 */
     return(0);
   }