ICED_Physics: Diffusion Class Reference
Diffusion Class Reference
Physics module that handles non-linear diffusion.
Detailed Description
Physics module that handles non-linear diffusion.
Definition at line 631 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
Diffusion ()
Default constructor.
Diffusion (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~Diffusion ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Physics solution.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
Diffusion () inline
Default constructor.
Definition at line 638 of file PhysicsModule.hpp.
References Diffusion::Initialize().
 {Initialize();};
Diffusion (SolutionData * solutionData, GlobalType & globin) inline
Constructor for solution data and global object.
Definition at line 643 of file PhysicsModule.hpp.
References Diffusion::Initialize().
                                                               : PhysicsModule(solutionData, globin) {
       Diffusion::Initialize();
     };
~Diffusion () inline
Default destructor.
Definition at line 650 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 659 of file PhysicsModule.hpp.
References ICED::HalfCell::conc_e, PhysicsModule::idealParameters, PhysicsModule::moduleName, and PhysicsModule::variableIndex.
Referenced by Diffusion::Diffusion().
                       {
       moduleName="Diffusion";
       SetName(moduleName);
       variableIndex=conc_e;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ConcentrationDiffusion","0"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("electrolyteVolumeFraction","1"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("bruggemanCoefficient","2"));
     };
void SolvePhysics () virtual
Physics solution.
The Diffusion function is a module that calculates the motion of ions due to a concentration gradient. The overall governing equation for the time-dependent ion concentration is Diffusion + IonMigration + WallFlux:
This equation represents the material balance on the ion (e.g., lithium) in the polymer/salt within porous electrode theory where the solution and matrix phases are treated as superimposed continua. The diffusion term of the overall governing equation is the first term on the RHS, and the basic function becomes
where
The discrete version of the above equation is:
where the discrete version of is computed by the concentration-dependent diffusion coefficient submodule (ConcentrationDiffusion) where is the concentration for species . and similarly for .
Todo:
add unit test for non-uniform grid spacing at the boundary nodes
Implements PhysicsModule.
Definition at line 19 of file Diffusion.cpp.
References SolutionData::bruggemanCoefficient, ICED::HalfCell::conc_e, SolutionData::concentrationDiffusion, SolutionData::dx, SolutionData::electrolyteVolumeFraction, SolutionData::function, SolutionData::iStartInternal, SolutionData::jacobian, PhysicsModule::pSolutionData, SolutionData::solutionData, and SolutionData::xCoords.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     //Ostr << "Hello from SolvePhysics" << std::endl;
     // get diffusion coefficients
     std::vector<double> *concDiffusion = &pSolutionData->concentrationDiffusion;
     std::vector<double> *concDiffusionP = &pSolutionData->
          concentrationDiffusionDer;
     // take into account the electrolyte volume fraction
     double factor = pow(pSolutionData->electrolyteVolumeFraction,
                         pSolutionData->bruggemanCoefficient);
     for (size_t i=0; i < concDiffusion->size(); ++i) {
       (*concDiffusion)[i]*=factor;
       (*concDiffusionP)[i]*=factor;
     }
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     double value1, value2;
     int iStartIn = pSolutionData->iStartInternal-1;
     int iEndIn = pSolutionData-> iEndInternal+1;
 /*
     Ostr << "dx = " << pSolutionData->dx << std::endl;
     //Print out concentration
     Ostr << "concentration = ";
     for(int i = iStartIn; i <= iEndIn; ++i){
       Ostr << (*pSolution)[i][conc_e] << " ";
     }
     Ostr << std::endl;
     //Print out concentrationDiffusion
     Ostr << "concentrationDiffusion = ";
     for(int i = iStartIn; i <= iEndIn; ++i){
       Ostr << (*concDiffusion)[i] << " ";
     }
     Ostr << std::endl;
     //Print out concentrationDiffusionDer
     Ostr << "concentrationDiffusionDer = ";
     for(int i = iStartIn; i <= iEndIn; ++i){
       Ostr << (*concDiffusionP)[i] << " ";
     }
     Ostr << std::endl;
 */
     //Sum the diffusion function values into the function
     //for  Diffusion + ion migration + wallflux.
     //Sum only for the interior nodes (boundary nodes
     //will be treated separately
      // dx to the left and right, used for non-uniform grid spacing at the nodes
      double dxr=pSolutionData->dx;
      double dxl=pSolutionData->dx;
     for(int i = iStartIn; i <= iEndIn; ++i){
 /*
     // old implementation for uniform grid spacing
       value1 = (*pSolution)[i+1][conc_e]*(*pSolution)[i+1][conc_e];
       value1 -= 2.0*(*pSolution)[i+1][conc_e]*(*pSolution)[i-1][conc_e];
       value1 += (*pSolution)[i-1][conc_e]*(*pSolution)[i-1][conc_e];
       value1 *= (*concDiffusionP)[i]/4.0;
       value2 = (*pSolution)[i+1][conc_e] - 2.0*(*pSolution)[i][conc_e];
       value2 += (*pSolution)[i-1][conc_e];
       value2 *= (*concDiffusion)[i];
       value1 += value2;
       value1 *= (1.0/(pSolutionData->dx*pSolutionData->dx));
 */
       // set dxl,dxr at boundary nodes
       if (i == iStartIn)
         dxl = pSolutionData->xCoords[iStartIn]-pSolutionData->xCoords[iStartIn-1];
       else if (i == iEndIn)
         dxr = pSolutionData->xCoords[iEndIn+1]-pSolutionData->xCoords[iEndIn];
       value1 = (*pSolution)[i+1][conc_e]*(*pSolution)[i+1][conc_e]
              - 2.0*(*pSolution)[i+1][conc_e]*(*pSolution)[i-1][conc_e]
              + (*pSolution)[i-1][conc_e]*(*pSolution)[i-1][conc_e];
       value1 *= (*concDiffusionP)[i];
       value2 = (1+dxl/dxr)*((*pSolution)[i+1][conc_e]-(*pSolution)[i][conc_e])
              + (1+dxr/dxl)*((*pSolution)[i-1][conc_e]-(*pSolution)[i][conc_e]);
       value2 *= 2*(*concDiffusion)[i];
       value1 += value2;
       value1 *= (1.0/(dxl+dxr)/(dxl+dxr));
       //(*pSolutionData->function)[i][0] += value1;
       (*pSolutionData->function)[i][conc_e] += value1/
         pSolutionData->electrolyteVolumeFraction;
       Ostr << "computed Diffusion Function = " << value1 << std::endl;
 /*
       // old implementation for uniform mesh
       value1 = (*pSolution)[i+1][conc_e] - (*pSolution)[i-1][conc_e];
       value1 *= (*concDiffusionP)[i]/2.0;
       (*pSolutionData->jacobian)[i][i-1][0][conc_e] =
            ((*concDiffusion)[i] - value1) /
            (pSolutionData->dx*pSolutionData->dx);
       (*pSolutionData->jacobian)[i][i][0][conc_e] =
            -2.0*(*concDiffusion)[i] /
            (pSolutionData->dx*pSolutionData->dx);
       (*pSolutionData->jacobian)[i][i+1][0][conc_e] =
            ((*concDiffusion)[i] + value1) /
            (pSolutionData->dx*pSolutionData->dx);
 */
       //Enter the Jacobian value for (partial f) / (partial c)
       value1 = (*pSolution)[i+1][conc_e] - (*pSolution)[i-1][conc_e];
       value1 *= 2*(*concDiffusionP)[i];
       (*pSolutionData->jacobian)[i][i][0][conc_e] =
          -2.0*(*concDiffusion)[i]*(2+dxr/dxl+dxl/dxr)/(dxl+dxr)/(dxl+dxr);
       (*pSolutionData->jacobian)[i][i-1][0][conc_e] =
          (2*(*concDiffusion)[i]*(1+dxr/dxl)-value1)/(dxl+dxr)/(dxl+dxr);
       (*pSolutionData->jacobian)[i][i+1][0][conc_e] =
          (2*(*concDiffusion)[i]*(1+dxl/dxr)+value1)/(dxl+dxr)/(dxl+dxr);
       // reset dxl for interior nodes
       if (i == iStartIn)
         dxl = pSolutionData->dx;
     }
     Ostr << std::endl;
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
The documentation for this class was generated from the following files:
PhysicsModule.hpp
Diffusion.cpp