ICED_Physics: testModule Class Reference
testModule Class Reference
Physics module for testing.
Detailed Description
Physics module for testing.
Definition at line 380 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
testModule ()
Default constructor.
testModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~testModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Sets a dummy solution data for testing.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
testModule () inline
Default constructor.
Definition at line 387 of file PhysicsModule.hpp.
References testModule::Initialize().
 {Initialize();};
testModule (SolutionData * solutionData, GlobalType & globin) inline
Constructor for solution data and global object.
Definition at line 392 of file PhysicsModule.hpp.
References testModule::Initialize().
                                                                : PhysicsModule(solutionData, globin) {
       testModule::Initialize();
     };
~testModule () inline
Default destructor.
Definition at line 399 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 408 of file PhysicsModule.hpp.
References PhysicsModule::idealParameters, PhysicsModule::moduleName, ICED::HalfCell::phi_s, and PhysicsModule::variableIndex.
Referenced by testModule::testModule().
                       {
       SetName("testModule");
       moduleName="testModule";
       // set this to phi_s to test the boundary conditions
       // this allows us to test both Neumann and Dirichlet BCs
       variableIndex=phi_s;
       //set the things for idealparameter
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","6"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","0"));
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","1"));
     };
void SolvePhysics () inline virtual
Sets a dummy solution data for testing.
Set the solution data to be solution[i]=temperature*x[i]
Implements PhysicsModule.
Definition at line 429 of file PhysicsModule.hpp.
References SolutionData::iEndInternal, SolutionData::iStartInternal, SolutionData::myGlobalElements, PhysicsModule::pSolutionData, SolutionData::solutionEpetra, SolutionData::temperature, and SolutionData::xCoords.
{
       FunctionEntry("SolvePhysics");
       std::ostringstream Ostr;
       int lclerr;
       int iStart = pSolutionData->iStartInternal-1;
       int iEnd = pSolutionData->iEndInternal+1;
       for (int i=iStart; i<=iEnd; ++i) {
         double data = pSolutionData->temperature*(pSolutionData->xCoords[i]);
         //std::cout << "data[" << i << "] " << data << std::endl;
         //std::cout << "xCoords[" << i << "] " << pSolutionData->xCoords[i] << std::endl;
         global_ordinal_type row = pSolutionData->myGlobalElements[i];
         lclerr = pSolutionData->solutionEpetra->ReplaceGlobalValue(row, 0, data);
         if (lclerr != 0) {
           Ostr << "Problem setting solution data" << std::endl;
           StdOut(Ostr.str());
           FunctionExit("SolvePhysics");
           break;
         }
       }
       FunctionExit("SolvePhysics");
     };
The documentation for this class was generated from the following file:
PhysicsModule.hpp