ICED_Physics: ICED::TestingObject::Test__Intercalation
void Test__Intercalation (ResultsType & result) inline
Test for ICED::Intercalation.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of the Intercalation module.
This function calls another function that actually sets up the input parameters and calls the Intercalation SolvePhysics. This function calls the other function with differing total time steps to run. It verifies that the percent error goes down the greater the number of time steps are used.
Definition at line 5292 of file ICEDTest.H.
References TestingObject< ResultsType >::RunIntercalationModule().
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       bool works, allWorks = true;
       int totalTimeSteps = 10;
       std::vector<double> percentError;
       int shortTau = 1, longTau = 0;
       //Call function that sets up and runs Intercalation
       //module for a given number of time steps,
       //using the long tau formulation
       for(int i=1; i <= totalTimeSteps; i++){
         works= RunIntercalationModule(result, i, &percentError, longTau);
         if(works == false)
           allWorks = false;
       }
       //Print out percentError to check
       std::cout << "long percentError: " << std::endl;
       for(int i=0; i < totalTimeSteps; i++){
         std::cout << i << ": " << percentError[i] << std::endl;
       }
       //Verify that the percent error is less than 7% and decreasing
       for(int i=0; i < totalTimeSteps; i++){
         if(percentError[i] > 0.07){
           allWorks = false;
           std::cout << "Intercalation fails due to long tau formulation having"
                << "an error greater than 7\%!!" << std::endl;
         }
         if(i > 0 && percentError[i] > percentError[i-1]){
           allWorks = false;
           std::cout << "Intercalation fails due to long tau formulation having"
                << "an increasing percent error!!" << std::endl;
         }
       }
       percentError.clear();
       //Call function that sets up and runs Intercalation
       //module for a given number of time steps,
       //using the short tau formulation
       for(int i=1; i <= totalTimeSteps; i++){
         works= RunIntercalationModule(result, i, &percentError, shortTau);
         if(works == false)
           allWorks = false;
       }
       //Print out percentError to check
       std::cout << "short percentError: " << std::endl;
       for(int i=0; i < totalTimeSteps; i++){
         std::cout << i << ": " << percentError[i] << std::endl;
       }
       //Verify that the percent error is less than 4% and decreasing
       for(int i=0; i < totalTimeSteps; i++){
         if(percentError[i] > 0.04){
           allWorks = false;
           std::cout << "Intercalation fails due to short tau formulation having"
                << "an error greater than 7\%!!" << std::endl;
         }
         if(i > 0 && percentError[i] > percentError[i-1]){
           allWorks = false;
           std::cout << "Intercalation fails due to short tau formulation having"
                << "an increasing percent error!!" << std::endl;
         }
       }
       result.UpdateResult("Intercalation:Works",allWorks);
     }