ICED_Physics: ICED::TestingObject::Test__ComponentBoundaryConditions
void Test__ComponentBoundaryConditions (ResultsType & result) inline
Test for ICED::ComponentBoundaryConditions.
Parameters
result ICED::TestResults object to store test results.
This function builds a DeviceData object and tests the application of boundary conditions at the component level.
This test loads the testModule PhysicsModule and does not exhaustively test every boudary condition for every implemented module. It is left to the unit tests for each module to check it's BC implementation.
Input is specified via Parameter objects. A test module is loaded that sets solution data to be a simple list of numbers based on the temperature parameter. Boundary conditions are applied for current collectors and separators. The expected results are verified.
Definition at line 636 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, ICED::HalfCell::conc_s, DeviceData::deviceComponents, ICED::HalfCell::dirichlet, TestingObject< ResultsType >::global, ICED::HalfCell::internal, ICED::HalfCell::neumann, ICED::HalfCell::none, TestingObject< ResultsType >::pDeviceData, ICED::HalfCell::phi_e, ICED::HalfCell::phi_s, and ICED::HalfCell::wallFlux.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       Ostr.str("");
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(3);
       // device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1","anode component1.inp"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc2","separator component2.inp"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc3","cathode component3.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","5"));
       //componentParameters[0].push_back(
         //IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","15"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("testModule","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "leftBC","currentCollector voltage 1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "rightBC","separator"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectrolytePotential","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialSolidPotential","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectrolyteLiConcentration","3"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialSolidLiConcentration","4"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectronProductionRate","5"));
       // component2 parameters
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","7"));
       //componentParameters[1].push_back(
         //IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","40"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","1"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","2"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("testModule","1"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("leftBC","separator"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("rightBC","separator"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectrolyteLiConcentration","8"));
       // component3 parameters
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","6"));
       //componentParameters[2].push_back(
         //IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","70"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","2"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMax","3"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "testModule","1"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "leftBC","separator"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "rightBC","currentCollector current 5"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectrolytePotential","11"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialSolidPotential","12"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectrolyteLiConcentration","13"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialSolidLiConcentration","14"));
       componentParameters[2].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>(
         "initialElectronProductionRate","15"));
       // build the device
       bool builds=false;
       int error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("ComponentBoundaryConditions:Builds",builds);
       // verify that the boundary conditions got set as we expected
       // this also checks the initialization for unset boundaries (for certain variables)
       bool setBC=true;
       // anode component
       // left is current collection with voltage separator, V=1
       if (pDeviceData->deviceComponents[0]->leftBCType[HalfCell::phi_e] == HalfCell::neumann &&
           pDeviceData->deviceComponents[0]->leftBCType[HalfCell::phi_s] == HalfCell::dirichlet &&
           pDeviceData->deviceComponents[0]->leftBCType[HalfCell::conc_e] == HalfCell::neumann &&
           pDeviceData->deviceComponents[0]->leftBCType[HalfCell::conc_s] == HalfCell::none &&
           pDeviceData->deviceComponents[0]->leftBCType[HalfCell::wallFlux] == HalfCell::none) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect left boundary type for component 1" << std::endl;
         setBC = false;
       }
       if (pDeviceData->deviceComponents[0]->leftBCValue[HalfCell::phi_e] == 0. &&
           pDeviceData->deviceComponents[0]->leftBCValue[HalfCell::phi_s] == 1. &&
           pDeviceData->deviceComponents[0]->leftBCValue[HalfCell::conc_e] == 0. &&
           pDeviceData->deviceComponents[0]->leftBCValue[HalfCell::conc_s] == 0. &&
           pDeviceData->deviceComponents[0]->leftBCValue[HalfCell::wallFlux] == 0.) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect left boundary value for component 1" << std::endl;
         setBC = false;
       }
       // right is separator
       if (pDeviceData->deviceComponents[0]->rightBCType[HalfCell::phi_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[0]->rightBCType[HalfCell::phi_s] == HalfCell::neumann &&
           pDeviceData->deviceComponents[0]->rightBCType[HalfCell::conc_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[0]->rightBCType[HalfCell::conc_s] == HalfCell::none &&
           pDeviceData->deviceComponents[0]->rightBCType[HalfCell::wallFlux] == HalfCell::none) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect right boundary type for component 1" << std::endl;
         setBC = false;
       }
       if (pDeviceData->deviceComponents[0]->rightBCValue[HalfCell::phi_e] == 0. &&
           pDeviceData->deviceComponents[0]->rightBCValue[HalfCell::phi_s] == 0. &&
           pDeviceData->deviceComponents[0]->rightBCValue[HalfCell::conc_e] == 0. &&
           pDeviceData->deviceComponents[0]->rightBCValue[HalfCell::conc_s] == 0. &&
           pDeviceData->deviceComponents[0]->rightBCValue[HalfCell::wallFlux] == 0.) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect right boundary value for component 1" << std::endl;
         setBC = false;
       }
       // separator component
       // left is separator
       if (pDeviceData->deviceComponents[1]->leftBCType[HalfCell::phi_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[1]->leftBCType[HalfCell::phi_s] == HalfCell::neumann &&
           pDeviceData->deviceComponents[1]->leftBCType[HalfCell::conc_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[1]->leftBCType[HalfCell::conc_s] == HalfCell::none &&
           pDeviceData->deviceComponents[1]->leftBCType[HalfCell::wallFlux] == HalfCell::none) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect left boundary type for component 2" << std::endl;
         setBC = false;
       }
       if (pDeviceData->deviceComponents[1]->leftBCValue[HalfCell::phi_e] == 0. &&
           pDeviceData->deviceComponents[1]->leftBCValue[HalfCell::phi_s] == 0. &&
           pDeviceData->deviceComponents[1]->leftBCValue[HalfCell::conc_e] == 0. &&
           pDeviceData->deviceComponents[1]->leftBCValue[HalfCell::conc_s] == 0. &&
           pDeviceData->deviceComponents[1]->leftBCValue[HalfCell::wallFlux] == 0.) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect left boundary value for component 2" << std::endl;
         setBC = false;
       }
       // right is separator
       if (pDeviceData->deviceComponents[1]->rightBCType[HalfCell::phi_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[1]->rightBCType[HalfCell::phi_s] == HalfCell::neumann &&
           pDeviceData->deviceComponents[1]->rightBCType[HalfCell::conc_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[1]->rightBCType[HalfCell::conc_s] == HalfCell::none &&
           pDeviceData->deviceComponents[1]->rightBCType[HalfCell::wallFlux] == HalfCell::none) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect right boundary type for component 2" << std::endl;
         setBC = false;
       }
       if (pDeviceData->deviceComponents[1]->rightBCValue[HalfCell::phi_e] == 0. &&
           pDeviceData->deviceComponents[1]->rightBCValue[HalfCell::phi_s] == 0. &&
           pDeviceData->deviceComponents[1]->rightBCValue[HalfCell::conc_e] == 0. &&
           pDeviceData->deviceComponents[1]->rightBCValue[HalfCell::conc_s] == 0. &&
           pDeviceData->deviceComponents[1]->rightBCValue[HalfCell::wallFlux] == 0.) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect right boundary value for component 2" << std::endl;
         setBC = false;
       }
       // cathode component
       // left is separator
       if (pDeviceData->deviceComponents[2]->leftBCType[HalfCell::phi_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[2]->leftBCType[HalfCell::phi_s] == HalfCell::neumann &&
           pDeviceData->deviceComponents[2]->leftBCType[HalfCell::conc_e] == HalfCell::internal &&
           pDeviceData->deviceComponents[2]->leftBCType[HalfCell::conc_s] == HalfCell::none &&
           pDeviceData->deviceComponents[2]->leftBCType[HalfCell::wallFlux] == HalfCell::none) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect left boundary type for component 3" << std::endl;
         setBC = false;
       }
       if (pDeviceData->deviceComponents[2]->leftBCValue[HalfCell::phi_e] == 0. &&
           pDeviceData->deviceComponents[2]->leftBCValue[HalfCell::phi_s] == 0. &&
           pDeviceData->deviceComponents[2]->leftBCValue[HalfCell::conc_e] == 0. &&
           pDeviceData->deviceComponents[2]->leftBCValue[HalfCell::conc_s] == 0. &&
           pDeviceData->deviceComponents[2]->leftBCValue[HalfCell::wallFlux] == 0.) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect left boundary value for component 3" << std::endl;
         setBC = false;
       }
       // right is current collector with current, i=5
       if (pDeviceData->deviceComponents[2]->rightBCType[HalfCell::phi_e] == HalfCell::neumann &&
           pDeviceData->deviceComponents[2]->rightBCType[HalfCell::phi_s] == HalfCell::neumann &&
           pDeviceData->deviceComponents[2]->rightBCType[HalfCell::conc_e] == HalfCell::neumann &&
           pDeviceData->deviceComponents[2]->rightBCType[HalfCell::conc_s] == HalfCell::none &&
           pDeviceData->deviceComponents[2]->rightBCType[HalfCell::wallFlux] == HalfCell::none) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect right boundary type for component 3" << std::endl;
         setBC = false;
       }
       if (pDeviceData->deviceComponents[2]->rightBCValue[HalfCell::phi_e] == 0. &&
           pDeviceData->deviceComponents[2]->rightBCValue[HalfCell::phi_s] == 5. &&
           pDeviceData->deviceComponents[2]->rightBCValue[HalfCell::conc_e] == 0. &&
           pDeviceData->deviceComponents[2]->rightBCValue[HalfCell::conc_s] == 0. &&
           pDeviceData->deviceComponents[2]->rightBCValue[HalfCell::wallFlux] == 0.) {
         setBC = true && setBC;
       } else {
           std::cout << "Incorrect right boundary value for component 3" << std::endl;
         setBC = false;
       }
       result.UpdateResult("ComponentBoundaryConditions:SetBC",setBC);
       // now we initialize the device so that we can apply the boundary conditions
       for (int i=0; i<pDeviceData->deviceComponents.size(); ++i) {
         pDeviceData->deviceComponents[i]->InitializeComponentSolution();
       }
       // first test that the components were initialized correctly
       // only check the internal nodes
       // the initialization values are hard coded above
       bool init=true;
       int component = 0;
       int iStart = pDeviceData->deviceComponents[component]->pSolutionData->iStartInternal;
       int iEnd = pDeviceData->deviceComponents[component]->pSolutionData->iEndInternal;
       for (int j=iStart; j<=iEnd; ++j) {
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::phi_e] != 1) {
           std::cout << "Incorrect initial solution data for phi_e in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::phi_s] != 2) {
           std::cout << "Incorrect initial solution data for phi_s in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::conc_e] != 3) {
           std::cout << "Incorrect initial solution data for conc_e in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::conc_s] != 4) {
           std::cout << "Incorrect initial solution data for conc_s in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::wallFlux] != 5) {
           std::cout << "Incorrect initial solution data for wallFlux in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
       }
       // the inital values are not set when the 2nd component is built
       // this part tests that they are initialized to 0
       component = 1;
       iStart = pDeviceData->deviceComponents[component]->pSolutionData->iStartInternal;
       iEnd = pDeviceData->deviceComponents[component]->pSolutionData->iEndInternal;
       for (int j=iStart; j<=iEnd; ++j) {
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::phi_e] != 0) {
           std::cout << "Incorrect initial solution data for phi_e in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::phi_s] != 0) {
           std::cout << "Incorrect initial solution data for phi_s in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::conc_e] != 8) {
           std::cout << "Incorrect initial solution data for conc_e in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::conc_s] != 0) {
           std::cout << "Incorrect initial solution data for conc_s in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::wallFlux] != 0) {
           std::cout << "Incorrect initial solution data for wallFlux in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
       }
       component = 2;
       iStart = pDeviceData->deviceComponents[component]->pSolutionData->iStartInternal;
       iEnd = pDeviceData->deviceComponents[component]->pSolutionData->iEndInternal;
       for (int j=iStart; j<=iEnd; ++j) {
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::phi_e] != 11) {
           std::cout << "Incorrect initial solution data for phi_e in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::phi_s] != 12) {
           std::cout << "Incorrect initial solution data for phi_s in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::conc_e] != 13) {
           std::cout << "Incorrect initial solution data for conc_e in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::conc_s] != 14) {
           std::cout << "Incorrect initial solution data for conc_s in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
         if ((*pDeviceData->deviceComponents[component]->pSolutionData->solutionData)[j][HalfCell::wallFlux] != 15) {
           std::cout << "Incorrect initial solution data for wallFlux in component "
                     << component << " at node " << j << std::endl;
           init = false;
         }
       }
       result.UpdateResult("ComponentBoundaryConditions:Initialization",init);
       for (int i=0; i<pDeviceData->deviceComponents.size(); ++i) {
         pDeviceData->deviceComponents[i]->ApplyComponentBC();
       }
       // now check that the BC's were applied correctly
       // only check anode and cathode, separator is redundant
       bool applyBC=true;
       // anode component
       // left is current collection with voltage separator, V=1
       // dirichlet BC
       int index = pDeviceData->deviceComponents[0]->pSolutionData->iStartInternal-1;
       if ((*pDeviceData->deviceComponents[0]->pSolutionData->solutionData)[index][HalfCell::phi_s] ==
           pDeviceData->deviceComponents[0]->leftBCValue[HalfCell::phi_s]) {
         applyBC = true && applyBC;
       } else {
           std::cout << "Incorrect left boundary value when applying BC for component 1" << std::endl;
         setBC = false;
       }
       // right is separator
       // neumann BC with 0 value,
       //testModule uses a central difference for the first order derivative
       index = pDeviceData->deviceComponents[0]->pSolutionData->iEndInternal-1;
       double leftVal = (*pDeviceData->deviceComponents[0]->pSolutionData->
                          solutionData)[index-1][HalfCell::phi_s];
       double rightVal = (*pDeviceData->deviceComponents[0]->pSolutionData->
                          solutionData)[index+1][HalfCell::phi_s];
       double dx = pDeviceData->deviceComponents[0]->pSolutionData->xCoords[index+1] -
                   pDeviceData->deviceComponents[0]->pSolutionData->xCoords[index-1];
       double expected = (rightVal - leftVal)/dx;
       if ( expected == pDeviceData->deviceComponents[0]->rightBCValue[HalfCell::phi_s]) {
         applyBC = true && applyBC;
       } else {
           std::cout << "Incorrect right boundary value when applying BC for component 1" << std::endl;
         setBC = false;
       }
       // cathode component
       // left is separator
       // neumann BC with 0 value
       index = pDeviceData->deviceComponents[1]->pSolutionData->iStartInternal-1;
       leftVal = (*pDeviceData->deviceComponents[1]->pSolutionData->
                          solutionData)[index-1][HalfCell::phi_s];
       rightVal = (*pDeviceData->deviceComponents[1]->pSolutionData->
                          solutionData)[index+1][HalfCell::phi_s];
       dx = pDeviceData->deviceComponents[1]->pSolutionData->xCoords[index+1] -
                   pDeviceData->deviceComponents[1]->pSolutionData->xCoords[index-1];
       expected = (rightVal - leftVal)/dx;
       if ( expected == pDeviceData->deviceComponents[1]->leftBCValue[HalfCell::phi_s]) {
         applyBC = true && applyBC;
       } else {
           std::cout << "Incorrect left boundary value when applying BC for component 3" << std::endl;
         setBC = false;
       }
       // right is current collector with current, i=5
       // neumann BC with non-zero value
       index = pDeviceData->deviceComponents[1]->pSolutionData->iEndInternal-1;
       leftVal = (*pDeviceData->deviceComponents[1]->pSolutionData->
                          solutionData)[index-1][HalfCell::phi_s];
       rightVal = (*pDeviceData->deviceComponents[1]->pSolutionData->
                          solutionData)[index+1][HalfCell::phi_s];
       dx = pDeviceData->deviceComponents[1]->pSolutionData->xCoords[index+1] -
                   pDeviceData->deviceComponents[1]->pSolutionData->xCoords[index-1];
       expected = (rightVal - leftVal)/dx;
       if ( expected == pDeviceData->deviceComponents[1]->rightBCValue[HalfCell::phi_s]) {
         applyBC = true && applyBC;
       } else {
           std::cout << "Incorrect right boundary value when applying BC for component 3" << std::endl;
         setBC = false;
       }
       result.UpdateResult("ComponentBoundaryConditions:ApplyBC",applyBC);
       delete pDeviceData;
     }