ICED_Physics: ICED::TestingObject::Test__DeviceData
void Test__DeviceData (ResultsType & result) inline
Test for ICED::DeviceData.
Parameters
result ICED::TestResults object to store test results.
This function implements builds a DeviceData object and tests a couple of I/O features, specifically that input is passed from the device to the component level and can be overwritten at the component level
There is a test script to copy the input files to IO_Unit_Test. The test script returns the results of the IOCopy test. This test will not pass if IOCopy does not pass.
Definition at line 183 of file ICEDTest.H.
References DeviceData::BuildDevice(), DeviceData::deviceComponents, DeviceData::GetDeviceComponentParameters(), TestingObject< ResultsType >::global, TestingObject< ResultsType >::pDeviceData, DeviceData::pSolutionData, and SolutionData::temperature.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       bool builds=false;
       bool propagateDown=false;
       bool componentDataMod=false;
       bool readVectorData=false;
       std::ostringstream Ostr;
       Ostr.str("");
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       // test for errors during build
       // this method tests the file read functionality. It is the way the code
       // will be run by the user
       IRAD::Util::Parameters deviceParams;
       std::string inputFile = "IO_Unit_Test/testInputMultiComponent.inp";
       std::ifstream Input;
       Input.open(inputFile.c_str());
       if(!Input) {
         Ostr.str("");
         Ostr << "Failed to open input file in device test" << std::endl;
         std::cout << Ostr.str();
       }
       deviceParams.ReadFromStream(Input);
       //int error = pDeviceData->BuildDevice(deviceParams);
       std::vector<IRAD::Util::Parameters> componentParams;
       int error =  pDeviceData->GetDeviceComponentParameters(deviceParams, componentParams);
       error = pDeviceData->BuildDevice(deviceParams, componentParams);
       if (error == 0)
         builds=true;
       result.UpdateResult("DeviceData:Builds",builds);
       // check that data propagated down from the device to the physics module
       // this happens when a component doesn't overwrite the data
       if (pDeviceData->deviceComponents[1]->componentPhysicsModules[0]->pSolutionData->temperature ==
           pDeviceData->pSolutionData->temperature)
         propagateDown = true;
       result.UpdateResult("DeviceData:PropagateData",propagateDown);
       // check that the components can modify their data if input values are
       // specified in the input file
       if (pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->temperature !=
           pDeviceData->pSolutionData->temperature)
         componentDataMod = true;
       result.UpdateResult("DeviceData:ComponentModifyData",componentDataMod);
       // check that the component 1 vector was read in correctly
       std::vector<double> transCoeff(3);
       transCoeff = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                  ->pSolutionData->transferenceCoefficients;
       std::cout << "transCoeff = " << transCoeff[0] << " "
                 << transCoeff[1] << " " << transCoeff[2] << std::endl;
       if(transCoeff[0] == 1.0 && transCoeff[1] == 2.0 && transCoeff[2] == 3.4)
         readVectorData = true;
       std::cout << "readVectorData = " << readVectorData << std::endl;
       result.UpdateResult("DeviceData:ReadVectorData",readVectorData);
       // now test loading input data without files
       // this is never used by a user, but is used in the testing framework
       delete pDeviceData;
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       builds=false;
       propagateDown=false;
       componentDataMod=false;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(2);
       // device parameters
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("iterationLimit","5"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("tmax","1.5"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","500"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1","firstComponent component1.inp"));
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc2","secondComponent component2.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","0"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xmax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("temperature","300"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
             ("transferenceCoefficients","1.0 2.0 3.4"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ionMigration","1"));
       // component1 parameters
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("numNodes","7"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xMin","1"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("xmax","2"));
       componentParameters[1].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("electronMigration","1"));
       // build the device and run the same tests
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("DeviceData:Builds2",builds);
       // check that data propagated down from the device to the physics module
       // this happens when a component doesn't overwrite the data
       if (pDeviceData->deviceComponents[1]->componentPhysicsModules[0]->pSolutionData->temperature ==
           pDeviceData->pSolutionData->temperature)
         propagateDown = true;
       result.UpdateResult("DeviceData:PropagateData2",propagateDown);
       // check that the components can modify their data if input values are
       // specified in the input file
       if (pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->pSolutionData->temperature !=
           pDeviceData->pSolutionData->temperature)
         componentDataMod = true;
       result.UpdateResult("DeviceData:ComponentModifyData2",componentDataMod);
       // check that the component 1 vector was read in correctly
       std::vector<double> transCoeff2(3);
       transCoeff2 = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                  ->pSolutionData->transferenceCoefficients;
       if(transCoeff2[0] == 1.0 && transCoeff2[1] == 2.0 && transCoeff2[2] == 3.4)
         readVectorData = true;
       result.UpdateResult("DeviceData:ReadVectorData2",readVectorData);
       delete pDeviceData;
     }