ICED_Physics: ICED::TestingObject::Test__WallFlux
void Test__WallFlux (ResultsType & result) inline
Test for ICED::wallFlux.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of a wall-flux module.
This fucntion initializes the input data values for the simulation, and then calls another function that initializes the test fixtrue solution data object. It then calls the Wall Flux class: SolvePhysics. Jacobian vector with the correct values
Definition at line 3554 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, ICED::HalfCell::conc_s, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, TestingObject< ResultsType >::pDeviceData, ICED::HalfCell::phi_e, ICED::HalfCell::phi_s, and ICED::HalfCell::wallFlux.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__WallFlux" << std::endl;
       bool builds=false;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int error;
       int numNodes=6;
       std::vector<double> transCoeff(3);
       std::vector<double> solution(numNodes+2);
       std::vector<double> x(numNodes+2);
       std::vector<double> coefficient(3);
       std::stringstream ss;
       ss << numNodes;
       transCoeff[0] = 1.0;
       transCoeff[1] = 2.3;
       transCoeff[2] = 3.4;
       ss << transCoeff[0] << " " << transCoeff[1] << " " << transCoeff[2];
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("ecdc1",
              "firstComponent component1.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("numNodes", "6"));
       //componentParameters[0].push_back(
         //IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         //("surfaceAreaA","20"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("numberOfIons","2"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("xMin","-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
         ("xMax","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("TransferenceNumber","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("WallFlux","1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("transferenceCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("electrolyteVolumeFraction","0.5"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("poreRadius","2"));
       // build the device
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("WallFlux:Builds",builds);
       int iStartIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->xCoords;
       // set phi_e values to x^2 + 2x +3
       coefficient[0] = 1;
       coefficient[1] = 2;
       coefficient[2] = 3;
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << "Parabolic Function Output  " << solution[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::phi_e]=solution[i];
       }
       // set phi_s values to 2x^2 + 3x +4
       coefficient[0] = 2;
       coefficient[1] = 3;
       coefficient[2] = 4;
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << "Parabolic Function Output  " << solution[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::phi_s]=solution[i];
       }
       // set conc_e values to -4x^2 + 5x -6
       coefficient[0] = -4;
       coefficient[1] = 5;
       coefficient[2] = -6;
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << "Parabolic Function Output  " << solution[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]=solution[i];
       }
       // set conc_s values to 0.5x^2 + 4.2x - 8.1
       coefficient[0] = 0.5;
       coefficient[1] = 4.2;
       coefficient[2] = -8.1;
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << "Parabolic Function Output " << solution[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_s]=solution[i];
       }
       // set wallFlux values to 0.2x^2 + 3x +4
       coefficient[0] = 0.2;
       coefficient[1] = 3;
       coefficient[2] = 4;
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output wallFlux "
              << solution[i] << std::endl;
       }
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
             pSolutionData->solutionData)[i][ICED::HalfCell::wallFlux]=solution[i];
       }
       //Call TransferenceNumber module SolvePhysics function
       //(WallFlux depends on it)
      pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       std::cout << "componentPhysicsModules.size() = " <<
          pDeviceData->deviceComponents[0]->componentPhysicsModules.size()
          << std::endl;
       //Call WallFlux SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[1]->
          SolvePhysics();
       double value;
       double jn =  (*pDeviceData->deviceComponents[0]->pSolutionData->
                      solutionData)[iStartIn+1][ICED::HalfCell::wallFlux];
       double transNum = pDeviceData->deviceComponents[0]->pSolutionData->
                         transferenceNumber[iStartIn+1];
       double numIon =  pDeviceData->deviceComponents[0]->pSolutionData->numberOfIons;
       double As = 0.25;  // consistent with mesh settings above
       double volFrac =  pDeviceData->deviceComponents[0]->pSolutionData->electrolyteVolumeFraction;
       double exact = As*jn*(1-transNum)/numIon/volFrac;
       //Check WallFlux discretized function
       value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
               pSolutionData->function)[iStartIn+1][ICED::HalfCell::conc_e];
       if(fabs(value -exact) > 1.0e-5) {
           works = false;
           std::cout << "Failed in wallFlux, exact=" << exact << " computed = " << value << std::endl;
       }
       std::cout << "WallFlux: ";
       for(int i = iStartIn - 1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << (*pDeviceData->deviceComponents[0]->
              componentPhysicsModules[0]->pSolutionData->function)[i][ICED::HalfCell::conc_e] << " ";
       }
       std::cout << std::endl;
 /*
      //Check Jacobian for s_dot variable (wallFlux variable)
       value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[iStartIn][iStartIn][0][ICED::HalfCell::wallFlux];
       if(fabs(value + 66269.976) > 1.0e-5)
           works = false;
      std::cout << "Jacobian for s_dot: " << std::endl;
      for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=iStartIn-1; j <= iEndIn+1; j++){
           value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                ->pSolutionData->jacobian)[i][j][0][ICED::HalfCell::wallFlux];
           std::cout << std::setprecision(15) << value << " ";
         }
         std::cout << std::endl;
       }
      //Check Jacobian for conc_e variable
       value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->jacobian)[iStartIn+2][iStartIn+2][0][ICED::HalfCell::conc_e];
       if(fabs(value - 28902.2976) > 1.0e-5)
           works = false;
      std::cout << "Jacobian for conc_e: " << std::endl;
      for(int i=iStartIn-1; i <= iEndIn+1; i++){
         for(int j=iStartIn-1; j <= iEndIn+1; j++){
           value = (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
                ->pSolutionData->jacobian)[i][j][0][ICED::HalfCell::conc_e];
           std::cout << std::setprecision(15) << value << " ";
         }
         std::cout << std::endl;
       }
 */
       result.UpdateResult("WallFlux:Works",works);
       delete pDeviceData;
     }