ICED_Physics: ICED::TestingObject::Test__TransferenceNumber
void Test__TransferenceNumber (ResultsType & result) inline
Test for ICED::TransferenceNumber.
Parameters
result ICED::TestResults object to store test results.
This function implements a test of TransferenceNumber module.
This fucntion initializes the input data values for the simulation. It then calls the TransferenceNumber class SolvePhysics function, passing in test values for calculation. Finally it verifies that SolvePhysics populates its function and derivative with the correct values.
Definition at line 3816 of file ICEDTest.H.
References DeviceData::BuildDevice(), ICED::HalfCell::conc_e, DeviceData::deviceComponents, TestingObject< ResultsType >::GenerateParabolicFunction(), TestingObject< ResultsType >::global, and TestingObject< ResultsType >::pDeviceData.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       pDeviceData = new ICED::HalfCell::DeviceData(global);
       std::cout << "Running Test__TransferenceNumber" << std::endl;
       bool works=true;
       //bool propagateDown=false;
       //bool componentDataMod=false;
       int error;
       int numNodes=6;
       std::vector<double> transCoeff(3);
       std::vector<double> solution(numNodes+2);
       std::vector<double> coefficient(3);
       std::vector<double> x(numNodes+2);
       std::stringstream ss;
       IRAD::Util::Parameters deviceParameters;
       std::vector<IRAD::Util::Parameters> componentParameters(1);
       transCoeff[0] = 1.0;
       transCoeff[1] = 2.3;
       transCoeff[2] = 3.4;
       ss << transCoeff[0] << " " << transCoeff[1] << " " << transCoeff[2];
       deviceParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("ecdc1","firstComponent component1.inp"));
       // component1 parameters
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("numNodes", "6"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("transferenceCoefficients", ss.str()));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMin", "-1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("xMax", "1"));
       componentParameters[0].push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>
                         ("TransferenceNumber","1"));
       //error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       //if (error != 0)
       //  works=false;
       bool builds = false;
       // build the device
       error = pDeviceData->BuildDevice(deviceParameters, componentParameters);
       if (error == 0)
         builds=true;
       result.UpdateResult("TransferenceNumber:Builds",builds);
       int iStartIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iStartInternal;
       int iEndIn = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
            ->pSolutionData->iEndInternal;
       std::cout << "iStartIn = " << iStartIn << std::endl;
       std::cout << "iEndIn = " << iEndIn << std::endl;
       //Get x values for the nodes
       x = pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
           ->pSolutionData->xCoords;
       // set conc_e values to 0.5x^2 + 4.2x - 8.1
       coefficient[0] = 0.5;
       coefficient[1] = 4.2;
       coefficient[2] = -8.1;
       // Generate parabola
       GenerateParabolicFunction(solution, x, coefficient, iStartIn, iEndIn);
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
         std::cout << std::setprecision(15) << "Parabolic Function Output  " << solution[i] << std::endl;
       }
       //Initialize values for conc_e as the parabola
       for(int i = iStartIn-1; i<= iEndIn+1; i++){
        (*pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
             ->pSolutionData->solutionData)[i][ICED::HalfCell::conc_e]=solution[i];
       }
       //Call TransferenceNumber SolvePhysics function
       pDeviceData->deviceComponents[0]->componentPhysicsModules[0]->
          SolvePhysics();
       double value;
       //Check transferenceNumber
       std::cout << "transferenceNumber:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumber[i] << " ";
         value = transCoeff[0]*solution[i]*solution[i] + transCoeff[1]*solution[i] + transCoeff[2];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumber[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       //Check transferenceNumberDer
       std::cout << "transferenceNumberDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDer[i] << " ";
         value = transCoeff[0]*2.0*solution[i] + transCoeff[1];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDer[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       //Check transferenceNumberDerDer
       std::cout << "transferenceNumberDerDer:";
       for(int i=iStartIn-1; i<=iEndIn+1; i++){
         std::cout << pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDerDer[i] << " ";
         value = 2.0*transCoeff[0];
         if(fabs(value - pDeviceData->deviceComponents[0]->componentPhysicsModules[0]
              ->pSolutionData->transferenceNumberDerDer[i]) > 1.0e-10)
           works = false;
       }
       std::cout << std::endl;
       result.UpdateResult("TransferenceNumber:Works",works);
       delete pDeviceData;
     }