ICED_Physics: ICED::HalfCell::DeviceComponent::InitializeComponentPhysics
int InitializeComponentPhysics ()
Performs initialization of physics module data outside of timestepping.
This function intializes physics module that that does not need to be recalculated during the non-linear solver iteration. Used by the BackwardEuler transient solver.
InitializeComponent
ApplyComponentBC
module InitializePhysics
ApplyInternalBC
FinalizeComponent
Returns
int an error code
Test:
None
Definition at line 382 of file DeviceComponent.cpp.
References DeviceComponent::ApplyComponentBC(), DeviceComponent::ApplyInternalBC(), DeviceComponent::componentPhysicsModules, DeviceComponent::FinalizeComponent(), and DeviceComponent::InitializeComponent().
{
       std::ostringstream Ostr;
       InitializeComponent();
       ApplyComponentBC();
 /*
       std::cout << "In device component, before solve, printing Epetra x" << std::endl;
       pSolutionData->solutionEpetra->Print(std::cout);
       std::cout << "In device component, before solve, printing  Epetra f" << std::endl;
       pSolutionData->functionEpetra->Print(std::cout);
       std::cout << "In device component, before solve, printing Vector x" << std::endl;
       std::cout << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->solutionData)[i][2] << " ";
       std::cout << "]" << std::endl;
       std::cout << "In device component, before solve, printing  Vector f" << std::endl;
       std::cout << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->function)[i][2] << " ";
       std::cout << "]" << std::endl;
 */
       // loop over all modules and compute solutions
       for (size_t i=0; i<componentPhysicsModules.size(); ++i) {
         Ostr << "Initializing Physics for module " <<
           componentPhysicsModules[i]->moduleName << std::endl;
         componentPhysicsModules[i]->InitializePhysics();
       }
       ApplyInternalBC();
       FinalizeComponent();
 /*
       std::cout << "In device component, after solve, printing x" << std::endl;
       pSolutionData->solutionEpetra->Print(std::cout);
       std::cout << "In device component, after solve, printing f" << std::endl;
       pSolutionData->functionEpetra->Print(std::cout);
       std::cout << "In device component, after solve, printing Vector x" << std::endl;
       std::cout << "x=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->solutionData)[i][2] << " ";
       std::cout << "]" << std::endl;
       std::cout << "In device component, after solve, printing  Vector f" << std::endl;
       std::cout << "f=[";
       for (int i=0; i<pSolutionData->numMyElements; ++i)
         std::cout << (*pSolutionData->function)[i][2] << " ";
       std::cout << "]" << std::endl;
 */
       StdOut(Ostr.str(),3);
       return 0;
     } // Function InitializeComponentPhysics