ICED_Physics: ConcentrationDiffusion Class Reference
ConcentrationDiffusion Class Reference
Physics module for ConcentrationDiffusion of species i.
Detailed Description
Physics module for ConcentrationDiffusion of species i.
Definition at line 1090 of file PhysicsModule.hpp.
#include <Physics/include/PhysicsModule.hpp>
Public Member Functions
ConcentrationDiffusion ()
Default constructor.
ConcentrationDiffusion (SolutionData *solutionData, GlobalType &globin)
~ConcentrationDiffusion ()
Default destructor.
void Initialize ()
Initialization of the member data.
void SolvePhysics ()
Solves the ConcentrationDiffusion physics.
Public Member Functions inherited from PhysicsModule
PhysicsModule ()
Default constructor.
PhysicsModule (SolutionData *solutionData, GlobalType &globin)
Constructor for solution data and global object.
~PhysicsModule ()
Default destructor.
void Initialize ()
Initialization of the member data.
virtual void InitializePhysics ()
Solution timestep initialization.
void ApplyDirichletBC (int position, double value)
Application of Dirichlet boundary conditions.
void ApplyNeumannBC (int position, double value)
Application of Neumann boundary conditions.
void SetPriority (int priority)
Set Module Priority.
int CheckParams (IRAD::Util::Parameters &componentParameters)
Check input parameters.
Additional Inherited Members
Public Attributes inherited from PhysicsModule
ICED::HalfCell::SolutionData * pSolutionData
member data
solutionVariable_t variableIndex
denotes the solution variable, this is set to solutionVariable_t_MAX if the module does not participate in the global solution matrix this is the case for modules that provide spatially varying parameters Populated in each subclass in the initialize function
IRAD::Util::Parameters idealParameters
The required parameters that need to be set in the input file for proper module operation Populated in each subclass in the initialize function.
std::string moduleName
int modulePriority
Constructor & Destructor Documentation
ConcentrationDiffusion () inline
Default constructor.
Definition at line 1097 of file PhysicsModule.hpp.
References OhmsLawElectrolyte::Initialize().
 {Initialize();};
ConcentrationDiffusion (SolutionData * solutionData, GlobalType & globin) inline
Definition at line 1102 of file PhysicsModule.hpp.
References ConcentrationDiffusion::Initialize().
                                                                            : PhysicsModule(solutionData, globin) {
       ConcentrationDiffusion::Initialize();
     };
~ConcentrationDiffusion () inline
Default destructor.
Definition at line 1109 of file PhysicsModule.hpp.
 {};
Member Function Documentation
void Initialize () inline
Initialization of the member data.
Returns
void
Test:
None
Definition at line 1118 of file PhysicsModule.hpp.
References PhysicsModule::idealParameters, PhysicsModule::moduleName, ICED::HalfCell::solutionVariable_t_MAX, and PhysicsModule::variableIndex.
Referenced by ConcentrationDiffusion::ConcentrationDiffusion().
                       {
       moduleName="ConcentrationDiffusion";
       SetName(moduleName);
       variableIndex=solutionVariable_t_MAX;
       idealParameters.push_back(
         IRAD::Primitive::KeyValuePairObj<std::string,std::string>("concentrationDiffusionCoefficients","6"));
     };
void SolvePhysics () virtual
Solves the ConcentrationDiffusion physics.
The ConcentrationDiffusion SolvePhysics function is a submodule that solves for the concentration-dependent diffusion coefficient with units . The diffusion coefficient measures how quickly an ion moves through a solution. It is based on the concentration of electrolyte . The current implementation assumes a parabola, but other functions could be added. The coefficients of the parabola are read from the input file(s). Matching the coefficient to the equation of a parabola gives us
where and are constants (utilized in the vector pDiffCoeff in the function below). The calculation of the coefficient is used in calculating the Diffusion function.
Implements PhysicsModule.
Definition at line 20 of file ConcentrationDiffusion.cpp.
References ICED::HalfCell::conc_e, SolutionData::concentrationDiffusion, SolutionData::concentrationDiffusionDer, SolutionData::concentrationDiffusionDerDer, SolutionData::iEndInternal, SolutionData::iStartInternal, PhysicsModule::pSolutionData, and SolutionData::solutionData.
{
     FunctionEntry("SolvePhysics");
     std::ostringstream Ostr;
     //Ostr << "Hello from SolvePhysics" << std::endl;
     //int numNodes = pSolutionData->numNodes;
     int iStartIn = pSolutionData->iStartInternal-1;
     int iEndIn = pSolutionData->iEndInternal+1;
     std::vector< std::vector<double> >* pSolution = pSolutionData->solutionData;
     std::vector<double>* pDiffCoeff = &pSolutionData->
          concentrationDiffusionCoefficients;
     // Parabolic function for the concentration dependent diffusion
     // as a function of conc_e
     for(int i= iStartIn; i<=iEndIn; i++){
       pSolutionData->concentrationDiffusion[i] = (*pDiffCoeff)[0]*
            (*pSolution)[i][conc_e] *
            (*pSolution)[i][conc_e] + (*pDiffCoeff)[1]*
            (*pSolution)[i][conc_e] + (*pDiffCoeff)[2];
       //Ostr << std::setprecision(15) << "concDiff[" << i << "] = "
            //<< pSolutionData->concentrationDiffusion[i] << std::endl;
       pSolutionData->concentrationDiffusionDer[i] =
            2 * (*pDiffCoeff)[0] * (*pSolution)[i][conc_e] + (*pDiffCoeff)[1];
       //Ostr << std::setprecision(15) << "concDiffDer[" << i << "] = "
            //<< pSolutionData->concentrationDiffusionDer[i] << std::endl;
       pSolutionData->concentrationDiffusionDerDer[i] = 2 * (*pDiffCoeff)[0];
       //Ostr << std::setprecision(15) << "concDiffDerDer[" << i << "] = "
            //<< pSolutionData->concentrationDiffusionDerDer[i] << std::endl;
     }
     StdOut(Ostr.str(),3);
     FunctionExit("SolvePhysics");
   };
The documentation for this class was generated from the following files:
PhysicsModule.hpp
ConcentrationDiffusion.cpp