var files =
[
    [ "ActivityCoefficient.cpp", "ActivityCoefficient_8cpp.html", null ],
    [ "BatterySim.cpp", "BatterySim_8cpp.html", "BatterySim_8cpp" ],
    [ "ButlerVolmer.cpp", "ButlerVolmer_8cpp.html", null ],
    [ "ConcentrationDiffusion.cpp", "ConcentrationDiffusion_8cpp.html", null ],
    [ "DeviceComponent.cpp", "DeviceComponent_8cpp.html", null ],
    [ "DeviceComponent.hpp", "DeviceComponent_8hpp.html", "DeviceComponent_8hpp" ],
    [ "DeviceData.cpp", "DeviceData_8cpp.html", null ],
    [ "DeviceData.hpp", "DeviceData_8hpp.html", "DeviceData_8hpp" ],
    [ "DeviceModel.cpp", "DeviceModel_8cpp.html", null ],
    [ "DeviceModel.hpp", "DeviceModel_8hpp.html", "DeviceModel_8hpp" ],
    [ "Diffusion.cpp", "Diffusion_8cpp.html", null ],
    [ "ExampleHeader.hpp", "ExampleHeader_8hpp.html", "ExampleHeader_8hpp" ],
    [ "ExampleParallelProgram.C", "ExampleParallelProgram_8C.html", null ],
    [ "ExampleProgram.hpp", "ExampleProgram_8hpp.html", "ExampleProgram_8hpp" ],
    [ "ExampleSerialProgram.C", "ExampleSerialProgram_8C.html", null ],
    [ "ExampleSourceFile.C", "ExampleSourceFile_8C.html", "ExampleSourceFile_8C" ],
    [ "HalfCell.cpp", "HalfCell_8cpp.html", null ],
    [ "HalfCell.hpp", "HalfCell_8hpp.html", "HalfCell_8hpp" ],
    [ "ICEDTest.H", "ICEDTest_8H.html", "ICEDTest_8H" ],
    [ "Intercalation.cpp", "Intercalation_8cpp.html", "Intercalation_8cpp" ],
    [ "IonMigration.cpp", "IonMigration_8cpp.html", null ],
    [ "OhmsLawElectrolyte.cpp", "OhmsLawElectrolyte_8cpp.html", null ],
    [ "OhmsLawSolid.cpp", "OhmsLawSolid_8cpp.html", null ],
    [ "ParallelTestICED.C", "ParallelTestICED_8C.html", "ParallelTestICED_8C" ],
    [ "pepi.C", "pepi_8C.html", "pepi_8C" ],
    [ "PhysicsModule.hpp", "PhysicsModule_8hpp.html", [
      [ "PhysicsModule", "classICED_1_1HalfCell_1_1PhysicsModule.html", "classICED_1_1HalfCell_1_1PhysicsModule" ],
      [ "ionMigration", "classICED_1_1HalfCell_1_1ionMigration.html", "classICED_1_1HalfCell_1_1ionMigration" ],
      [ "electronMigration", "classICED_1_1HalfCell_1_1electronMigration.html", "classICED_1_1HalfCell_1_1electronMigration" ],
      [ "testModule", "classICED_1_1HalfCell_1_1testModule.html", "classICED_1_1HalfCell_1_1testModule" ],
      [ "ButlerVolmer", "classICED_1_1HalfCell_1_1ButlerVolmer.html", "classICED_1_1HalfCell_1_1ButlerVolmer" ],
      [ "WallFlux", "classICED_1_1HalfCell_1_1WallFlux.html", "classICED_1_1HalfCell_1_1WallFlux" ],
      [ "Diffusion", "classICED_1_1HalfCell_1_1Diffusion.html", "classICED_1_1HalfCell_1_1Diffusion" ],
      [ "OhmsLawElectrolyte", "classICED_1_1HalfCell_1_1OhmsLawElectrolyte.html", "classICED_1_1HalfCell_1_1OhmsLawElectrolyte" ],
      [ "OhmsLawSolid", "classICED_1_1HalfCell_1_1OhmsLawSolid.html", "classICED_1_1HalfCell_1_1OhmsLawSolid" ],
      [ "TransferenceNumber", "classICED_1_1HalfCell_1_1TransferenceNumber.html", "classICED_1_1HalfCell_1_1TransferenceNumber" ],
      [ "Intercalation", "classICED_1_1HalfCell_1_1Intercalation.html", "classICED_1_1HalfCell_1_1Intercalation" ],
      [ "ConcentrationDiffusion", "classICED_1_1HalfCell_1_1ConcentrationDiffusion.html", "classICED_1_1HalfCell_1_1ConcentrationDiffusion" ],
      [ "ActivityCoefficient", "classICED_1_1HalfCell_1_1ActivityCoefficient.html", "classICED_1_1HalfCell_1_1ActivityCoefficient" ],
      [ "IonMigration", "classICED_1_1HalfCell_1_1IonMigration.html", "classICED_1_1HalfCell_1_1IonMigration" ]
    ] ],
    [ "sep.C", "sep_8C.html", "sep_8C" ],
    [ "SolutionData.cpp", "SolutionData_8cpp.html", null ],
    [ "SolutionData.hpp", "SolutionData_8hpp.html", "SolutionData_8hpp" ],
    [ "Solver.cpp", "Solver_8cpp.html", "Solver_8cpp" ],
    [ "Solver.hpp", "Solver_8hpp.html", "Solver_8hpp" ],
    [ "TestICED.C", "TestICED_8C.html", "TestICED_8C" ],
    [ "TestICED.H", "TestICED_8H.html", [
      [ "TestComLine", "classICED_1_1TestComLine.html", "classICED_1_1TestComLine" ]
    ] ],
    [ "TransferenceNumber.cpp", "TransferenceNumber_8cpp.html", null ],
    [ "TrilinosExample.cpp", "TrilinosExample_8cpp.html", "TrilinosExample_8cpp" ],
    [ "TrilinosExample.hpp", "TrilinosExample_8hpp.html", "TrilinosExample_8hpp" ],
    [ "WallFlux.cpp", "WallFlux_8cpp.html", null ]
];