ICED_Physics: ICED::HalfCell::Driver
int ICED::HalfCell::Driver (int argc, char * argv[])
Unified driver for batterySim.
This driver is a direct replacement for main and is responsible for creating the "Program object" and calling its Initialization, Run, and Finalize methods.
Definition at line 248 of file HalfCell.hpp.
References SerialProgram::Initialize(), SerialProgram::Run(), and SerialProgram::VerbLevel().
     {
       ProgramType MyProgram(argc, argv);
       int retval = MyProgram.Initialize();
       if(retval){
         if(retval > 0){ // then there was an error
           MyProgram.ErrOut("Error in Program Initialization.\n");
           return(1);
         }
         else return(0); // no error, but the program should not continue
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("Calling RUN.\n");
       if(MyProgram.Run()){
         MyProgram.ErrOut("Error in Program RUN method.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1){
         std::ostringstream Ostr;
         MyProgram.Report(Ostr);
         MyProgram.StdOut(Ostr.str());
         MyProgram.StdOut("Calling Finalize.\n");
       }
       if(MyProgram.Finalize()){
         MyProgram.ErrOut("Error in Program Finalization.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("All done.\n");
       return(0);
     }