ICED_Physics: ICED::HalfCell::SetupSolver
int SetupSolver (Teuchos::RCP< DeviceData > & device)
initialization of the NOX solver
This function initializes the NOX solver.
Todo:
Parameterize the options for the NOX solver and enable them as file input through the device input file.
Definition at line 194 of file Solver.cpp.
Referenced by TestingObject< ResultsType >::Test__SolverOhmsLawElectrolyte(), TestingObject< ResultsType >::Test__SteadySolver(), TestingObject< ResultsType >::Test__SteadySolverNL(), and TransientSolverInterface::TransientBackwardEuler().
{
     //FunctionEntry("SetupSolver");
     std::ostringstream Ostr, Cstr;
     // create linear solver adapter
     // not sure if needed? This works with an XML file, can I use the input methods
     // I already have?
     //Stratimikos::DefaultLinearSolverBuilder lowsfCreator;
     // Create the factory for the LinearOpWithSolverBase object
     // this has constructors that take Teuchos::ParameterList's so
     // we will need to initialize it below
     //Teuchos::RCP<Thyra::LinearOpWithSolverFactoryBase<double> > W_factory;
     //W_factory = Teuchos::rcp(new Thyra::AztecOOLinearOpWithSolveFactory());
     // Create the top-level parameter list to control NOX.
     Teuchos::RCP<SolverInterface> solverInterface =
       Teuchos::rcp(new SolverInterface(device));
     //Teuchos::RCP<SolverInterface> solverInterface =
       //Teuchos::rcp(device->transientSolverInterface);
     //
     // "parameterList" (lowercase initial "p") is a "nonmember
     // constructor" that returns an RCP<ParameterList> with the
     // given name.
     Teuchos::RCP<Teuchos::ParameterList> NOXparameters =
       Teuchos::parameterList ("NOX");
     //
     // Set the printing parameters in the "Printing" sublist.
     //
     Teuchos::ParameterList& printParams = NOXparameters->sublist ("Printing");
     //printParams.set ("MyPID", Comm.MyPID ());
     printParams.set ("Output Precision", 3);
     printParams.set ("Output Processor", 0);
     printParams.set ("Output Information",
                      NOX::Utils::Error
                      //+ NOX::Utils::LinearSolverDetails
                      //+ NOX::Utils::StepperIteration
                      //+ NOX::Utils::StepperDetails
                      //+ NOX::Utils::StepperParameters
                      //+ NOX::Utils::OuterIteration
                      //+ NOX::Utils::OuterIterationStatusTest
                      //+ NOX::Utils::InnerIteration
                      //+ NOX::Utils::Parameters
                      //+ NOX::Utils::Details
                      //+ NOX::Utils::Warning
                     );
     //
     // Set the nonlinear solver parameters.
     //
     // Tell the nonlinear solver to use line search.
     NOXparameters->set ("Nonlinear Solver", "Line Search Based");
     //NOXparameters->set ("Nonlinear Solver", "Trust Region Based");
     //Teuchos::ParameterList& trustSearchParams = NOXparameters->sublist ("Trust Region");
     //Teuchos::ParameterList& dirTrustParams = trustSearchParams.sublist ("Direction");
     // Line search parameters.
     //Teuchos::ParameterList& searchParams = NOXparameters->sublist ("Line Search");
     // Tensor search parameters.
     Teuchos::ParameterList& searchParams = NOXparameters->sublist ("Line Search");
     searchParams.set ("Method", "More'-Thuente");
     // More'-Thuente options
     Teuchos::ParameterList& mtParams = searchParams.sublist("More'-Thuente");
     //mtParams.set("Maximum Step", 1.);
     mtParams.set("Curvature Condition", 0.7);
     mtParams.set("Optimize Slope Calculation", true);
     mtParams.set("Sufficient Decrease", 0.01);
     mtParams.set("Default Step", 1.);
 /*
     //searchParams.set ("Method", "Full Step");
     //Teuchos::ParameterList& fsParams = searchParams.sublist("Full Step");
     //fsParams.set("Curvature Condition", 0.5);
 */
     // Parameters for picking the search direction.
     Teuchos::ParameterList& dirParams = NOXparameters->sublist ("Direction");
     // Use Newton's method to pick the search direction.
     // This method goes in the wrong direction, maybe can tune it?
     dirParams.set ("Method", "Newton");
     Teuchos::ParameterList& newtonParams = dirParams.sublist ("Newton");
     newtonParams.set ("Forcing Term Method", "Constant");
     //newtonParams.set ("Forcing Term Method", "Type 1");
     Teuchos::ParameterList& lsParams = newtonParams.sublist ("Linear Solver");
 /*
     dirParams.set ("Method", "Steepest Descent");
     Teuchos::ParameterList& steepParams = dirParams.sublist ("Steepest Descent");
     //steepParams.set ("Scaling Type", "F 2-Norm");
     steepParams.set ("Scaling Type", "Quadratic Model Min");
 */
     // this fails "unable to apply jacobian"
     //dirParams.set ("Method", "NonlinearCG");
     //dirParams.set ("Method", "Broyden");
     // Parameters for Newton's method.
     //Teuchos::ParameterList& broydenParams = dirParams.sublist ("Broyden");
     //
     // Newton's method invokes a linear solver repeatedly.
     // Set the parameters for the linear solver.
     //
     // params for Broyden linear solver
     //Teuchos::ParameterList& lsParams = broydenParams.sublist ("Linear Solver");
     //Teuchos::ParameterList& lsParams = steepParams.sublist ("Linear Solver");
     // Use Aztec's implementation of GMRES, with at most 800 iterations,
     // a residual tolerance of 1.0e-4, with output every 50 iterations,
     // and Aztec's native ILU preconditioner.
     lsParams.set ("Aztec Solver", "GMRES");
     //lsParams.set ("Aztec Solver", "BiCGStab");
     lsParams.set ("Max Iterations", 800);
     lsParams.set ("Tolerance", 1e-4);
     //lsParams.set ("Output Frequency", 50);
     lsParams.set ("Output Frequency", 1);
     //lsParams.set ("Preconditioner", "New Ifpack");
     lsParams.set ("Preconditioner", "None");
     //lsParams.set ("Preconditioner", "ML");
     //lsParams.set ("Preconditioner", "AztecOO");
     lsParams.set ("Aztec Preconditioner", "Jacobi");
     lsParams.set ("Preconditioner Operator", "Use Jacobian");
     // Jacobian operator
     lsParams.set ("Jacobian Operator","Finite Difference");
     //lsParams.set ("Jacobian Operator","Matrix-Free");
     // Our SolverInterface implements both Required and
     // Jacobian, so we can use the same object for each.
     Teuchos::RCP<NOX::Epetra::Interface::Required> iReq = solverInterface;
     Teuchos::RCP<NOX::Epetra::Interface::Jacobian> iJac = solverInterface;
     // this call requires an external jacobian
 /*
     Teuchos::RCP<NOX::Epetra::LinearSystemAztecOO> linSys =
       Teuchos::rcp (new NOX::Epetra::LinearSystemAztecOO (printParams, lsParams,
                                              iReq, iJac, A, initialGuess));
 */
     // this calculates the jacobian for us
     // see the AztecOO documentation for available options
     Ostr << "Building Linear Solver" << std::endl;
     Teuchos::RCP<NOX::Epetra::LinearSystemAztecOO> linSys =
       Teuchos::rcp (new NOX::Epetra::LinearSystemAztecOO (printParams, lsParams,
                                              //iReq, initialGuess));
                                              iReq, (*device->globalDeviceSolution)));
     // Need a NOX::Epetra::Vector for constructor.
     Ostr << "Building Non-Linear Solver" << std::endl;
     //NOX::Epetra::Vector noxInitGuess (initialGuess, NOX::DeepCopy);
     NOX::Epetra::Vector noxInitGuess ((*device->globalDeviceSolution), NOX::DeepCopy);
     Teuchos::RCP<NOX::Epetra::Group> group =
       Teuchos::rcp (new NOX::Epetra::Group (printParams, iReq, noxInitGuess, linSys));
     Cstr << "NOX initial Guess:" << std::endl;
     noxInitGuess.print(Cstr);
     //
     // Set up NOX's iteration stopping criteria ("status tests").
     //
     // ||F(X)||_2 / N < 1.0e-4, where N is the length of F(X).
     //
     // NormF has many options for setting up absolute vs. relative
     // (scaled by the norm of the initial guess) tolerances, scaling or
     // not scaling by the length of F(X), and choosing a different norm
     // (we use the 2-norm here).
     Teuchos::RCP<NOX::StatusTest::NormF> testNormF =
       //Teuchos::rcp (new NOX::StatusTest::NormF (1.0e-4));
       Teuchos::rcp (new NOX::StatusTest::NormF (1.0));
     // At most 20 (nonlinear) iterations.
     Teuchos::RCP<NOX::StatusTest::MaxIters> testMaxIters =
       //Teuchos::rcp (new NOX::StatusTest::MaxIters (20));
       Teuchos::rcp (new NOX::StatusTest::MaxIters (40));
     // Combine the above two stopping criteria (normwise convergence,
     // and maximum number of nonlinear iterations).  The result tells
     // NOX to stop if at least one of them is satisfied.
     Teuchos::RCP<NOX::StatusTest::Combo> combo =
       Teuchos::rcp (new NOX::StatusTest::Combo (NOX::StatusTest::Combo::OR,
                                        testNormF, testMaxIters));
     // Create the NOX nonlinear solver.
     Ostr << "Creating Solver" << std::endl;
     device->noxSolver =
       NOX::Solver::buildSolver (group, combo, NOXparameters);
     //
     // figure out how to do this...probably need to nest this function
     // inside one of our global objects ...
     //
     /*
     StdOut(Ostr.str(),1);
     StdOut(Cstr.str(),1);
     //FunctionExit("SetupSolver");
     */
     return(0);
   } // Function SetupSolver