ICED_Physics: ICED::ExampleProgram Namespace Reference
ICED::ExampleProgram Namespace Reference
Encapsulate example program-specific code constructs.
Detailed Description
Encapsulate example program-specific code constructs.
This namespace contains all of the base code constructs that are used in the example programs. These example programs have several features which make them very easy to integrate in composite software systems.
Program is entirely encapsulated in program object
All screen output is automatically tagged with the program name
Common look-and-feel interface
Interface functionality allows menu-driven integration
Other convenient features of this API are:
Built-in stack tracing for debugging
Built-in profiling utilities
Advanced command-line handling
Built-in parallelism
Classes
class ExampleProgramComLine
The ComLineObject for the example programs.
class SerialProgram
Implementation of the basic parts of the serial program example.
Typedefs
typedef IRAD::Profiler::ProfilerObj ProfilerType
Convenience type definition for Profiler object.
typedef std::string StackType
Convenience type definition for program stack.
typedef
IRAD::Global::GlobalObj
< StackType, int, ProfilerType > GlobalType
Convenience type definition for the serial global object.
typedef ExampleProgramComLine ComLineType
Convenience type definition for the example comline object.
typedef IRAD::Global::Program
< GlobalType, ComLineType > SerialProgramType
Convenience type definition for the serial program.
typedef
ICED::ExampleProgram::SerialProgram SEProgramType
Convenience definition for serial program type.
Functions
template<typename ProgramType >
int Driver (int argc, char *argv[])
Unified driver for the example programs.
Typedef Documentation
typedef ExampleProgramComLine ComLineType
Convenience type definition for the example comline object.
Definition at line 114 of file ExampleProgram.hpp.
typedef IRAD::Global::GlobalObj<StackType,int,ProfilerType> GlobalType
Convenience type definition for the serial global object.
The global object encapsulates all of the built-in functionalities for a program. Its interface and implementation are defined in IRAD/include/Global.H
Definition at line 53 of file ExampleProgram.hpp.
typedef IRAD::Profiler::ProfilerObj ProfilerType
Convenience type definition for Profiler object.
Definition at line 41 of file ExampleProgram.hpp.
typedef ICED::ExampleProgram::SerialProgram SEProgramType
Convenience definition for serial program type.
Definition at line 479 of file ExampleProgram.hpp.
typedef IRAD::Global::Program<GlobalType,ComLineType> SerialProgramType
Convenience type definition for the serial program.
For a detailed description of the program type, see IRAD::Global::Program documentation.
Definition at line 121 of file ExampleProgram.hpp.
typedef std::string StackType
Convenience type definition for program stack.
Definition at line 45 of file ExampleProgram.hpp.
Function Documentation
int ICED::ExampleProgram::Driver (int argc, char * argv[])
Unified driver for the example programs.
This driver is exactly the same for both the serial and parallel example programs. It is a direct replacement for main and is responsible for creating the "Program object" and calling its Initialization, Run, and Finalize methods.
Definition at line 443 of file ExampleProgram.hpp.
References SerialProgram::Initialize(), SerialProgram::Run(), and SerialProgram::VerbLevel().
     {
       ProgramType MyProgram(argc,argv);
       int retval = MyProgram.Initialize();
       if(retval){
         if(retval > 0){ // then there was an error
           MyProgram.ErrOut("Error in Program Initialization.\n");
           return(1);
         }
         else return(0); // no error, but the program should not continue
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("Calling RUN.\n");
       if(MyProgram.Run()){
         MyProgram.ErrOut("Error in Program RUN method.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1){
         std::ostringstream Ostr;
         MyProgram.Report(Ostr);
         MyProgram.StdOut(Ostr.str());
         MyProgram.StdOut("Calling Finalize.\n");
       }
       if(MyProgram.Finalize()){
         MyProgram.ErrOut("Error in Program Finalization.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("All done.\n");
       return(0);
     }